#include "\ALF_Client\script_macros.hpp"
/*
File: fn_menuSonyP.sqf
Author: ALF Team
*/
if(!dialog) then {
	createDialog "ALF_SonyP_Dialog";
};
disableSerialization;
private _display = findDisplay 38999;
private _home = _display displayCtrl 39000;
private _SonyMenu = _display displayCtrl 39001;
private _SonyMenuBtnAppel = _display displayCtrl 39002;
private _SonyMenuBtnSms = _display displayCtrl 39003;
private _SonyMenuBtnContact = _display displayCtrl 39004;
private _SonyMenuBtnRegl = _display displayCtrl 39005;
private _SonyMenuBtnRadio = _display displayCtrl 39006;
private _SonyAppel = _display displayCtrl 39007;
private _SonyAppelBtn = _display displayCtrl 39008;
private _SonyAppelEdit = _display displayCtrl 39009;
private _SonyMenuLock = _display displayCtrl 39010;
private _SonyInCall = _display displayCtrl 39011;
private _SonyInCallHP = _display displayCtrl 39012;
private _SonyInCallMute = _display displayCtrl 39013;
private _SonyInCallBtnVolp = _display displayCtrl 39014;
private _SonyInCallBtnVolm = _display displayCtrl 39015;
private _SonyInCallBtnHP = _display displayCtrl 39016;
private _SonyInCallBtnMute = _display displayCtrl 39017;
private _SonyRingCall = _display displayCtrl 39018;
private _SonyInCallName = _display displayCtrl 39019;
private _SonyInCallNumber = _display displayCtrl 39020;
private _SonyInCallTime = _display displayCtrl 39021;
private _SonyInCallBtnRefuse = _display displayCtrl 39022;
private _SonyRingCallBtnDecro = _display displayCtrl 39023;
private _SonyRingCallBtnRefus = _display displayCtrl 39024;
private _SonyRegl = _display displayCtrl 39025;
private _SonyReglON1 = _display displayCtrl 39026;
private _SonyReglOFF1 = _display displayCtrl 39027;
private _SonyReglON2 = _display displayCtrl 39028;
private _SonyReglOFF2 = _display displayCtrl 39029;
private _SonyReglON3 = _display displayCtrl 39030;
private _SonyReglOFF3 = _display displayCtrl 39031;
private _SonyReglBtnAvion = _display displayCtrl 39032;
private _SonyReglBtnSilence = _display displayCtrl 39033;
private _SonyReglBtnAnon = _display displayCtrl 39034;
private _SonyDate = _display displayCtrl 39035;
private _SonyRadio = _display displayCtrl 39036;
private _SonyRadioBtn1 = _display displayCtrl 39037;
private _SonyRadioBtn2 = _display displayCtrl 39038;
private _SonyRadioBtn3 = _display displayCtrl 39039;
private _SonyRadioBtn4 = _display displayCtrl 39040;
private _SonyRadioBtn5 = _display displayCtrl 39041;
private _SonyRadioBtn6 = _display displayCtrl 39042;
private _SonyRadioBtn7 = _display displayCtrl 39043;
private _SonyRadioBtn8 = _display displayCtrl 39044;
private _SonyRadioBtn9 = _display displayCtrl 39045;
private _SonyRadioBtn10 = _display displayCtrl 39046;
private _SonyRadioBtn11 = _display displayCtrl 39047;
private _SonyRadioBtn12 = _display displayCtrl 39048;
private _SonyRadioBtn13 = _display displayCtrl 39049;
private _SonyRadioBtn14 = _display displayCtrl 39050;
private _SonyRadioBtn15 = _display displayCtrl 39051;
private _SonyRadioBtn16 = _display displayCtrl 39052;
private _SonyRadioBtn17 = _display displayCtrl 39053;
private _SonyRadioBtn21 = _display displayCtrl 39057;
private _SonyRadioCo1 = _display displayCtrl 39059;
private _SonyRadioCo2 = _display displayCtrl 39060;
private _SonyRadioCo3 = _display displayCtrl 39061;
private _SonyRadioCo4 = _display displayCtrl 39062;
private _SonyRadioCo5 = _display displayCtrl 39063;
private _SonyRadioCo6 = _display displayCtrl 39064;
private _SonyRadioCo7 = _display displayCtrl 39065;
private _SonyRadioCo8 = _display displayCtrl 39066;
private _SonyRadioCo9 = _display displayCtrl 39067;
private _SonyRadioCo10 = _display displayCtrl 39068;
private _SonyRadioCo11 = _display displayCtrl 39069;
private _SonyRadioCo12 = _display displayCtrl 39070;
private _SonyRadioCo13 = _display displayCtrl 39071;
private _SonyRadioCo14 = _display displayCtrl 39072;
private _SonyRadioCo15 = _display displayCtrl 39073;
private _SonyRadioCo16 = _display displayCtrl 39074;
private _SonyRadioCo17 = _display displayCtrl 39075;
private _SonyRadioCo21 = _display displayCtrl 39079;
private _SonyRadioNb1 = _display displayCtrl 39081;
private _SonyRadioNb2 = _display displayCtrl 39082;
private _SonyRadioNb3 = _display displayCtrl 39083;
private _SonyRadioNb4 = _display displayCtrl 39084;
private _SonyRadioNb5 = _display displayCtrl 39085;
private _SonyRadioNb6 = _display displayCtrl 39086;
private _SonyRadioNb7 = _display displayCtrl 39087;
private _SonyRadioNb8 = _display displayCtrl 39088;
private _SonyRadioNb9 = _display displayCtrl 39089;
private _SonyRadioNb10 = _display displayCtrl 39090;
private _SonyRadioNb11 = _display displayCtrl 39091;
private _SonyRadioNb12 = _display displayCtrl 39092;
private _SonyRadioNb13 = _display displayCtrl 39093;
private _SonyRadioNb14 = _display displayCtrl 39094;
private _SonyRadioNb15 = _display displayCtrl 39095;
private _SonyRadioNb16 = _display displayCtrl 39096;
private _SonyRadioNb17 = _display displayCtrl 39097;
private _SonyRadioNb21 = _display displayCtrl 39101;
private _SonyReglBtnVolp1 = _display displayCtrl 39103;
private _SonyReglBtnVolm1 = _display displayCtrl 39104;
private _SonyMenuBtnCentral = _display displayCtrl 39109;
private _SonyContacts = _display displayCtrl 39110;
private _SonyContactsAdd = _display displayCtrl 39111;
private _SonyContactsTexte = _display displayCtrl 39112;
private _SonyContactsList = _display displayCtrl 39113;
private _SonyFiche = _display displayCtrl 39114;
private _SonyFicheName = _display displayCtrl 39115;
private _SonyFicheNum = _display displayCtrl 39116;
private _SonyFicheBtnSms = _display displayCtrl 39117;
private _SonyFicheBtnAppel = _display displayCtrl 39118;
private _SonyFicheBtnDelete = _display displayCtrl 39119;
private _SonyCentral = _display displayCtrl 39120;
private _SonyCentralList = _display displayCtrl 39121;
private _SonyCentralBtnApp = _display displayCtrl 39122;
private _SonyCentralBtnRaf = _display displayCtrl 39123;
private _SonyCentralBtnRac = _display displayCtrl 39124;
private _SonyNewContact = _display displayCtrl 39125;
private _SonyNewContactAnn = _display displayCtrl 39126;
private _SonyNewContactAdd = _display displayCtrl 39127;
private _SonyNewContactName = _display displayCtrl 39128;
private _SonyNewContactNum = _display displayCtrl 39129;
private _SonyRadioRaf = _display displayCtrl 39130;
private _SonyRecents = _display displayCtrl 39131;
private _SonyRecentsLb = _display displayCtrl 39132;
private _SonyRecentsVider = _display displayCtrl 39133;
private _SonyRecentsApp = _display displayCtrl 39134;
private _SonyRecentsSms = _display displayCtrl 39135;
private _SonyAppelRecents = _display displayCtrl 39136;
private _SonyReglBtnFg = _display displayCtrl 39137;
private _SonyReglBtnFm = _display displayCtrl 39138;
private _SonyReglBtnFd = _display displayCtrl 39139;
private _SonyReglBtnF2g = _display displayCtrl 39140;
private _SonyReglBtnF2m = _display displayCtrl 39141;
private _SonyReglBtnF2d = _display displayCtrl 39142;
private _SonySms = _display displayCtrl 39143;
private _SonySmsLb = _display displayCtrl 39144;
private _SonySmsTexte = _display displayCtrl 39145;
private _SonySmsBtnRep = _display displayCtrl 39146;
private _SonySmsBtnSup = _display displayCtrl 39147;
private _SonySmsBtnNew = _display displayCtrl 39148;
private _SonyNewSms = _display displayCtrl 39149;
private _SonyNewSmsNameTexte = _display displayCtrl 39150;
private _SonyNewSmsNumEdit = _display displayCtrl 39151;
private _SonyNewSmsSmsEdit = _display displayCtrl 39152;
private _SonyNewSmsBtnAnn = _display displayCtrl 39153;
private _SonyNewSmsBtnSend = _display displayCtrl 39154;

private _menu = uiNamespace getVariable "sonyp";
switch (_menu) do {
	case 0 : {
		_home ctrlShow false;
		_SonyAppel ctrlShow false;
		_SonyAppelBtn ctrlShow false;
		_SonyAppelEdit ctrlShow false;
		_SonyRegl ctrlShow false;
		_SonyReglON1 ctrlShow false;
		_SonyReglOFF1 ctrlShow false;
		_SonyReglON2 ctrlShow false;
		_SonyReglOFF2 ctrlShow false;
		_SonyReglON3 ctrlShow false;
		_SonyReglOFF3 ctrlShow false;
		_SonyReglBtnAvion ctrlShow false;
		_SonyReglBtnSilence ctrlShow false;
		_SonyReglBtnAnon ctrlShow false;
		_SonyReglBtnVolp1 ctrlShow false;
		_SonyReglBtnVolm1 ctrlShow false;
		_SonyNewContact ctrlShow false;
		_SonyNewContactAnn ctrlShow false;
		_SonyNewContactAdd ctrlShow false;
		_SonyNewContactName ctrlShow false;
		_SonyNewContactNum ctrlShow false;
		_SonyRecents ctrlShow false;
		_SonyRecentsLb ctrlShow false;
		_SonyRecentsVider ctrlShow false;
		_SonyRecentsApp ctrlShow false;
		_SonyRecentsSms ctrlShow false;
		_SonyAppelRecents ctrlShow false;
		_SonySms ctrlShow false;
		_SonySmsLb ctrlShow false;
		_SonySmsTexte ctrlShow false;
		_SonySmsBtnRep ctrlShow false;
		_SonySmsBtnSup ctrlShow false;
		_SonySmsBtnNew ctrlShow false;
		_SonyNewSms ctrlShow false;
		_SonyNewSmsNameTexte ctrlShow false;
		_SonyNewSmsNumEdit ctrlShow false;
		_SonyNewSmsSmsEdit ctrlShow false;
		_SonyNewSmsBtnAnn ctrlShow false;
		_SonyNewSmsBtnSend ctrlShow false;

		_SonyRadio ctrlShow false;
		_SonyRadioRaf ctrlShow false;
		_SonyRadioBtn1 ctrlShow false;
		_SonyRadioBtn2 ctrlShow false;
		_SonyRadioBtn3 ctrlShow false;
		_SonyRadioBtn4 ctrlShow false;
		_SonyRadioBtn5 ctrlShow false;
		_SonyRadioBtn6 ctrlShow false;
		_SonyRadioBtn7 ctrlShow false;
		_SonyRadioBtn8 ctrlShow false;
		_SonyRadioBtn9 ctrlShow false;
		_SonyRadioBtn10 ctrlShow false;
		_SonyRadioBtn11 ctrlShow false;
		_SonyRadioBtn12 ctrlShow false;
		_SonyRadioBtn13 ctrlShow false;
		_SonyRadioBtn14 ctrlShow false;
		_SonyRadioBtn15 ctrlShow false;
		_SonyRadioBtn16 ctrlShow false;
		_SonyRadioBtn17 ctrlShow false;
		_SonyRadioBtn21 ctrlShow false;
		_SonyRadioCo1 ctrlShow false;
		_SonyRadioCo2 ctrlShow false;
		_SonyRadioCo3 ctrlShow false;
		_SonyRadioCo4 ctrlShow false;
		_SonyRadioCo5 ctrlShow false;
		_SonyRadioCo6 ctrlShow false;
		_SonyRadioCo7 ctrlShow false;
		_SonyRadioCo8 ctrlShow false;
		_SonyRadioCo9 ctrlShow false;
		_SonyRadioCo10 ctrlShow false;
		_SonyRadioCo11 ctrlShow false;
		_SonyRadioCo12 ctrlShow false;
		_SonyRadioCo13 ctrlShow false;
		_SonyRadioCo14 ctrlShow false;
		_SonyRadioCo15 ctrlShow false;
		_SonyRadioCo16 ctrlShow false;
		_SonyRadioCo17 ctrlShow false;
		_SonyRadioCo21 ctrlShow false;
		_SonyRadioNb1 ctrlShow false;
		_SonyRadioNb2 ctrlShow false;
		_SonyRadioNb3 ctrlShow false;
		_SonyRadioNb4 ctrlShow false;
		_SonyRadioNb5 ctrlShow false;
		_SonyRadioNb6 ctrlShow false;
		_SonyRadioNb7 ctrlShow false;
		_SonyRadioNb8 ctrlShow false;
		_SonyRadioNb9 ctrlShow false;
		_SonyRadioNb10 ctrlShow false;
		_SonyRadioNb11 ctrlShow false;
		_SonyRadioNb12 ctrlShow false;
		_SonyRadioNb13 ctrlShow false;
		_SonyRadioNb14 ctrlShow false;
		_SonyRadioNb15 ctrlShow false;
		_SonyRadioNb16 ctrlShow false;
		_SonyRadioNb17 ctrlShow false;
		_SonyRadioNb21 ctrlShow false;
		_SonyContacts ctrlShow false;
		_SonyContactsAdd ctrlShow false;
		_SonyContactsTexte ctrlShow false;
		_SonyContactsList ctrlShow false;
		_SonyFiche ctrlShow false;
		_SonyFicheName ctrlShow false;
		_SonyFicheNum ctrlShow false;
		_SonyFicheBtnSms ctrlShow false;
		_SonyFicheBtnAppel ctrlShow false;
		_SonyFicheBtnDelete ctrlShow false;
		_SonyCentral ctrlShow false;
		_SonyCentralList ctrlShow false;
		_SonyCentralBtnApp ctrlShow false;
		_SonyCentralBtnRaf ctrlShow false;
		_SonyCentralBtnRac ctrlShow false;
		_SonyReglBtnFg ctrlShow false;
		_SonyReglBtnFm ctrlShow false;
		_SonyReglBtnFd ctrlShow false;
		_SonyReglBtnF2g ctrlShow false;
		_SonyReglBtnF2m ctrlShow false;
		_SonyReglBtnF2d ctrlShow false;

		if (ALF_Phone_inCall) then {
			_SonyMenu ctrlShow false;
			_SonyMenuBtnAppel ctrlShow false;
			_SonyMenuBtnSms ctrlShow false;
			_SonyMenuBtnContact ctrlShow false;
			_SonyMenuBtnRegl ctrlShow false;
			_SonyMenuBtnRadio ctrlShow false;
			_SonyMenuLock ctrlShow false;
			_SonyMenuBtnCentral ctrlShow false;
			_SonyRingCall ctrlShow false;
			_SonyRingCallBtnDecro ctrlShow false;
			_SonyRingCallBtnRefus ctrlShow false;
			_SonyInCall ctrlShow true;
			_SonyInCallHP ctrlShow true;
			_SonyInCallMute ctrlShow true;
			_SonyInCallBtnVolp ctrlShow true;
			_SonyInCallBtnVolm ctrlShow true;
			_SonyInCallBtnHP ctrlShow true;
			_SonyInCallBtnMute ctrlShow true;
			_SonyInCallName ctrlShow true;
			_SonyInCallNumber ctrlShow true;
			_SonyInCallTime ctrlShow true;
			_SonyInCallBtnRefuse ctrlShow true;
			_SonyDate ctrlShow false;
			private _hisName = "Inconnu";
			private _hisNumber = ALF_Phone_CallNumber;
			private _hisAnonyme = ALF_Phone_CallAnonyme;
			if (count life_contacts > 0) then {
				{
					if ((_x select 1) isEqualTo _hisNumber) exitWith {
						_hisName = _x select 0;
					};
				} forEach life_contacts;
			};
			if(_hisNumber isEqualTo "17") then {_hisName = "Gendarmerie"};
			if(_hisNumber isEqualTo "18") then {_hisName = "Pompier"};
			if(_hisAnonyme) then {_hisName = "Anonyme"; _hisNumber = "**********"};
			if(ALF_Central) then {_hisName = "Central"};
			_SonyInCallName ctrlSetStructuredText parseText format["<t align='left' style='0' shadow='0' color='#000000' font='HelveticaNeueLTStdLt' size='2'>%1</t>", _hisName];
			_SonyInCallNumber ctrlSetStructuredText parseText format["<t align='left' style='0' shadow='0' color='#000000' font='HelveticaNeueLTStdLt' size='1.2'>%1</t>", _hisNumber];
			_SonyInCallBtnVolp buttonSetAction "[""UP""] spawn ALF_fnc_SonyPSetVolume;";
			_SonyInCallBtnVolm buttonSetAction "[""DOWN""] spawn ALF_fnc_SonyPSetVolume;";
			_SonyInCallBtnRefuse buttonSetAction "[] call ALF_fnc_endCall;";
			if(iPhone_Mute) then {
				_SonyInCallMute ctrlShow true;
				_SonyInCallBtnMute buttonSetAction "[] spawn ALF_fnc_SonyPUnmute;";
			} else {
				_SonyInCallMute ctrlShow false;
				_SonyInCallBtnMute buttonSetAction "[] spawn ALF_fnc_SonyPMute;";
			};
			_SonyInCallBtnHP buttonSetAction "[] spawn ALF_fnc_SonyPSpeakers;";
			if(iPhone_Speackers) then {
				_SonyInCallHP ctrlShow true;
			} else {
				_SonyInCallHP ctrlShow false;
			};
		} else {
			if (ALF_Phone_Ring) then {
				_SonyMenu ctrlShow false;
				_SonyMenuBtnAppel ctrlShow false;
				_SonyMenuBtnSms ctrlShow false;
				_SonyMenuBtnContact ctrlShow false;
				_SonyMenuBtnRegl ctrlShow false;
				_SonyMenuBtnRadio ctrlShow false;
				_SonyMenuLock ctrlShow false;
				_SonyMenuBtnCentral ctrlShow false;
				_SonyInCall ctrlShow false;
				_SonyInCallHP ctrlShow false;
				_SonyInCallMute ctrlShow false;
				_SonyInCallBtnVolp ctrlShow false;
				_SonyInCallBtnVolm ctrlShow false;
				_SonyInCallBtnHP ctrlShow false;
				_SonyInCallBtnMute ctrlShow false;
				_SonyInCallTime ctrlShow false;
				_SonyInCallBtnRefuse ctrlShow false;
				_SonyRingCall ctrlShow true;
				_SonyRingCallBtnDecro ctrlShow true;
				_SonyRingCallBtnRefus ctrlShow true;
				_SonyInCallName ctrlShow true;
				_SonyInCallNumber ctrlShow true;
				_SonyDate ctrlShow false;
				private _hisName = "Inconnu";
				private _hisNumber = ALF_Phone_CallNumber;
				private _hisAnonyme = ALF_Phone_CallAnonyme;
				if (count life_contacts > 0) then {
					{
						if ((_x select 1) isEqualTo _hisNumber) exitWith {
							_hisName = _x select 0;
						};
					} forEach life_contacts;
				};
				if(_hisNumber isEqualTo "17") then {_hisName = "Gendarmerie"};
				if(_hisNumber isEqualTo "18") then {_hisName = "Pompier"};
				if(_hisAnonyme) then {_hisName = "Anonyme"; _hisNumber = "**********"};
				_SonyInCallName ctrlSetStructuredText parseText format["<t align='left' style='0' shadow='0' color='#000000' font='HelveticaNeueLTStdLt' size='2'>%1</t>", _hisName];
				_SonyInCallNumber ctrlSetStructuredText parseText format["<t align='left' style='0' shadow='0' color='#000000' font='HelveticaNeueLTStdLt' size='1.2'>%1</t>", _hisNumber];
				_SonyRingCallBtnDecro buttonSetAction "player setVariable [""call_info"",2,HC3_Life];";
				_SonyRingCallBtnRefus buttonSetAction "[] call ALF_fnc_resetCall;";
			} else {
				if(ALF_Phone_tryCall) then {
					_SonyMenu ctrlShow false;
					_SonyMenuBtnAppel ctrlShow false;
					_SonyMenuBtnSms ctrlShow false;
					_SonyMenuBtnContact ctrlShow false;
					_SonyMenuBtnRegl ctrlShow false;
					_SonyMenuBtnRadio ctrlShow false;
					_SonyMenuLock ctrlShow false;
					_SonyMenuBtnCentral ctrlShow false;
					_SonyInCall ctrlShow true;
					_SonyInCallHP ctrlShow false;
					_SonyInCallMute ctrlShow false;
					_SonyInCallBtnVolp ctrlShow true;
					_SonyInCallBtnVolm ctrlShow true;
					_SonyInCallBtnHP ctrlShow false;
					_SonyInCallBtnMute ctrlShow false;
					_SonyInCallName ctrlShow true;
					_SonyInCallNumber ctrlShow true;
					_SonyInCallTime ctrlShow false;
					_SonyInCallBtnRefuse ctrlShow true;
					_SonyRingCall ctrlShow false;
					_SonyRingCallBtnDecro ctrlShow false;
					_SonyRingCallBtnRefus ctrlShow false;
					_SonyDate ctrlShow false;
					private _hisName = "Inconnu";
					private _hisNumber = ALF_Phone_CallNumber;
					if (count life_contacts > 0) then {
						{
							if ((_x select 1) isEqualTo _hisNumber) exitWith {
								_hisName = _x select 0;
							};
						} forEach life_contacts;
					};
					if(_hisNumber isEqualTo "17") then {_hisName = "Gendarmerie"};
					if(_hisNumber isEqualTo "18") then {_hisName = "Pompier"};
					_SonyInCallName ctrlSetStructuredText parseText format["<t align='left' style='0' shadow='0' color='#000000' font='HelveticaNeueLTStdLt' size='2'>%1</t>", _hisName];
					_SonyInCallNumber ctrlSetStructuredText parseText format["<t align='left' style='0' shadow='0' color='#000000' font='HelveticaNeueLTStdLt' size='1.2'>%1</t>", _hisNumber];
					_SonyInCallBtnRefuse buttonSetAction "[] call ALF_fnc_resetCall;";
					_SonyInCallBtnVolp buttonSetAction "[""UP""] spawn ALF_fnc_SonyPSetVolume;";
					_SonyInCallBtnVolm buttonSetAction "[""DOWN""] spawn ALF_fnc_SonyPSetVolume;";
				} else {
					if(ALF_Forfait isEqualTo -1) then {
						_SonyMenu ctrlShow false;
						_SonyMenuLock ctrlShow true;
						_SonyMenuBtnAppel ctrlShow false;
						_SonyMenuBtnSms ctrlShow false;
						_SonyMenuBtnContact ctrlShow false;
						_SonyMenuBtnRegl ctrlShow false;
						_SonyMenuBtnRadio ctrlShow false;
						_SonyMenuBtnCentral ctrlShow false;
						_SonyInCall ctrlShow false;
						_SonyInCallHP ctrlShow false;
						_SonyInCallMute ctrlShow false;
						_SonyInCallBtnVolp ctrlShow false;
						_SonyInCallBtnVolm ctrlShow false;
						_SonyInCallBtnHP ctrlShow false;
						_SonyInCallBtnMute ctrlShow false;
						_SonyInCallName ctrlShow false;
						_SonyInCallNumber ctrlShow false;
						_SonyInCallTime ctrlShow false;
						_SonyInCallBtnRefuse ctrlShow false;
						_SonyRingCall ctrlShow false;
						_SonyRingCallBtnDecro ctrlShow false;
						_SonyRingCallBtnRefus ctrlShow false;
						_SonyDate ctrlShow false;
					} else {
						[] spawn ALF_fnc_setSonyPDate;
						_SonyMenu ctrlShow true;
						_SonyMenuBtnAppel ctrlShow true;
						_SonyMenuBtnSms ctrlShow true;
						_SonyMenuBtnContact ctrlShow true;
						_SonyMenuBtnRegl ctrlShow true;
						_SonyMenuBtnRadio ctrlShow true;

						_SonyMenuBtnCentral ctrlShow true;
						_SonyMenuLock ctrlShow false;
						_SonyInCall ctrlShow false;
						_SonyInCallHP ctrlShow false;
						_SonyInCallMute ctrlShow false;
						_SonyInCallBtnVolp ctrlShow false;
						_SonyInCallBtnVolm ctrlShow false;
						_SonyInCallBtnHP ctrlShow false;
						_SonyInCallBtnMute ctrlShow false;
						_SonyInCallName ctrlShow false;
						_SonyInCallNumber ctrlShow false;
						_SonyInCallTime ctrlShow false;
						_SonyInCallBtnRefuse ctrlShow false;
						_SonyRingCall ctrlShow false;
						_SonyRingCallBtnDecro ctrlShow false;
						_SonyRingCallBtnRefus ctrlShow false;
						_SonyDate ctrlShow true;
						_SonyMenuBtnAppel buttonSetAction "uiNamespace setVariable ['sonyp',1]; [] call ALF_fnc_menuSonyP;";
						_SonyMenuBtnSms buttonSetAction "uiNamespace setVariable ['sonyp',2]; [] call ALF_fnc_menuSonyP;";
						_SonyMenuBtnContact buttonSetAction "uiNamespace setVariable ['sonyp',3]; [] call ALF_fnc_menuSonyP;";
						_SonyMenuBtnRegl buttonSetAction "uiNamespace setVariable ['sonyp',4]; [] call ALF_fnc_menuSonyP;";
						_SonyMenuBtnRadio buttonSetAction "uiNamespace setVariable ['sonyp',5]; [] call ALF_fnc_menuSonyP;";
						_SonyMenuBtnCentral buttonSetAction "uiNamespace setVariable ['sonyp',8]; [] call ALF_fnc_menuSonyP;";
					};
				};
			};
		};
	};
	case 1 : {
		_SonyMenu ctrlShow false;
		_SonyMenuLock ctrlShow false;
		_SonyMenuBtnAppel ctrlShow false;
		_SonyMenuBtnSms ctrlShow false;
		_SonyMenuBtnContact ctrlShow false;
		_SonyMenuBtnRegl ctrlShow false;
		_SonyMenuBtnRadio ctrlShow false;
		_SonyRingCall ctrlShow false;
		_SonyRingCallBtnDecro ctrlShow false;
		_SonyRingCallBtnRefus ctrlShow false;
		_SonyInCall ctrlShow false;
		_SonyInCallHP ctrlShow false;
		_SonyInCallMute ctrlShow false;
		_SonyInCallBtnVolp ctrlShow false;
		_SonyInCallBtnVolm ctrlShow false;
		_SonyInCallBtnHP ctrlShow false;
		_SonyInCallBtnMute ctrlShow false;
		_SonyInCallName ctrlShow false;
		_SonyInCallNumber ctrlShow false;
		_SonyInCallTime ctrlShow false;
		_SonyInCallBtnRefuse ctrlShow false;
		_SonyRegl ctrlShow false;
		_SonyReglON1 ctrlShow false;
		_SonyReglOFF1 ctrlShow false;
		_SonyReglON2 ctrlShow false;
		_SonyReglOFF2 ctrlShow false;
		_SonyReglON3 ctrlShow false;
		_SonyReglOFF3 ctrlShow false;
		_SonyReglBtnAvion ctrlShow false;
		_SonyReglBtnSilence ctrlShow false;
		_SonyReglBtnAnon ctrlShow false;
		_SonyDate ctrlShow false;
		_SonyRadio ctrlShow false;
		_SonyRadioRaf ctrlShow false;
		_SonyRadioBtn1 ctrlShow false;
		_SonyRadioBtn2 ctrlShow false;
		_SonyRadioBtn3 ctrlShow false;
		_SonyRadioBtn4 ctrlShow false;
		_SonyRadioBtn5 ctrlShow false;
		_SonyRadioBtn6 ctrlShow false;
		_SonyRadioBtn7 ctrlShow false;
		_SonyRadioBtn8 ctrlShow false;
		_SonyRadioBtn9 ctrlShow false;
		_SonyRadioBtn10 ctrlShow false;
		_SonyRadioBtn11 ctrlShow false;
		_SonyRadioBtn12 ctrlShow false;
		_SonyRadioBtn13 ctrlShow false;
		_SonyRadioBtn14 ctrlShow false;
		_SonyRadioBtn15 ctrlShow false;
		_SonyRadioBtn16 ctrlShow false;
		_SonyRadioBtn17 ctrlShow false;
		_SonyRadioBtn21 ctrlShow false;
		_SonyRadioCo1 ctrlShow false;
		_SonyRadioCo2 ctrlShow false;
		_SonyRadioCo3 ctrlShow false;
		_SonyRadioCo4 ctrlShow false;
		_SonyRadioCo5 ctrlShow false;
		_SonyRadioCo6 ctrlShow false;
		_SonyRadioCo7 ctrlShow false;
		_SonyRadioCo8 ctrlShow false;
		_SonyRadioCo9 ctrlShow false;
		_SonyRadioCo10 ctrlShow false;
		_SonyRadioCo11 ctrlShow false;
		_SonyRadioCo12 ctrlShow false;
		_SonyRadioCo13 ctrlShow false;
		_SonyRadioCo14 ctrlShow false;
		_SonyRadioCo15 ctrlShow false;
		_SonyRadioCo16 ctrlShow false;
		_SonyRadioCo17 ctrlShow false;
		_SonyRadioCo21 ctrlShow false;
		_SonyRadioNb1 ctrlShow false;
		_SonyRadioNb2 ctrlShow false;
		_SonyRadioNb3 ctrlShow false;
		_SonyRadioNb4 ctrlShow false;
		_SonyRadioNb5 ctrlShow false;
		_SonyRadioNb6 ctrlShow false;
		_SonyRadioNb7 ctrlShow false;
		_SonyRadioNb8 ctrlShow false;
		_SonyRadioNb9 ctrlShow false;
		_SonyRadioNb10 ctrlShow false;
		_SonyRadioNb11 ctrlShow false;
		_SonyRadioNb12 ctrlShow false;
		_SonyRadioNb13 ctrlShow false;
		_SonyRadioNb14 ctrlShow false;
		_SonyRadioNb15 ctrlShow false;
		_SonyRadioNb16 ctrlShow false;
		_SonyRadioNb17 ctrlShow false;
		_SonyRadioNb21 ctrlShow false;
		_SonyMenuBtnCentral ctrlShow false;
		_SonyReglBtnVolp1 ctrlShow false;
		_SonyReglBtnVolm1 ctrlShow false;
		_SonyContacts ctrlShow false;
		_SonyContactsAdd ctrlShow false;
		_SonyContactsTexte ctrlShow false;
		_SonyContactsList ctrlShow false;
		_SonyFiche ctrlShow false;
		_SonyFicheName ctrlShow false;
		_SonyFicheNum ctrlShow false;
		_SonyFicheBtnSms ctrlShow false;
		_SonyFicheBtnAppel ctrlShow false;
		_SonyFicheBtnDelete ctrlShow false;
		_SonyCentral ctrlShow false;
		_SonyCentralList ctrlShow false;
		_SonyCentralBtnApp ctrlShow false;
		_SonyCentralBtnRaf ctrlShow false;
		_SonyCentralBtnRac ctrlShow false;
		_SonyNewContact ctrlShow false;
		_SonyNewContactAnn ctrlShow false;
		_SonyNewContactAdd ctrlShow false;
		_SonyNewContactName ctrlShow false;
		_SonyNewContactNum ctrlShow false;
		_SonyRecents ctrlShow false;
		_SonyRecentsLb ctrlShow false;
		_SonyRecentsVider ctrlShow false;
		_SonyRecentsApp ctrlShow false;
		_SonyRecentsSms ctrlShow false;
		_SonyReglBtnFg ctrlShow false;
		_SonyReglBtnFm ctrlShow false;
		_SonyReglBtnFd ctrlShow false;
		_SonyReglBtnF2g ctrlShow false;
		_SonyReglBtnF2m ctrlShow false;
		_SonyReglBtnF2d ctrlShow false;
		_SonySms ctrlShow false;
		_SonySmsLb ctrlShow false;
		_SonySmsTexte ctrlShow false;
		_SonySmsBtnRep ctrlShow false;
		_SonySmsBtnSup ctrlShow false;
		_SonySmsBtnNew ctrlShow false;
		_SonyNewSms ctrlShow false;
		_SonyNewSmsNameTexte ctrlShow false;
		_SonyNewSmsNumEdit ctrlShow false;
		_SonyNewSmsSmsEdit ctrlShow false;
		_SonyNewSmsBtnAnn ctrlShow false;
		_SonyNewSmsBtnSend ctrlShow false;
		_SonyAppel ctrlShow true;
		_SonyAppelBtn ctrlShow true;
		_SonyAppelEdit ctrlShow true;
		_SonyAppelRecents ctrlShow true;
		_home ctrlShow true;
		_SonyAppelBtn buttonSetAction "[] spawn ALF_fnc_SonyPCallCustom;";
		_SonyAppelRecents buttonSetAction "uiNamespace setVariable ['sonyp',11]; [] call ALF_fnc_menuSonyP;";
	};

	case 2 : {
		_SonyMenu ctrlShow false;
		_SonyMenuLock ctrlShow false;
		_SonyMenuBtnAppel ctrlShow false;
		_SonyMenuBtnSms ctrlShow false;
		_SonyMenuBtnContact ctrlShow false;
		_SonyMenuBtnRegl ctrlShow false;
		_SonyMenuBtnRadio ctrlShow false;
		_SonyRingCall ctrlShow false;
		_SonyRingCallBtnDecro ctrlShow false;
		_SonyRingCallBtnRefus ctrlShow false;
		_SonyInCall ctrlShow false;
		_SonyInCallHP ctrlShow false;
		_SonyInCallMute ctrlShow false;
		_SonyInCallBtnVolp ctrlShow false;
		_SonyInCallBtnVolm ctrlShow false;
		_SonyInCallBtnHP ctrlShow false;
		_SonyInCallBtnMute ctrlShow false;
		_SonyInCallName ctrlShow false;
		_SonyInCallNumber ctrlShow false;
		_SonyInCallTime ctrlShow false;
		_SonyInCallBtnRefuse ctrlShow false;
		_SonyRegl ctrlShow false;
		_SonyReglON1 ctrlShow false;
		_SonyReglOFF1 ctrlShow false;
		_SonyReglON2 ctrlShow false;
		_SonyReglOFF2 ctrlShow false;
		_SonyReglON3 ctrlShow false;
		_SonyReglOFF3 ctrlShow false;
		_SonyReglBtnAvion ctrlShow false;
		_SonyReglBtnSilence ctrlShow false;
		_SonyReglBtnAnon ctrlShow false;
		_SonyDate ctrlShow false;
		_SonyRadio ctrlShow false;
		_SonyRadioRaf ctrlShow false;
		_SonyRadioBtn1 ctrlShow false;
		_SonyRadioBtn2 ctrlShow false;
		_SonyRadioBtn3 ctrlShow false;
		_SonyRadioBtn4 ctrlShow false;
		_SonyRadioBtn5 ctrlShow false;
		_SonyRadioBtn6 ctrlShow false;
		_SonyRadioBtn7 ctrlShow false;
		_SonyRadioBtn8 ctrlShow false;
		_SonyRadioBtn9 ctrlShow false;
		_SonyRadioBtn10 ctrlShow false;
		_SonyRadioBtn11 ctrlShow false;
		_SonyRadioBtn12 ctrlShow false;
		_SonyRadioBtn13 ctrlShow false;
		_SonyRadioBtn14 ctrlShow false;
		_SonyRadioBtn15 ctrlShow false;
		_SonyRadioBtn16 ctrlShow false;
		_SonyRadioBtn17 ctrlShow false;
		_SonyRadioBtn21 ctrlShow false;
		_SonyRadioCo1 ctrlShow false;
		_SonyRadioCo2 ctrlShow false;
		_SonyRadioCo3 ctrlShow false;
		_SonyRadioCo4 ctrlShow false;
		_SonyRadioCo5 ctrlShow false;
		_SonyRadioCo6 ctrlShow false;
		_SonyRadioCo7 ctrlShow false;
		_SonyRadioCo8 ctrlShow false;
		_SonyRadioCo9 ctrlShow false;
		_SonyRadioCo10 ctrlShow false;
		_SonyRadioCo11 ctrlShow false;
		_SonyRadioCo12 ctrlShow false;
		_SonyRadioCo13 ctrlShow false;
		_SonyRadioCo14 ctrlShow false;
		_SonyRadioCo15 ctrlShow false;
		_SonyRadioCo16 ctrlShow false;
		_SonyRadioCo17 ctrlShow false;
		_SonyRadioCo21 ctrlShow false;
		_SonyRadioNb1 ctrlShow false;
		_SonyRadioNb2 ctrlShow false;
		_SonyRadioNb3 ctrlShow false;
		_SonyRadioNb4 ctrlShow false;
		_SonyRadioNb5 ctrlShow false;
		_SonyRadioNb6 ctrlShow false;
		_SonyRadioNb7 ctrlShow false;
		_SonyRadioNb8 ctrlShow false;
		_SonyRadioNb9 ctrlShow false;
		_SonyRadioNb10 ctrlShow false;
		_SonyRadioNb11 ctrlShow false;
		_SonyRadioNb12 ctrlShow false;
		_SonyRadioNb13 ctrlShow false;
		_SonyRadioNb14 ctrlShow false;
		_SonyRadioNb15 ctrlShow false;
		_SonyRadioNb16 ctrlShow false;
		_SonyRadioNb17 ctrlShow false;
		_SonyRadioNb21 ctrlShow false;
		_SonyMenuBtnCentral ctrlShow false;
		_SonyReglBtnVolp1 ctrlShow false;
		_SonyReglBtnVolm1 ctrlShow false;
		_SonyContacts ctrlShow false;
		_SonyContactsAdd ctrlShow false;
		_SonyContactsTexte ctrlShow false;
		_SonyContactsList ctrlShow false;
		_SonyFiche ctrlShow false;
		_SonyFicheName ctrlShow false;
		_SonyFicheNum ctrlShow false;
		_SonyFicheBtnSms ctrlShow false;
		_SonyFicheBtnAppel ctrlShow false;
		_SonyFicheBtnDelete ctrlShow false;
		_SonyCentral ctrlShow false;
		_SonyCentralList ctrlShow false;
		_SonyCentralBtnApp ctrlShow false;
		_SonyCentralBtnRaf ctrlShow false;
		_SonyCentralBtnRac ctrlShow false;
		_SonyNewContact ctrlShow false;
		_SonyNewContactAnn ctrlShow false;
		_SonyNewContactAdd ctrlShow false;
		_SonyNewContactName ctrlShow false;
		_SonyNewContactNum ctrlShow false;
		_SonyRecents ctrlShow false;
		_SonyRecentsLb ctrlShow false;
		_SonyRecentsVider ctrlShow false;
		_SonyRecentsApp ctrlShow false;
		_SonyRecentsSms ctrlShow false;
		_SonyReglBtnFg ctrlShow false;
		_SonyReglBtnFm ctrlShow false;
		_SonyReglBtnFd ctrlShow false;
		_SonyReglBtnF2g ctrlShow false;
		_SonyReglBtnF2m ctrlShow false;
		_SonyReglBtnF2d ctrlShow false;
		_SonySms ctrlShow true;
		_SonySmsLb ctrlShow true;
		_SonySmsTexte ctrlShow true;
		_SonySmsBtnRep ctrlShow false;
		_SonySmsBtnSup ctrlShow false;
		_SonySmsBtnNew ctrlShow true;
		_SonyNewSms ctrlShow false;
		_SonyNewSmsNameTexte ctrlShow false;
		_SonyNewSmsNumEdit ctrlShow false;
		_SonyNewSmsSmsEdit ctrlShow false;
		_SonyNewSmsBtnAnn ctrlShow false;
		_SonyNewSmsBtnSend ctrlShow false;
		_SonyAppel ctrlShow false;
		_SonyAppelBtn ctrlShow false;
		_SonyAppelEdit ctrlShow false;
		_SonyAppelRecents ctrlShow false;
		_home ctrlShow true;
		[ALF_Phone_Number,player] remoteExecCall ["HC_fnc_loadSmsSonyP",HC3_Life];
		ALF_Phone_SMS = false;
		_SonySmsBtnNew buttonSetAction "uiNamespace setVariable ['sonyp',6]; [] call ALF_fnc_menuSonyP;";
	};

	case 3 : {
		_SonyMenu ctrlShow false;
		_SonyMenuLock ctrlShow false;
		_SonyMenuBtnAppel ctrlShow false;
		_SonyMenuBtnSms ctrlShow false;
		_SonyMenuBtnContact ctrlShow false;
		_SonyMenuBtnRegl ctrlShow false;
		_SonyMenuBtnRadio ctrlShow false;
		_SonyRingCall ctrlShow false;
		_SonyRingCallBtnDecro ctrlShow false;
		_SonyRingCallBtnRefus ctrlShow false;
		_SonyInCall ctrlShow false;
		_SonyInCallHP ctrlShow false;
		_SonyInCallMute ctrlShow false;
		_SonyInCallBtnVolp ctrlShow false;
		_SonyInCallBtnVolm ctrlShow false;
		_SonyInCallBtnHP ctrlShow false;
		_SonyInCallBtnMute ctrlShow false;
		_SonyInCallName ctrlShow false;
		_SonyInCallNumber ctrlShow false;
		_SonyInCallTime ctrlShow false;
		_SonyInCallBtnRefuse ctrlShow false;
		_SonyRegl ctrlShow false;
		_SonyReglON1 ctrlShow false;
		_SonyReglOFF1 ctrlShow false;
		_SonyReglON2 ctrlShow false;
		_SonyReglOFF2 ctrlShow false;
		_SonyReglON3 ctrlShow false;
		_SonyReglOFF3 ctrlShow false;
		_SonyReglBtnAvion ctrlShow false;
		_SonyReglBtnSilence ctrlShow false;
		_SonyReglBtnAnon ctrlShow false;
		_SonyDate ctrlShow false;
		_SonyRadio ctrlShow false;
		_SonyRadioRaf ctrlShow false;
		_SonyRadioBtn1 ctrlShow false;
		_SonyRadioBtn2 ctrlShow false;
		_SonyRadioBtn3 ctrlShow false;
		_SonyRadioBtn4 ctrlShow false;
		_SonyRadioBtn5 ctrlShow false;
		_SonyRadioBtn6 ctrlShow false;
		_SonyRadioBtn7 ctrlShow false;
		_SonyRadioBtn8 ctrlShow false;
		_SonyRadioBtn9 ctrlShow false;
		_SonyRadioBtn10 ctrlShow false;
		_SonyRadioBtn11 ctrlShow false;
		_SonyRadioBtn12 ctrlShow false;
		_SonyRadioBtn13 ctrlShow false;
		_SonyRadioBtn14 ctrlShow false;
		_SonyRadioBtn15 ctrlShow false;
		_SonyRadioBtn16 ctrlShow false;
		_SonyRadioBtn17 ctrlShow false;
		_SonyRadioBtn21 ctrlShow false;
		_SonyRadioCo1 ctrlShow false;
		_SonyRadioCo2 ctrlShow false;
		_SonyRadioCo3 ctrlShow false;
		_SonyRadioCo4 ctrlShow false;
		_SonyRadioCo5 ctrlShow false;
		_SonyRadioCo6 ctrlShow false;
		_SonyRadioCo7 ctrlShow false;
		_SonyRadioCo8 ctrlShow false;
		_SonyRadioCo9 ctrlShow false;
		_SonyRadioCo10 ctrlShow false;
		_SonyRadioCo11 ctrlShow false;
		_SonyRadioCo12 ctrlShow false;
		_SonyRadioCo13 ctrlShow false;
		_SonyRadioCo14 ctrlShow false;
		_SonyRadioCo15 ctrlShow false;
		_SonyRadioCo16 ctrlShow false;
		_SonyRadioCo17 ctrlShow false;
		_SonyRadioCo21 ctrlShow false;
		_SonyRadioNb1 ctrlShow false;
		_SonyRadioNb2 ctrlShow false;
		_SonyRadioNb3 ctrlShow false;
		_SonyRadioNb4 ctrlShow false;
		_SonyRadioNb5 ctrlShow false;
		_SonyRadioNb6 ctrlShow false;
		_SonyRadioNb7 ctrlShow false;
		_SonyRadioNb8 ctrlShow false;
		_SonyRadioNb9 ctrlShow false;
		_SonyRadioNb10 ctrlShow false;
		_SonyRadioNb11 ctrlShow false;
		_SonyRadioNb12 ctrlShow false;
		_SonyRadioNb13 ctrlShow false;
		_SonyRadioNb14 ctrlShow false;
		_SonyRadioNb15 ctrlShow false;
		_SonyRadioNb16 ctrlShow false;
		_SonyRadioNb17 ctrlShow false;
		_SonyRadioNb21 ctrlShow false;
		_SonyMenuBtnCentral ctrlShow false;
		_SonyReglBtnVolp1 ctrlShow false;
		_SonyReglBtnVolm1 ctrlShow false;
		_SonyContacts ctrlShow true;
		_SonyContactsAdd ctrlShow true;
		_SonyContactsTexte ctrlShow true;
		_SonyContactsList ctrlShow true;
		_SonyFiche ctrlShow false;
		_SonyFicheName ctrlShow false;
		_SonyFicheNum ctrlShow false;
		_SonyFicheBtnSms ctrlShow false;
		_SonyFicheBtnAppel ctrlShow false;
		_SonyFicheBtnDelete ctrlShow false;
		_SonyAppel ctrlShow false;
		_SonyAppelBtn ctrlShow false;
		_SonyAppelEdit ctrlShow false;
		_SonyCentral ctrlShow false;
		_SonyCentralList ctrlShow false;
		_SonyCentralBtnApp ctrlShow false;
		_SonyCentralBtnRaf ctrlShow false;
		_SonyCentralBtnRac ctrlShow false;
		_SonyNewContact ctrlShow false;
		_SonyNewContactAnn ctrlShow false;
		_SonyNewContactAdd ctrlShow false;
		_SonyNewContactName ctrlShow false;
		_SonyNewContactNum ctrlShow false;
		_SonyRecents ctrlShow false;
		_SonyRecentsLb ctrlShow false;
		_SonyRecentsVider ctrlShow false;
		_SonyRecentsApp ctrlShow false;
		_SonyRecentsSms ctrlShow false;
		_SonyAppelRecents ctrlShow false;
		_SonyReglBtnFg ctrlShow false;
		_SonyReglBtnFm ctrlShow false;
		_SonyReglBtnFd ctrlShow false;
		_SonyReglBtnF2g ctrlShow false;
		_SonyReglBtnF2m ctrlShow false;
		_SonyReglBtnF2d ctrlShow false;
		_SonySms ctrlShow false;
		_SonySmsLb ctrlShow false;
		_SonySmsTexte ctrlShow false;
		_SonySmsBtnRep ctrlShow false;
		_SonySmsBtnSup ctrlShow false;
		_SonySmsBtnNew ctrlShow false;
		_SonyNewSms ctrlShow false;
		_SonyNewSmsNameTexte ctrlShow false;
		_SonyNewSmsNumEdit ctrlShow false;
		_SonyNewSmsSmsEdit ctrlShow false;
		_SonyNewSmsBtnAnn ctrlShow false;
		_SonyNewSmsBtnSend ctrlShow false;
		_home ctrlShow true;

		lbClear _SonyContactsList;
		if (count life_contacts > 0) then {
			{
				private _name = _x select 0;
				_SonyContactsList lbAdd format["%1",_name];
				_SonyContactsList lbSetData [(lbSize _SonyContactsList)-1,str(_x)];
				_SonyContactsList lbSetValue [(lbSize _SonyContactsList)-1,_forEachIndex];
			} forEach life_contacts;
			lbSort _SonyContactsList;
		};
		private _myName = name player;
		private _myNumber = ALF_Phone_Number;
		_SonyContactsTexte ctrlSetStructuredText parseText format["<t align='left' style='0' shadow='0' color='#000000' font='HelveticaNeueLTStdLt' size='1.2'>%1 - %2</t>",_myName,_myNumber];
		_SonyContactsList ctrlSetEventHandler ["LBDblClick", "uiNamespace setVariable ['sonyp',9]; [] call ALF_fnc_menuSonyP;"];
		_SonyContactsAdd buttonSetAction "uiNamespace setVariable ['sonyp',10]; [] call ALF_fnc_menuSonyP;";
	};

	case 4 : {
		_SonyDate ctrlShow false;
		_SonyAppel ctrlShow false;
		_SonyAppelBtn ctrlShow false;
		_SonyAppelEdit ctrlShow false;
		_SonyMenu ctrlShow false;
		_SonyMenuLock ctrlShow false;
		_SonyMenuBtnAppel ctrlShow false;
		_SonyMenuBtnSms ctrlShow false;
		_SonyMenuBtnContact ctrlShow false;
		_SonyMenuBtnRegl ctrlShow false;
		_SonyMenuBtnRadio ctrlShow false;
		_SonyRingCall ctrlShow false;
		_SonyRingCallBtnDecro ctrlShow false;
		_SonyRingCallBtnRefus ctrlShow false;
		_SonyInCall ctrlShow false;
		_SonyInCallHP ctrlShow false;
		_SonyInCallMute ctrlShow false;
		_SonyInCallBtnVolp ctrlShow false;
		_SonyInCallBtnVolm ctrlShow false;
		_SonyInCallBtnHP ctrlShow false;
		_SonyInCallBtnMute ctrlShow false;
		_SonyInCallName ctrlShow false;
		_SonyInCallNumber ctrlShow false;
		_SonyInCallTime ctrlShow false;
		_SonyInCallBtnRefuse ctrlShow false;
		_SonyRadio ctrlShow false;
		_SonyRadioRaf ctrlShow false;
		_SonyRadioBtn1 ctrlShow false;
		_SonyRadioBtn2 ctrlShow false;
		_SonyRadioBtn3 ctrlShow false;
		_SonyRadioBtn4 ctrlShow false;
		_SonyRadioBtn5 ctrlShow false;
		_SonyRadioBtn6 ctrlShow false;
		_SonyRadioBtn7 ctrlShow false;
		_SonyRadioBtn8 ctrlShow false;
		_SonyRadioBtn9 ctrlShow false;
		_SonyRadioBtn10 ctrlShow false;
		_SonyRadioBtn11 ctrlShow false;
		_SonyRadioBtn12 ctrlShow false;
		_SonyRadioBtn13 ctrlShow false;
		_SonyRadioBtn14 ctrlShow false;
		_SonyRadioBtn15 ctrlShow false;
		_SonyRadioBtn16 ctrlShow false;
		_SonyRadioBtn17 ctrlShow false;
		_SonyRadioBtn21 ctrlShow false;
		_SonyRadioCo1 ctrlShow false;
		_SonyRadioCo2 ctrlShow false;
		_SonyRadioCo3 ctrlShow false;
		_SonyRadioCo4 ctrlShow false;
		_SonyRadioCo5 ctrlShow false;
		_SonyRadioCo6 ctrlShow false;
		_SonyRadioCo7 ctrlShow false;
		_SonyRadioCo8 ctrlShow false;
		_SonyRadioCo9 ctrlShow false;
		_SonyRadioCo10 ctrlShow false;
		_SonyRadioCo11 ctrlShow false;
		_SonyRadioCo12 ctrlShow false;
		_SonyRadioCo13 ctrlShow false;
		_SonyRadioCo14 ctrlShow false;
		_SonyRadioCo15 ctrlShow false;
		_SonyRadioCo16 ctrlShow false;
		_SonyRadioCo17 ctrlShow false;
		_SonyRadioCo21 ctrlShow false;
		_SonyRadioNb1 ctrlShow false;
		_SonyRadioNb2 ctrlShow false;
		_SonyRadioNb3 ctrlShow false;
		_SonyRadioNb4 ctrlShow false;
		_SonyRadioNb5 ctrlShow false;
		_SonyRadioNb6 ctrlShow false;
		_SonyRadioNb7 ctrlShow false;
		_SonyRadioNb8 ctrlShow false;
		_SonyRadioNb9 ctrlShow false;
		_SonyRadioNb10 ctrlShow false;
		_SonyRadioNb11 ctrlShow false;
		_SonyRadioNb12 ctrlShow false;
		_SonyRadioNb13 ctrlShow false;
		_SonyRadioNb14 ctrlShow false;
		_SonyRadioNb15 ctrlShow false;
		_SonyRadioNb16 ctrlShow false;
		_SonyRadioNb17 ctrlShow false;
		_SonyRadioNb21 ctrlShow false;
		_SonyMenuBtnCentral ctrlShow false;
		_SonyContacts ctrlShow false;
		_SonyContactsAdd ctrlShow false;
		_SonyContactsTexte ctrlShow false;
		_SonyContactsList ctrlShow false;
		_SonyFiche ctrlShow false;
		_SonyFicheName ctrlShow false;
		_SonyFicheNum ctrlShow false;
		_SonyFicheBtnSms ctrlShow false;
		_SonyFicheBtnAppel ctrlShow false;
		_SonyFicheBtnDelete ctrlShow false;
		_SonyCentral ctrlShow false;
		_SonyCentralList ctrlShow false;
		_SonyCentralBtnApp ctrlShow false;
		_SonyCentralBtnRaf ctrlShow false;
		_SonyCentralBtnRac ctrlShow false;
		_SonyNewContact ctrlShow false;
		_SonyNewContactAnn ctrlShow false;
		_SonyNewContactAdd ctrlShow false;
		_SonyNewContactName ctrlShow false;
		_SonyNewContactNum ctrlShow false;
		_SonyRecents ctrlShow false;
		_SonyRecentsLb ctrlShow false;
		_SonyRecentsVider ctrlShow false;
		_SonyRecentsApp ctrlShow false;
		_SonyRecentsSms ctrlShow false;
		_SonyAppelRecents ctrlShow false;
		_SonySms ctrlShow false;
		_SonySmsLb ctrlShow false;
		_SonySmsTexte ctrlShow false;
		_SonySmsBtnRep ctrlShow false;
		_SonySmsBtnSup ctrlShow false;
		_SonySmsBtnNew ctrlShow false;
		_SonyNewSms ctrlShow false;
		_SonyNewSmsNameTexte ctrlShow false;
		_SonyNewSmsNumEdit ctrlShow false;
		_SonyNewSmsSmsEdit ctrlShow false;
		_SonyNewSmsBtnAnn ctrlShow false;
		_SonyNewSmsBtnSend ctrlShow false;
		_SonyReglBtnVolp1 ctrlShow true;
		_SonyReglBtnVolm1 ctrlShow true;
		_SonyReglBtnFg ctrlShow true;
		_SonyReglBtnFm ctrlShow true;
		_SonyReglBtnFd ctrlShow true;
		_SonyReglBtnF2g ctrlShow true;
		_SonyReglBtnF2m ctrlShow true;
		_SonyReglBtnF2d ctrlShow true;
		_SonyRegl ctrlShow true;
		_home ctrlShow true;
		if (ALF_Phone_Anonyme) then {_SonyReglON3 ctrlShow true; _SonyReglOFF3 ctrlShow false;} else {_SonyReglON3 ctrlShow false; _SonyReglOFF3 ctrlShow true;};
		if (ALF_Phone_Avion) then {_SonyReglON1 ctrlShow true; _SonyReglOFF1 ctrlShow false;} else {_SonyReglON1 ctrlShow false; _SonyReglOFF1 ctrlShow true;};
		if (ALF_Phone_Mute) then {_SonyReglON2 ctrlShow true; _SonyReglOFF2 ctrlShow false;} else {_SonyReglON2 ctrlShow false; _SonyReglOFF2 ctrlShow true;};
		_SonyReglBtnAvion ctrlShow true;
		_SonyReglBtnAvion buttonSetAction "if(ALF_Phone_Avion)then{ALF_Phone_Avion=false;}else{ALF_Phone_Avion=true;}; [] call ALF_fnc_menuSonyP;";
		_SonyReglBtnSilence ctrlShow true;
		_SonyReglBtnSilence buttonSetAction "if(ALF_Phone_Mute)then{ALF_Phone_Mute=false;}else{ALF_Phone_Mute=true;}; [] call ALF_fnc_menuSonyP;";
		_SonyReglBtnAnon ctrlShow true;
		_SonyReglBtnAnon buttonSetAction "if(ALF_Phone_Anonyme)then{ALF_Phone_Anonyme=false;}else{ALF_Phone_Anonyme=true;}; [] call ALF_fnc_menuSonyP;";
		_SonyReglBtnVolp1 buttonSetAction "[""UP""] spawn ALF_fnc_SonyPRadioSetVolume;";
		_SonyReglBtnVolm1 buttonSetAction "[""DOWN""] spawn ALF_fnc_SonyPRadioSetVolume;";
		_SonyReglBtnFg buttonSetAction "[1,""G""] spawn ALF_fnc_SonyPSetStereo;";
		_SonyReglBtnFm buttonSetAction "[1,""M""] spawn ALF_fnc_SonyPSetStereo;";
		_SonyReglBtnFs buttonSetAction "[1,""S""] spawn ALF_fnc_SonyPSetStereo;";
		_SonyReglBtnF2g buttonSetAction "[2,""G""] spawn ALF_fnc_SonyPSetStereo;";
		_SonyReglBtnF2m buttonSetAction "[2,""M""] spawn ALF_fnc_SonyPSetStereo;";
		_SonyReglBtnF2d buttonSetAction "[2,""D""] spawn ALF_fnc_SonyPSetStereo;";
	};
	case 5 : {
		if (!life_pompier_service) exitWith {};
		_SonyMenu ctrlShow false;
		_SonyMenuLock ctrlShow false;
		_SonyMenuBtnAppel ctrlShow false;
		_SonyMenuBtnSms ctrlShow false;
		_SonyMenuBtnContact ctrlShow false;
		_SonyMenuBtnRegl ctrlShow false;
		_SonyMenuBtnRadio ctrlShow false;
		_SonyRingCall ctrlShow false;
		_SonyRingCallBtnDecro ctrlShow false;
		_SonyRingCallBtnRefus ctrlShow false;
		_SonyInCall ctrlShow false;
		_SonyInCallHP ctrlShow false;
		_SonyInCallMute ctrlShow false;
		_SonyInCallBtnVolp ctrlShow false;
		_SonyInCallBtnVolm ctrlShow false;
		_SonyInCallBtnHP ctrlShow false;
		_SonyInCallBtnMute ctrlShow false;
		_SonyInCallName ctrlShow false;
		_SonyInCallNumber ctrlShow false;
		_SonyInCallTime ctrlShow false;
		_SonyInCallBtnRefuse ctrlShow false;
		_SonyRegl ctrlShow false;
		_SonyReglON1 ctrlShow false;
		_SonyReglOFF1 ctrlShow false;
		_SonyReglON2 ctrlShow false;
		_SonyReglOFF2 ctrlShow false;
		_SonyReglON3 ctrlShow false;
		_SonyReglOFF3 ctrlShow false;
		_SonyReglBtnAvion ctrlShow false;
		_SonyReglBtnSilence ctrlShow false;
		_SonyReglBtnAnon ctrlShow false;
		_SonyDate ctrlShow false;
		_SonyAppel ctrlShow false;
		_SonyAppelBtn ctrlShow false;
		_SonyAppelEdit ctrlShow false;
		_SonyMenuBtnCentral ctrlShow false;
		_SonyReglBtnVolp1 ctrlShow false;
		_SonyReglBtnVolm1 ctrlShow false;
		_SonyContacts ctrlShow false;
		_SonyContactsAdd ctrlShow false;
		_SonyContactsTexte ctrlShow false;
		_SonyContactsList ctrlShow false;
		_SonyFiche ctrlShow false;
		_SonyFicheName ctrlShow false;
		_SonyFicheNum ctrlShow false;
		_SonyFicheBtnSms ctrlShow false;
		_SonyFicheBtnAppel ctrlShow false;
		_SonyFicheBtnDelete ctrlShow false;
		_SonyCentral ctrlShow false;
		_SonyCentralList ctrlShow false;
		_SonyCentralBtnApp ctrlShow false;
		_SonyCentralBtnRaf ctrlShow false;
		_SonyCentralBtnRac ctrlShow false;
		_SonyNewContact ctrlShow false;
		_SonyNewContactAnn ctrlShow false;
		_SonyNewContactAdd ctrlShow false;
		_SonyNewContactName ctrlShow false;
		_SonyNewContactNum ctrlShow false;
		_SonyRecents ctrlShow false;
		_SonyRecentsLb ctrlShow false;
		_SonyRecentsVider ctrlShow false;
		_SonyRecentsApp ctrlShow false;
		_SonyRecentsSms ctrlShow false;
		_SonyAppelRecents ctrlShow false;
		_SonyReglBtnFg ctrlShow false;
		_SonyReglBtnFm ctrlShow false;
		_SonyReglBtnFd ctrlShow false;
		_SonyReglBtnF2g ctrlShow false;
		_SonyReglBtnF2m ctrlShow false;
		_SonyReglBtnF2d ctrlShow false;
		_SonySms ctrlShow false;
		_SonySmsLb ctrlShow false;
		_SonySmsTexte ctrlShow false;
		_SonySmsBtnRep ctrlShow false;
		_SonySmsBtnSup ctrlShow false;
		_SonySmsBtnNew ctrlShow false;
		_SonyNewSms ctrlShow false;
		_SonyNewSmsNameTexte ctrlShow false;
		_SonyNewSmsNumEdit ctrlShow false;
		_SonyNewSmsSmsEdit ctrlShow false;
		_SonyNewSmsBtnAnn ctrlShow false;
		_SonyNewSmsBtnSend ctrlShow false;
		_SonyRadio ctrlShow true;
		_SonyRadioRaf ctrlShow true;
		_SonyRadioBtn1 ctrlShow true;
		_SonyRadioBtn2 ctrlShow true;
		_SonyRadioBtn3 ctrlShow true;
		_SonyRadioBtn4 ctrlShow true;
		_SonyRadioBtn5 ctrlShow true;
		_SonyRadioBtn6 ctrlShow true;
		_SonyRadioBtn7 ctrlShow true;
		_SonyRadioBtn8 ctrlShow true;
		_SonyRadioBtn9 ctrlShow true;
		_SonyRadioBtn10 ctrlShow true;
		_SonyRadioBtn11 ctrlShow true;
		_SonyRadioBtn12 ctrlShow true;
		_SonyRadioBtn13 ctrlShow true;
		_SonyRadioBtn14 ctrlShow true;
		_SonyRadioBtn15 ctrlShow true;
		_SonyRadioBtn16 ctrlShow true;
		_SonyRadioBtn17 ctrlShow true;
		_SonyRadioBtn21 ctrlShow true;
		_SonyRadioCo1 ctrlShow true;
		_SonyRadioCo2 ctrlShow true;
		_SonyRadioCo3 ctrlShow true;
		_SonyRadioCo4 ctrlShow true;
		_SonyRadioCo5 ctrlShow true;
		_SonyRadioCo6 ctrlShow true;
		_SonyRadioCo7 ctrlShow true;
		_SonyRadioCo8 ctrlShow true;
		_SonyRadioCo9 ctrlShow true;
		_SonyRadioCo10 ctrlShow true;
		_SonyRadioCo11 ctrlShow true;
		_SonyRadioCo12 ctrlShow true;
		_SonyRadioCo13 ctrlShow true;
		_SonyRadioCo14 ctrlShow true;
		_SonyRadioCo15 ctrlShow true;
		_SonyRadioCo16 ctrlShow true;
		_SonyRadioCo17 ctrlShow true;
		_SonyRadioCo21 ctrlShow true;
		_SonyRadioNb1 ctrlShow true;
		_SonyRadioNb2 ctrlShow true;
		_SonyRadioNb3 ctrlShow true;
		_SonyRadioNb4 ctrlShow true;
		_SonyRadioNb5 ctrlShow true;
		_SonyRadioNb6 ctrlShow true;
		_SonyRadioNb7 ctrlShow true;
		_SonyRadioNb8 ctrlShow true;
		_SonyRadioNb9 ctrlShow true;
		_SonyRadioNb10 ctrlShow true;
		_SonyRadioNb11 ctrlShow true;
		_SonyRadioNb12 ctrlShow true;
		_SonyRadioNb13 ctrlShow true;
		_SonyRadioNb14 ctrlShow true;
		_SonyRadioNb15 ctrlShow true;
		_SonyRadioNb16 ctrlShow true;
		_SonyRadioNb17 ctrlShow true;
		_SonyRadioNb21 ctrlShow true;
		_home ctrlShow true;
		[] call ALF_fnc_setupRadioSonyP;
		_SonyRadioRaf buttonSetAction "[] call ALF_fnc_menuSonyP;";
	};

	case 6 : {
		_SonyMenu ctrlShow false;
		_SonyMenuLock ctrlShow false;
		_SonyMenuBtnAppel ctrlShow false;
		_SonyMenuBtnSms ctrlShow false;
		_SonyMenuBtnContact ctrlShow false;
		_SonyMenuBtnRegl ctrlShow false;
		_SonyMenuBtnRadio ctrlShow false;
		_SonyRingCall ctrlShow false;
		_SonyRingCallBtnDecro ctrlShow false;
		_SonyRingCallBtnRefus ctrlShow false;
		_SonyInCall ctrlShow false;
		_SonyInCallHP ctrlShow false;
		_SonyInCallMute ctrlShow false;
		_SonyInCallBtnVolp ctrlShow false;
		_SonyInCallBtnVolm ctrlShow false;
		_SonyInCallBtnHP ctrlShow false;
		_SonyInCallBtnMute ctrlShow false;
		_SonyInCallName ctrlShow false;
		_SonyInCallNumber ctrlShow false;
		_SonyInCallTime ctrlShow false;
		_SonyInCallBtnRefuse ctrlShow false;
		_SonyRegl ctrlShow false;
		_SonyReglON1 ctrlShow false;
		_SonyReglOFF1 ctrlShow false;
		_SonyReglON2 ctrlShow false;
		_SonyReglOFF2 ctrlShow false;
		_SonyReglON3 ctrlShow false;
		_SonyReglOFF3 ctrlShow false;
		_SonyReglBtnAvion ctrlShow false;
		_SonyReglBtnSilence ctrlShow false;
		_SonyReglBtnAnon ctrlShow false;
		_SonyDate ctrlShow false;
		_SonyRadio ctrlShow false;
		_SonyRadioRaf ctrlShow false;
		_SonyRadioBtn1 ctrlShow false;
		_SonyRadioBtn2 ctrlShow false;
		_SonyRadioBtn3 ctrlShow false;
		_SonyRadioBtn4 ctrlShow false;
		_SonyRadioBtn5 ctrlShow false;
		_SonyRadioBtn6 ctrlShow false;
		_SonyRadioBtn7 ctrlShow false;
		_SonyRadioBtn8 ctrlShow false;
		_SonyRadioBtn9 ctrlShow false;
		_SonyRadioBtn10 ctrlShow false;
		_SonyRadioBtn11 ctrlShow false;
		_SonyRadioBtn12 ctrlShow false;
		_SonyRadioBtn13 ctrlShow false;
		_SonyRadioBtn14 ctrlShow false;
		_SonyRadioBtn15 ctrlShow false;
		_SonyRadioBtn16 ctrlShow false;
		_SonyRadioBtn17 ctrlShow false;
		_SonyRadioBtn21 ctrlShow false;
		_SonyRadioCo1 ctrlShow false;
		_SonyRadioCo2 ctrlShow false;
		_SonyRadioCo3 ctrlShow false;
		_SonyRadioCo4 ctrlShow false;
		_SonyRadioCo5 ctrlShow false;
		_SonyRadioCo6 ctrlShow false;
		_SonyRadioCo7 ctrlShow false;
		_SonyRadioCo8 ctrlShow false;
		_SonyRadioCo9 ctrlShow false;
		_SonyRadioCo10 ctrlShow false;
		_SonyRadioCo11 ctrlShow false;
		_SonyRadioCo12 ctrlShow false;
		_SonyRadioCo13 ctrlShow false;
		_SonyRadioCo14 ctrlShow false;
		_SonyRadioCo15 ctrlShow false;
		_SonyRadioCo16 ctrlShow false;
		_SonyRadioCo17 ctrlShow false;
		_SonyRadioCo21 ctrlShow false;
		_SonyRadioNb1 ctrlShow false;
		_SonyRadioNb2 ctrlShow false;
		_SonyRadioNb3 ctrlShow false;
		_SonyRadioNb4 ctrlShow false;
		_SonyRadioNb5 ctrlShow false;
		_SonyRadioNb6 ctrlShow false;
		_SonyRadioNb7 ctrlShow false;
		_SonyRadioNb8 ctrlShow false;
		_SonyRadioNb9 ctrlShow false;
		_SonyRadioNb10 ctrlShow false;
		_SonyRadioNb11 ctrlShow false;
		_SonyRadioNb12 ctrlShow false;
		_SonyRadioNb13 ctrlShow false;
		_SonyRadioNb14 ctrlShow false;
		_SonyRadioNb15 ctrlShow false;
		_SonyRadioNb16 ctrlShow false;
		_SonyRadioNb17 ctrlShow false;
		_SonyRadioNb21 ctrlShow false;
		_SonyMenuBtnCentral ctrlShow false;
		_SonyReglBtnVolp1 ctrlShow false;
		_SonyReglBtnVolm1 ctrlShow false;
		_SonyContacts ctrlShow false;
		_SonyContactsAdd ctrlShow false;
		_SonyContactsTexte ctrlShow false;
		_SonyContactsList ctrlShow false;
		_SonyFiche ctrlShow false;
		_SonyFicheName ctrlShow false;
		_SonyFicheNum ctrlShow false;
		_SonyFicheBtnSms ctrlShow false;
		_SonyFicheBtnAppel ctrlShow false;
		_SonyFicheBtnDelete ctrlShow false;
		_SonyCentral ctrlShow false;
		_SonyCentralList ctrlShow false;
		_SonyCentralBtnApp ctrlShow false;
		_SonyCentralBtnRaf ctrlShow false;
		_SonyCentralBtnRac ctrlShow false;
		_SonyNewContact ctrlShow false;
		_SonyNewContactAnn ctrlShow false;
		_SonyNewContactAdd ctrlShow false;
		_SonyNewContactName ctrlShow false;
		_SonyNewContactNum ctrlShow false;
		_SonyRecents ctrlShow false;
		_SonyRecentsLb ctrlShow false;
		_SonyRecentsVider ctrlShow false;
		_SonyRecentsApp ctrlShow false;
		_SonyRecentsSms ctrlShow false;
		_SonyReglBtnFg ctrlShow false;
		_SonyReglBtnFm ctrlShow false;
		_SonyReglBtnFd ctrlShow false;
		_SonyReglBtnF2g ctrlShow false;
		_SonyReglBtnF2m ctrlShow false;
		_SonyReglBtnF2d ctrlShow false;
		_SonySms ctrlShow false;
		_SonySmsLb ctrlShow false;
		_SonySmsTexte ctrlShow false;
		_SonySmsBtnRep ctrlShow false;
		_SonySmsBtnSup ctrlShow false;
		_SonySmsBtnNew ctrlShow false;
		_SonyNewSms ctrlShow true;
		_SonyNewSmsNameTexte ctrlShow false;
		_SonyNewSmsNumEdit ctrlShow true;
		_SonyNewSmsSmsEdit ctrlShow true;
		_SonyNewSmsBtnAnn ctrlShow true;
		_SonyNewSmsBtnSend ctrlShow true;
		_SonyAppel ctrlShow false;
		_SonyAppelBtn ctrlShow false;
		_SonyAppelEdit ctrlShow false;
		_SonyAppelRecents ctrlShow false;
		_home ctrlShow true;
		_SonyNewSmsBtnAnn buttonSetAction "uiNamespace setVariable ['sonyp',2]; [] call ALF_fnc_menuSonyP;";
		_SonyNewSmsBtnSend buttonSetAction "[] call ALF_fnc_SonyPSendNewSms;";
	};

	case 7 : {
		private["_data","_numero","_name"];
		_data = _this select 0;
		_name = _data select 0;
		_numero = _data select 1;

		_SonyMenu ctrlShow false;
		_SonyMenuLock ctrlShow false;
		_SonyMenuBtnAppel ctrlShow false;
		_SonyMenuBtnSms ctrlShow false;
		_SonyMenuBtnContact ctrlShow false;
		_SonyMenuBtnRegl ctrlShow false;
		_SonyMenuBtnRadio ctrlShow false;
		_SonyRingCall ctrlShow false;
		_SonyRingCallBtnDecro ctrlShow false;
		_SonyRingCallBtnRefus ctrlShow false;
		_SonyInCall ctrlShow false;
		_SonyInCallHP ctrlShow false;
		_SonyInCallMute ctrlShow false;
		_SonyInCallBtnVolp ctrlShow false;
		_SonyInCallBtnVolm ctrlShow false;
		_SonyInCallBtnHP ctrlShow false;
		_SonyInCallBtnMute ctrlShow false;
		_SonyInCallName ctrlShow false;
		_SonyInCallNumber ctrlShow false;
		_SonyInCallTime ctrlShow false;
		_SonyInCallBtnRefuse ctrlShow false;
		_SonyRegl ctrlShow false;
		_SonyReglON1 ctrlShow false;
		_SonyReglOFF1 ctrlShow false;
		_SonyReglON2 ctrlShow false;
		_SonyReglOFF2 ctrlShow false;
		_SonyReglON3 ctrlShow false;
		_SonyReglOFF3 ctrlShow false;
		_SonyReglBtnAvion ctrlShow false;
		_SonyReglBtnSilence ctrlShow false;
		_SonyReglBtnAnon ctrlShow false;
		_SonyDate ctrlShow false;
		_SonyRadio ctrlShow false;
		_SonyRadioRaf ctrlShow false;
		_SonyRadioBtn1 ctrlShow false;
		_SonyRadioBtn2 ctrlShow false;
		_SonyRadioBtn3 ctrlShow false;
		_SonyRadioBtn4 ctrlShow false;
		_SonyRadioBtn5 ctrlShow false;
		_SonyRadioBtn6 ctrlShow false;
		_SonyRadioBtn7 ctrlShow false;
		_SonyRadioBtn8 ctrlShow false;
		_SonyRadioBtn9 ctrlShow false;
		_SonyRadioBtn10 ctrlShow false;
		_SonyRadioBtn11 ctrlShow false;
		_SonyRadioBtn12 ctrlShow false;
		_SonyRadioBtn13 ctrlShow false;
		_SonyRadioBtn14 ctrlShow false;
		_SonyRadioBtn15 ctrlShow false;
		_SonyRadioBtn16 ctrlShow false;
		_SonyRadioBtn17 ctrlShow false;
		_SonyRadioBtn21 ctrlShow false;
		_SonyRadioCo1 ctrlShow false;
		_SonyRadioCo2 ctrlShow false;
		_SonyRadioCo3 ctrlShow false;
		_SonyRadioCo4 ctrlShow false;
		_SonyRadioCo5 ctrlShow false;
		_SonyRadioCo6 ctrlShow false;
		_SonyRadioCo7 ctrlShow false;
		_SonyRadioCo8 ctrlShow false;
		_SonyRadioCo9 ctrlShow false;
		_SonyRadioCo10 ctrlShow false;
		_SonyRadioCo11 ctrlShow false;
		_SonyRadioCo12 ctrlShow false;
		_SonyRadioCo13 ctrlShow false;
		_SonyRadioCo14 ctrlShow false;
		_SonyRadioCo15 ctrlShow false;
		_SonyRadioCo16 ctrlShow false;
		_SonyRadioCo17 ctrlShow false;
		_SonyRadioCo21 ctrlShow false;
		_SonyRadioNb1 ctrlShow false;
		_SonyRadioNb2 ctrlShow false;
		_SonyRadioNb3 ctrlShow false;
		_SonyRadioNb4 ctrlShow false;
		_SonyRadioNb5 ctrlShow false;
		_SonyRadioNb6 ctrlShow false;
		_SonyRadioNb7 ctrlShow false;
		_SonyRadioNb8 ctrlShow false;
		_SonyRadioNb9 ctrlShow false;
		_SonyRadioNb10 ctrlShow false;
		_SonyRadioNb11 ctrlShow false;
		_SonyRadioNb12 ctrlShow false;
		_SonyRadioNb13 ctrlShow false;
		_SonyRadioNb14 ctrlShow false;
		_SonyRadioNb15 ctrlShow false;
		_SonyRadioNb16 ctrlShow false;
		_SonyRadioNb17 ctrlShow false;
		_SonyRadioNb21 ctrlShow false;
		_SonyMenuBtnCentral ctrlShow false;
		_SonyReglBtnVolp1 ctrlShow false;
		_SonyReglBtnVolm1 ctrlShow false;
		_SonyContacts ctrlShow false;
		_SonyContactsAdd ctrlShow false;
		_SonyContactsTexte ctrlShow false;
		_SonyContactsList ctrlShow false;
		_SonyFiche ctrlShow false;
		_SonyFicheName ctrlShow false;
		_SonyFicheNum ctrlShow false;
		_SonyFicheBtnSms ctrlShow false;
		_SonyFicheBtnAppel ctrlShow false;
		_SonyFicheBtnDelete ctrlShow false;
		_SonyCentral ctrlShow false;
		_SonyCentralList ctrlShow false;
		_SonyCentralBtnApp ctrlShow false;
		_SonyCentralBtnRaf ctrlShow false;
		_SonyCentralBtnRac ctrlShow false;
		_SonyNewContact ctrlShow false;
		_SonyNewContactAnn ctrlShow false;
		_SonyNewContactAdd ctrlShow false;
		_SonyNewContactName ctrlShow false;
		_SonyNewContactNum ctrlShow false;
		_SonyRecents ctrlShow false;
		_SonyRecentsLb ctrlShow false;
		_SonyRecentsVider ctrlShow false;
		_SonyRecentsApp ctrlShow false;
		_SonyRecentsSms ctrlShow false;
		_SonyReglBtnFg ctrlShow false;
		_SonyReglBtnFm ctrlShow false;
		_SonyReglBtnFd ctrlShow false;
		_SonyReglBtnF2g ctrlShow false;
		_SonyReglBtnF2m ctrlShow false;
		_SonyReglBtnF2d ctrlShow false;
		_SonySms ctrlShow false;
		_SonySmsLb ctrlShow false;
		_SonySmsTexte ctrlShow false;
		_SonySmsBtnRep ctrlShow false;
		_SonySmsBtnSup ctrlShow false;
		_SonySmsBtnNew ctrlShow false;
		_SonyNewSms ctrlShow true;
		_SonyNewSmsNameTexte ctrlShow true;
		_SonyNewSmsNumEdit ctrlShow false;
		_SonyNewSmsSmsEdit ctrlShow true;
		_SonyNewSmsBtnAnn ctrlShow true;
		_SonyNewSmsBtnSend ctrlShow true;
		_SonyAppel ctrlShow false;
		_SonyAppelBtn ctrlShow false;
		_SonyAppelEdit ctrlShow false;
		_SonyAppelRecents ctrlShow false;
		_home ctrlShow true;

		pInActNumber = _numero;
		_SonyNewSmsNameTexte ctrlSetStructuredText parseText format["<t align='left' style='0' shadow='0' color='#000000' font='HelveticaNeueLTStdLt' size='1'>%1</t>", _name];
		_SonyNewSmsBtnAnn buttonSetAction "uiNamespace setVariable ['sonyp',9]; [] call ALF_fnc_menuSonyP;";
		_SonyNewSmsBtnSend buttonSetAction "[pInActNumber] call ALF_fnc_SonyPSendSmsContact;";
	};

	case 8 : {
		if (!life_pompier_service) exitWith {};
		_SonyMenu ctrlShow false;
		_SonyMenuLock ctrlShow false;
		_SonyMenuBtnAppel ctrlShow false;
		_SonyMenuBtnSms ctrlShow false;
		_SonyMenuBtnContact ctrlShow false;
		_SonyMenuBtnRegl ctrlShow false;
		_SonyMenuBtnRadio ctrlShow false;
		_SonyRingCall ctrlShow false;
		_SonyRingCallBtnDecro ctrlShow false;
		_SonyRingCallBtnRefus ctrlShow false;
		_SonyInCall ctrlShow false;
		_SonyInCallHP ctrlShow false;
		_SonyInCallMute ctrlShow false;
		_SonyInCallBtnVolp ctrlShow false;
		_SonyInCallBtnVolm ctrlShow false;
		_SonyInCallBtnHP ctrlShow false;
		_SonyInCallBtnMute ctrlShow false;
		_SonyInCallName ctrlShow false;
		_SonyInCallNumber ctrlShow false;
		_SonyInCallTime ctrlShow false;
		_SonyInCallBtnRefuse ctrlShow false;
		_SonyRegl ctrlShow false;
		_SonyReglON1 ctrlShow false;
		_SonyReglOFF1 ctrlShow false;
		_SonyReglON2 ctrlShow false;
		_SonyReglOFF2 ctrlShow false;
		_SonyReglON3 ctrlShow false;
		_SonyReglOFF3 ctrlShow false;
		_SonyReglBtnAvion ctrlShow false;
		_SonyReglBtnSilence ctrlShow false;
		_SonyReglBtnAnon ctrlShow false;
		_SonyDate ctrlShow false;
		_SonyRadio ctrlShow false;
		_SonyRadioRaf ctrlShow false;
		_SonyRadioBtn1 ctrlShow false;
		_SonyRadioBtn2 ctrlShow false;
		_SonyRadioBtn3 ctrlShow false;
		_SonyRadioBtn4 ctrlShow false;
		_SonyRadioBtn5 ctrlShow false;
		_SonyRadioBtn6 ctrlShow false;
		_SonyRadioBtn7 ctrlShow false;
		_SonyRadioBtn8 ctrlShow false;
		_SonyRadioBtn9 ctrlShow false;
		_SonyRadioBtn10 ctrlShow false;
		_SonyRadioBtn11 ctrlShow false;
		_SonyRadioBtn12 ctrlShow false;
		_SonyRadioBtn13 ctrlShow false;
		_SonyRadioBtn14 ctrlShow false;
		_SonyRadioBtn15 ctrlShow false;
		_SonyRadioBtn16 ctrlShow false;
		_SonyRadioBtn17 ctrlShow false;
		_SonyRadioBtn21 ctrlShow false;
		_SonyRadioCo1 ctrlShow false;
		_SonyRadioCo2 ctrlShow false;
		_SonyRadioCo3 ctrlShow false;
		_SonyRadioCo4 ctrlShow false;
		_SonyRadioCo5 ctrlShow false;
		_SonyRadioCo6 ctrlShow false;
		_SonyRadioCo7 ctrlShow false;
		_SonyRadioCo8 ctrlShow false;
		_SonyRadioCo9 ctrlShow false;
		_SonyRadioCo10 ctrlShow false;
		_SonyRadioCo11 ctrlShow false;
		_SonyRadioCo12 ctrlShow false;
		_SonyRadioCo13 ctrlShow false;
		_SonyRadioCo14 ctrlShow false;
		_SonyRadioCo15 ctrlShow false;
		_SonyRadioCo16 ctrlShow false;
		_SonyRadioCo17 ctrlShow false;
		_SonyRadioCo21 ctrlShow false;
		_SonyRadioNb1 ctrlShow false;
		_SonyRadioNb2 ctrlShow false;
		_SonyRadioNb3 ctrlShow false;
		_SonyRadioNb4 ctrlShow false;
		_SonyRadioNb5 ctrlShow false;
		_SonyRadioNb6 ctrlShow false;
		_SonyRadioNb7 ctrlShow false;
		_SonyRadioNb8 ctrlShow false;
		_SonyRadioNb9 ctrlShow false;
		_SonyRadioNb10 ctrlShow false;
		_SonyRadioNb11 ctrlShow false;
		_SonyRadioNb12 ctrlShow false;
		_SonyRadioNb13 ctrlShow false;
		_SonyRadioNb14 ctrlShow false;
		_SonyRadioNb15 ctrlShow false;
		_SonyRadioNb16 ctrlShow false;
		_SonyRadioNb17 ctrlShow false;
		_SonyRadioNb21 ctrlShow false;
		_SonyMenuBtnCentral ctrlShow false;
		_SonyReglBtnVolp1 ctrlShow false;
		_SonyReglBtnVolm1 ctrlShow false;
		_SonyContacts ctrlShow false;
		_SonyContactsAdd ctrlShow false;
		_SonyContactsTexte ctrlShow false;
		_SonyContactsList ctrlShow false;
		_SonyNewContact ctrlShow false;
		_SonyNewContactAnn ctrlShow false;
		_SonyNewContactAdd ctrlShow false;
		_SonyNewContactName ctrlShow false;
		_SonyNewContactNum ctrlShow false;
		_SonyCentral ctrlShow true;
		_SonyCentralList ctrlShow true;
		_SonyCentralBtnApp ctrlShow true;
		_SonyCentralBtnRaf ctrlShow true;
		_SonyCentralBtnRac ctrlShow true;
		_SonyFiche ctrlShow false;
		_SonyFicheName ctrlShow false;
		_SonyFicheNum ctrlShow false;
		_SonyFicheBtnSms ctrlShow false;
		_SonyFicheBtnAppel ctrlShow false;
		_SonyFicheBtnDelete ctrlShow false;
		_SonyAppel ctrlShow false;
		_SonyAppelBtn ctrlShow false;
		_SonyAppelEdit ctrlShow false;
		_SonyRecents ctrlShow false;
		_SonyRecentsLb ctrlShow false;
		_SonyRecentsVider ctrlShow false;
		_SonyRecentsApp ctrlShow false;
		_SonyRecentsSms ctrlShow false;
		_SonyAppelRecents ctrlShow false;
		_SonyReglBtnFg ctrlShow false;
		_SonyReglBtnFm ctrlShow false;
		_SonyReglBtnFd ctrlShow false;
		_SonyReglBtnF2g ctrlShow false;
		_SonyReglBtnF2m ctrlShow false;
		_SonyReglBtnF2d ctrlShow false;
		_SonySms ctrlShow false;
		_SonySmsLb ctrlShow false;
		_SonySmsTexte ctrlShow false;
		_SonySmsBtnRep ctrlShow false;
		_SonySmsBtnSup ctrlShow false;
		_SonySmsBtnNew ctrlShow false;
		_SonyNewSms ctrlShow false;
		_SonyNewSmsNameTexte ctrlShow false;
		_SonyNewSmsNumEdit ctrlShow false;
		_SonyNewSmsSmsEdit ctrlShow false;
		_SonyNewSmsBtnAnn ctrlShow false;
		_SonyNewSmsBtnSend ctrlShow false;
		_home ctrlShow true;

		lbClear _SonyCentralList;
		
		[player] remoteExecCall ["HC_fnc_loadMedCentral",HC3_Life];

		_SonyCentralBtnApp buttonSetAction "[] spawn ALF_fnc_joinCallCentralP;";
		_SonyCentralBtnRaf buttonSetAction "uiNamespace setVariable ['sonyp',8]; [] call ALF_fnc_menuSonyP;";
		_SonyCentralBtnRac buttonSetAction "[] spawn ALF_fnc_terminateCallCentralP;";
	};

	case 9 : {
		_SonyMenu ctrlShow false;
		_SonyMenuLock ctrlShow false;
		_SonyMenuBtnAppel ctrlShow false;
		_SonyMenuBtnSms ctrlShow false;
		_SonyMenuBtnContact ctrlShow false;
		_SonyMenuBtnRegl ctrlShow false;
		_SonyMenuBtnRadio ctrlShow false;
		_SonyRingCall ctrlShow false;
		_SonyRingCallBtnDecro ctrlShow false;
		_SonyRingCallBtnRefus ctrlShow false;
		_SonyInCall ctrlShow false;
		_SonyInCallHP ctrlShow false;
		_SonyInCallMute ctrlShow false;
		_SonyInCallBtnVolp ctrlShow false;
		_SonyInCallBtnVolm ctrlShow false;
		_SonyInCallBtnHP ctrlShow false;
		_SonyInCallBtnMute ctrlShow false;
		_SonyInCallName ctrlShow false;
		_SonyInCallNumber ctrlShow false;
		_SonyInCallTime ctrlShow false;
		_SonyInCallBtnRefuse ctrlShow false;
		_SonyRegl ctrlShow false;
		_SonyReglON1 ctrlShow false;
		_SonyReglOFF1 ctrlShow false;
		_SonyReglON2 ctrlShow false;
		_SonyReglOFF2 ctrlShow false;
		_SonyReglON3 ctrlShow false;
		_SonyReglOFF3 ctrlShow false;
		_SonyReglBtnAvion ctrlShow false;
		_SonyReglBtnSilence ctrlShow false;
		_SonyReglBtnAnon ctrlShow false;
		_SonyDate ctrlShow false;
		_SonyRadio ctrlShow false;
		_SonyRadioRaf ctrlShow false;
		_SonyRadioBtn1 ctrlShow false;
		_SonyRadioBtn2 ctrlShow false;
		_SonyRadioBtn3 ctrlShow false;
		_SonyRadioBtn4 ctrlShow false;
		_SonyRadioBtn5 ctrlShow false;
		_SonyRadioBtn6 ctrlShow false;
		_SonyRadioBtn7 ctrlShow false;
		_SonyRadioBtn8 ctrlShow false;
		_SonyRadioBtn9 ctrlShow false;
		_SonyRadioBtn10 ctrlShow false;
		_SonyRadioBtn11 ctrlShow false;
		_SonyRadioBtn12 ctrlShow false;
		_SonyRadioBtn13 ctrlShow false;
		_SonyRadioBtn14 ctrlShow false;
		_SonyRadioBtn15 ctrlShow false;
		_SonyRadioBtn16 ctrlShow false;
		_SonyRadioBtn17 ctrlShow false;
		_SonyRadioBtn21 ctrlShow false;
		_SonyRadioCo1 ctrlShow false;
		_SonyRadioCo2 ctrlShow false;
		_SonyRadioCo3 ctrlShow false;
		_SonyRadioCo4 ctrlShow false;
		_SonyRadioCo5 ctrlShow false;
		_SonyRadioCo6 ctrlShow false;
		_SonyRadioCo7 ctrlShow false;
		_SonyRadioCo8 ctrlShow false;
		_SonyRadioCo9 ctrlShow false;
		_SonyRadioCo10 ctrlShow false;
		_SonyRadioCo11 ctrlShow false;
		_SonyRadioCo12 ctrlShow false;
		_SonyRadioCo13 ctrlShow false;
		_SonyRadioCo14 ctrlShow false;
		_SonyRadioCo15 ctrlShow false;
		_SonyRadioCo16 ctrlShow false;
		_SonyRadioCo17 ctrlShow false;
		_SonyRadioCo21 ctrlShow false;
		_SonyRadioNb1 ctrlShow false;
		_SonyRadioNb2 ctrlShow false;
		_SonyRadioNb3 ctrlShow false;
		_SonyRadioNb4 ctrlShow false;
		_SonyRadioNb5 ctrlShow false;
		_SonyRadioNb6 ctrlShow false;
		_SonyRadioNb7 ctrlShow false;
		_SonyRadioNb8 ctrlShow false;
		_SonyRadioNb9 ctrlShow false;
		_SonyRadioNb10 ctrlShow false;
		_SonyRadioNb11 ctrlShow false;
		_SonyRadioNb12 ctrlShow false;
		_SonyRadioNb13 ctrlShow false;
		_SonyRadioNb14 ctrlShow false;
		_SonyRadioNb15 ctrlShow false;
		_SonyRadioNb16 ctrlShow false;
		_SonyRadioNb17 ctrlShow false;
		_SonyRadioNb21 ctrlShow false;
		_SonyMenuBtnCentral ctrlShow false;
		_SonyReglBtnVolp1 ctrlShow false;
		_SonyReglBtnVolm1 ctrlShow false;
		_SonyContacts ctrlShow false;
		_SonyContactsAdd ctrlShow false;
		_SonyContactsTexte ctrlShow false;
		_SonyContactsList ctrlShow false;
		_SonyCentral ctrlShow false;
		_SonyCentralList ctrlShow false;
		_SonyCentralBtnApp ctrlShow false;
		_SonyCentralBtnRaf ctrlShow false;
		_SonyCentralBtnRac ctrlShow false;
		_SonyNewContact ctrlShow false;
		_SonyNewContactAnn ctrlShow false;
		_SonyNewContactAdd ctrlShow false;
		_SonyNewContactName ctrlShow false;
		_SonyNewContactNum ctrlShow false;
		_SonyFiche ctrlShow true;
		_SonyFicheName ctrlShow true;
		_SonyFicheNum ctrlShow true;
		_SonyFicheBtnSms ctrlShow true;
		_SonyFicheBtnAppel ctrlShow true;
		_SonyFicheBtnDelete ctrlShow true;
		_SonyAppel ctrlShow false;
		_SonyAppelBtn ctrlShow false;
		_SonyAppelEdit ctrlShow false;
		_SonyRecents ctrlShow false;
		_SonyRecentsLb ctrlShow false;
		_SonyRecentsVider ctrlShow false;
		_SonyRecentsApp ctrlShow false;
		_SonyRecentsSms ctrlShow false;
		_SonyAppelRecents ctrlShow false;
		_SonyReglBtnFg ctrlShow false;
		_SonyReglBtnFm ctrlShow false;
		_SonyReglBtnFd ctrlShow false;
		_SonyReglBtnF2g ctrlShow false;
		_SonyReglBtnF2m ctrlShow false;
		_SonyReglBtnF2d ctrlShow false;
		_SonySms ctrlShow false;
		_SonySmsLb ctrlShow false;
		_SonySmsTexte ctrlShow false;
		_SonySmsBtnRep ctrlShow false;
		_SonySmsBtnSup ctrlShow false;
		_SonySmsBtnNew ctrlShow false;
		_SonyNewSms ctrlShow false;
		_SonyNewSmsNameTexte ctrlShow false;
		_SonyNewSmsNumEdit ctrlShow false;
		_SonyNewSmsSmsEdit ctrlShow false;
		_SonyNewSmsBtnAnn ctrlShow false;
		_SonyNewSmsBtnSend ctrlShow false;
		_home ctrlShow true;

		private _cible = lbData[39113,lbCurSel (39113)];
		_cible = call compile format["%1", _cible];
		pInActContact = _cible;

		_SonyFicheName ctrlSetStructuredText parseText format["<t align='left' style='0' shadow='0' color='#000000' font='HelveticaNeueLTStdLt' size='1.5'>%1</t>", _cible select 0];
		_SonyFicheNum ctrlSetStructuredText parseText format["<t align='left' style='0' shadow='0' color='#000000' font='HelveticaNeueLTStdLt' size='1'>%1</t>", _cible select 1];

		_SonyFicheBtnSms buttonSetAction "uiNamespace setVariable ['sonyp',7]; [pInActContact] call ALF_fnc_menuSonyP;";
		_SonyFicheBtnAppel buttonSetAction "[] spawn ALF_fnc_SonyPCallContact;";
		_SonyFicheBtnDelete buttonSetAction "[] spawn ALF_fnc_SonyPDeleteContact;";
	};
	case 10 : {
		_SonyMenu ctrlShow false;
		_SonyMenuLock ctrlShow false;
		_SonyMenuBtnAppel ctrlShow false;
		_SonyMenuBtnSms ctrlShow false;
		_SonyMenuBtnContact ctrlShow false;
		_SonyMenuBtnRegl ctrlShow false;
		_SonyMenuBtnRadio ctrlShow false;
		_SonyRingCall ctrlShow false;
		_SonyRingCallBtnDecro ctrlShow false;
		_SonyRingCallBtnRefus ctrlShow false;
		_SonyInCall ctrlShow false;
		_SonyInCallHP ctrlShow false;
		_SonyInCallMute ctrlShow false;
		_SonyInCallBtnVolp ctrlShow false;
		_SonyInCallBtnVolm ctrlShow false;
		_SonyInCallBtnHP ctrlShow false;
		_SonyInCallBtnMute ctrlShow false;
		_SonyInCallName ctrlShow false;
		_SonyInCallNumber ctrlShow false;
		_SonyInCallTime ctrlShow false;
		_SonyInCallBtnRefuse ctrlShow false;
		_SonyRegl ctrlShow false;
		_SonyReglON1 ctrlShow false;
		_SonyReglOFF1 ctrlShow false;
		_SonyReglON2 ctrlShow false;
		_SonyReglOFF2 ctrlShow false;
		_SonyReglON3 ctrlShow false;
		_SonyReglOFF3 ctrlShow false;
		_SonyReglBtnAvion ctrlShow false;
		_SonyReglBtnSilence ctrlShow false;
		_SonyReglBtnAnon ctrlShow false;
		_SonyDate ctrlShow false;
		_SonyRadio ctrlShow false;
		_SonyRadioRaf ctrlShow false;
		_SonyRadioBtn1 ctrlShow false;
		_SonyRadioBtn2 ctrlShow false;
		_SonyRadioBtn3 ctrlShow false;
		_SonyRadioBtn4 ctrlShow false;
		_SonyRadioBtn5 ctrlShow false;
		_SonyRadioBtn6 ctrlShow false;
		_SonyRadioBtn7 ctrlShow false;
		_SonyRadioBtn8 ctrlShow false;
		_SonyRadioBtn9 ctrlShow false;
		_SonyRadioBtn10 ctrlShow false;
		_SonyRadioBtn11 ctrlShow false;
		_SonyRadioBtn12 ctrlShow false;
		_SonyRadioBtn13 ctrlShow false;
		_SonyRadioBtn14 ctrlShow false;
		_SonyRadioBtn15 ctrlShow false;
		_SonyRadioBtn16 ctrlShow false;
		_SonyRadioBtn17 ctrlShow false;
		_SonyRadioBtn21 ctrlShow false;
		_SonyRadioCo1 ctrlShow false;
		_SonyRadioCo2 ctrlShow false;
		_SonyRadioCo3 ctrlShow false;
		_SonyRadioCo4 ctrlShow false;
		_SonyRadioCo5 ctrlShow false;
		_SonyRadioCo6 ctrlShow false;
		_SonyRadioCo7 ctrlShow false;
		_SonyRadioCo8 ctrlShow false;
		_SonyRadioCo9 ctrlShow false;
		_SonyRadioCo10 ctrlShow false;
		_SonyRadioCo11 ctrlShow false;
		_SonyRadioCo12 ctrlShow false;
		_SonyRadioCo13 ctrlShow false;
		_SonyRadioCo14 ctrlShow false;
		_SonyRadioCo15 ctrlShow false;
		_SonyRadioCo16 ctrlShow false;
		_SonyRadioCo17 ctrlShow false;
		_SonyRadioCo21 ctrlShow false;
		_SonyRadioNb1 ctrlShow false;
		_SonyRadioNb2 ctrlShow false;
		_SonyRadioNb3 ctrlShow false;
		_SonyRadioNb4 ctrlShow false;
		_SonyRadioNb5 ctrlShow false;
		_SonyRadioNb6 ctrlShow false;
		_SonyRadioNb7 ctrlShow false;
		_SonyRadioNb8 ctrlShow false;
		_SonyRadioNb9 ctrlShow false;
		_SonyRadioNb10 ctrlShow false;
		_SonyRadioNb11 ctrlShow false;
		_SonyRadioNb12 ctrlShow false;
		_SonyRadioNb13 ctrlShow false;
		_SonyRadioNb14 ctrlShow false;
		_SonyRadioNb15 ctrlShow false;
		_SonyRadioNb16 ctrlShow false;
		_SonyRadioNb17 ctrlShow false;
		_SonyRadioNb21 ctrlShow false;
		_SonyMenuBtnCentral ctrlShow false;
		_SonyReglBtnVolp1 ctrlShow false;
		_SonyReglBtnVolm1 ctrlShow false;
		_SonyContacts ctrlShow false;
		_SonyContactsAdd ctrlShow false;
		_SonyContactsTexte ctrlShow false;
		_SonyContactsList ctrlShow false;
		_SonyCentral ctrlShow false;
		_SonyCentralList ctrlShow false;
		_SonyCentralBtnApp ctrlShow false;
		_SonyCentralBtnRaf ctrlShow false;
		_SonyCentralBtnRac ctrlShow false;
		_SonyFiche ctrlShow false;
		_SonyFicheName ctrlShow false;
		_SonyFicheNum ctrlShow false;
		_SonyFicheBtnSms ctrlShow false;
		_SonyFicheBtnAppel ctrlShow false;
		_SonyFicheBtnDelete ctrlShow false;
		_SonyAppel ctrlShow false;
		_SonyAppelBtn ctrlShow false;
		_SonyRecents ctrlShow false;
		_SonyRecentsLb ctrlShow false;
		_SonyRecentsVider ctrlShow false;
		_SonyRecentsApp ctrlShow false;
		_SonyRecentsSms ctrlShow false;
		_SonyAppelEdit ctrlShow false;
		_SonyAppelRecents ctrlShow false;
		_SonyReglBtnFg ctrlShow false;
		_SonyReglBtnFm ctrlShow false;
		_SonyReglBtnFd ctrlShow false;
		_SonyReglBtnF2g ctrlShow false;
		_SonyReglBtnF2m ctrlShow false;
		_SonyReglBtnF2d ctrlShow false;
		_SonySms ctrlShow false;
		_SonySmsLb ctrlShow false;
		_SonySmsTexte ctrlShow false;
		_SonySmsBtnRep ctrlShow false;
		_SonySmsBtnSup ctrlShow false;
		_SonySmsBtnNew ctrlShow false;
		_SonyNewSms ctrlShow false;
		_SonyNewSmsNameTexte ctrlShow false;
		_SonyNewSmsNumEdit ctrlShow false;
		_SonyNewSmsSmsEdit ctrlShow false;
		_SonyNewSmsBtnAnn ctrlShow false;
		_SonyNewSmsBtnSend ctrlShow false;
		_SonyNewContact ctrlShow true;
		_SonyNewContactAnn ctrlShow true;
		_SonyNewContactAdd ctrlShow true;
		_SonyNewContactName ctrlShow true;
		_SonyNewContactNum ctrlShow true;

		_SonyNewContactAnn buttonSetAction "uiNamespace setVariable ['sonyp',3]; [] call ALF_fnc_menuSonyP;";
		_SonyNewContactAdd buttonSetAction "[] call ALF_fnc_SonyPAddContact;";
		_home ctrlShow true;
	};
	case 11 : {
		_SonyMenu ctrlShow false;
		_SonyMenuLock ctrlShow false;
		_SonyMenuBtnAppel ctrlShow false;
		_SonyMenuBtnSms ctrlShow false;
		_SonyMenuBtnContact ctrlShow false;
		_SonyMenuBtnRegl ctrlShow false;
		_SonyMenuBtnRadio ctrlShow false;
		_SonyRingCall ctrlShow false;
		_SonyRingCallBtnDecro ctrlShow false;
		_SonyRingCallBtnRefus ctrlShow false;
		_SonyInCall ctrlShow false;
		_SonyInCallHP ctrlShow false;
		_SonyInCallMute ctrlShow false;
		_SonyInCallBtnVolp ctrlShow false;
		_SonyInCallBtnVolm ctrlShow false;
		_SonyInCallBtnHP ctrlShow false;
		_SonyInCallBtnMute ctrlShow false;
		_SonyInCallName ctrlShow false;
		_SonyInCallNumber ctrlShow false;
		_SonyInCallTime ctrlShow false;
		_SonyInCallBtnRefuse ctrlShow false;
		_SonyRegl ctrlShow false;
		_SonyReglON1 ctrlShow false;
		_SonyReglOFF1 ctrlShow false;
		_SonyReglON2 ctrlShow false;
		_SonyReglOFF2 ctrlShow false;
		_SonyReglON3 ctrlShow false;
		_SonyReglOFF3 ctrlShow false;
		_SonyReglBtnAvion ctrlShow false;
		_SonyReglBtnSilence ctrlShow false;
		_SonyReglBtnAnon ctrlShow false;
		_SonyDate ctrlShow false;
		_SonyRadio ctrlShow false;
		_SonyRadioRaf ctrlShow false;
		_SonyRadioBtn1 ctrlShow false;
		_SonyRadioBtn2 ctrlShow false;
		_SonyRadioBtn3 ctrlShow false;
		_SonyRadioBtn4 ctrlShow false;
		_SonyRadioBtn5 ctrlShow false;
		_SonyRadioBtn6 ctrlShow false;
		_SonyRadioBtn7 ctrlShow false;
		_SonyRadioBtn8 ctrlShow false;
		_SonyRadioBtn9 ctrlShow false;
		_SonyRadioBtn10 ctrlShow false;
		_SonyRadioBtn11 ctrlShow false;
		_SonyRadioBtn12 ctrlShow false;
		_SonyRadioBtn13 ctrlShow false;
		_SonyRadioBtn14 ctrlShow false;
		_SonyRadioBtn15 ctrlShow false;
		_SonyRadioBtn16 ctrlShow false;
		_SonyRadioBtn17 ctrlShow false;
		_SonyRadioBtn21 ctrlShow false;
		_SonyRadioCo1 ctrlShow false;
		_SonyRadioCo2 ctrlShow false;
		_SonyRadioCo3 ctrlShow false;
		_SonyRadioCo4 ctrlShow false;
		_SonyRadioCo5 ctrlShow false;
		_SonyRadioCo6 ctrlShow false;
		_SonyRadioCo7 ctrlShow false;
		_SonyRadioCo8 ctrlShow false;
		_SonyRadioCo9 ctrlShow false;
		_SonyRadioCo10 ctrlShow false;
		_SonyRadioCo11 ctrlShow false;
		_SonyRadioCo12 ctrlShow false;
		_SonyRadioCo13 ctrlShow false;
		_SonyRadioCo14 ctrlShow false;
		_SonyRadioCo15 ctrlShow false;
		_SonyRadioCo16 ctrlShow false;
		_SonyRadioCo17 ctrlShow false;
		_SonyRadioCo21 ctrlShow false;
		_SonyRadioNb1 ctrlShow false;
		_SonyRadioNb2 ctrlShow false;
		_SonyRadioNb3 ctrlShow false;
		_SonyRadioNb4 ctrlShow false;
		_SonyRadioNb5 ctrlShow false;
		_SonyRadioNb6 ctrlShow false;
		_SonyRadioNb7 ctrlShow false;
		_SonyRadioNb8 ctrlShow false;
		_SonyRadioNb9 ctrlShow false;
		_SonyRadioNb10 ctrlShow false;
		_SonyRadioNb11 ctrlShow false;
		_SonyRadioNb12 ctrlShow false;
		_SonyRadioNb13 ctrlShow false;
		_SonyRadioNb14 ctrlShow false;
		_SonyRadioNb15 ctrlShow false;
		_SonyRadioNb16 ctrlShow false;
		_SonyRadioNb17 ctrlShow false;
		_SonyRadioNb21 ctrlShow false;
		_SonyMenuBtnCentral ctrlShow false;
		_SonyReglBtnVolp1 ctrlShow false;
		_SonyReglBtnVolm1 ctrlShow false;
		_SonyContacts ctrlShow false;
		_SonyContactsAdd ctrlShow false;
		_SonyContactsTexte ctrlShow false;
		_SonyContactsList ctrlShow false;
		_SonyCentral ctrlShow false;
		_SonyCentralList ctrlShow false;
		_SonyCentralBtnApp ctrlShow false;
		_SonyCentralBtnRaf ctrlShow false;
		_SonyCentralBtnRac ctrlShow false;
		_SonyFiche ctrlShow false;
		_SonyFicheName ctrlShow false;
		_SonyFicheNum ctrlShow false;
		_SonyFicheBtnSms ctrlShow false;
		_SonyFicheBtnAppel ctrlShow false;
		_SonyFicheBtnDelete ctrlShow false;
		_SonyAppel ctrlShow false;
		_SonyAppelBtn ctrlShow false;
		_SonyRecents ctrlShow true;
		_SonyRecentsLb ctrlShow true;
		_SonyRecentsVider ctrlShow true;
		_SonyRecentsApp ctrlShow true;
		_SonyRecentsSms ctrlShow true;
		_SonyAppelEdit ctrlShow false;
		_SonyAppelRecents ctrlShow false;
		_SonyNewContact ctrlShow false;
		_SonyNewContactAnn ctrlShow false;
		_SonyNewContactAdd ctrlShow false;
		_SonyNewContactName ctrlShow false;
		_SonyNewContactNum ctrlShow false;
		_SonyReglBtnFg ctrlShow false;
		_SonyReglBtnFm ctrlShow false;
		_SonyReglBtnFd ctrlShow false;
		_SonyReglBtnF2g ctrlShow false;
		_SonyReglBtnF2m ctrlShow false;
		_SonyReglBtnF2d ctrlShow false;
		_SonySms ctrlShow false;
		_SonySmsLb ctrlShow false;
		_SonySmsTexte ctrlShow false;
		_SonySmsBtnRep ctrlShow false;
		_SonySmsBtnSup ctrlShow false;
		_SonySmsBtnNew ctrlShow false;
		_SonyNewSms ctrlShow false;
		_SonyNewSmsNameTexte ctrlShow false;
		_SonyNewSmsNumEdit ctrlShow false;
		_SonyNewSmsSmsEdit ctrlShow false;
		_SonyNewSmsBtnAnn ctrlShow false;
		_SonyNewSmsBtnSend ctrlShow false;

		lbClear _SonyRecentsLb;
		if (count ALF_Phone_Historique > 0) then {
			{
				private _time = _x select 0;
				private _anonyme = _x select 1;
				private _type = _x select 2;
				private _number = _x select 3;
				private _hisName = "Inconnu";
				if(_anonyme) then {_hisName = "Anonyme"; _number = "**********"};
				if (count life_contacts > 0) then {
					{
						if ((_x select 1) isEqualTo _number) exitWith {
							_hisName = _x select 0;
						};
					} forEach life_contacts;
				};
				if(_number isEqualTo "17") then {_hisName = "Gendarmerie"};
				if(_number isEqualTo "18") then {_hisName = "Pompier"};
				_SonyRecentsLb lbAdd format["[%1] - %2 (%3)",_time,_hisName,_number];
				if (_type isEqualTo 0) then {
					_SonyRecentsLb lbSetPicture [(lbSize _SonyRecentsLb)-1,"\ALF_Client2\icons\out.paa"];
				} else {
					_SonyRecentsLb lbSetPicture [(lbSize _SonyRecentsLb)-1,"\ALF_Client2\icons\in.paa"];
				};
				_SonyRecentsLb lbSetData [(lbSize _SonyRecentsLb)-1,str(_x)];
			} forEach ALF_Phone_Historique;
		} else {
			_SonyRecentsLb lbAdd "Aucun historique.";
			_SonyRecentsLb lbSetData [(lbSize _SonyRecentsLb)-1,"Aucun historique."];
		};
		((findDisplay 38999) displayCtrl 39132) lbSetCurSel 0;

		_SonyRecentsVider buttonSetAction "ALF_Phone_Historique = []; [] call ALF_fnc_menuSonyP;";
		_SonyRecentsApp buttonSetAction "[] spawn ALF_fnc_SonyPCallRecent;";
		_SonyRecentsSms buttonSetAction "uiNamespace setVariable ['sonyp',12]; [] call ALF_fnc_menuSonyP;";
		_home ctrlShow true;
	};

	case 12 : {
		private["_data","_numero","_name","_anonyme"];
		if(EQUAL((lbCurSel 39132),-1)) exitWith {hint "Il faut selectionner quelqu'un."; uiNamespace setVariable ['sonyp',11]; [] call ALF_fnc_menuSonyP;};
		_data = CONTROL_DATA(39132);
		if(_data isEqualTo "Aucun historique.") exitWith {uiNamespace setVariable ['sonyp',11]; [] call ALF_fnc_menuSonyP;};
		_data = call compile format["%1", _data];
		_anonyme = _data select 1;
		_numero = _data select 3;
		if(_anonyme) exitWith {hint "Tu ne peux pas repondre à un numéro anonyme."; uiNamespace setVariable ['sonyp',11]; [] call ALF_fnc_menuSonyP;};
		private _length = count (toArray(_numero));
		if(_length < 10) exitWith {hint "Tu ne peux pas repondre à ce numéro."; uiNamespace setVariable ['sonyp',11]; [] call ALF_fnc_menuSonyP;};

		_SonyMenu ctrlShow false;
		_SonyMenuLock ctrlShow false;
		_SonyMenuBtnAppel ctrlShow false;
		_SonyMenuBtnSms ctrlShow false;
		_SonyMenuBtnContact ctrlShow false;
		_SonyMenuBtnRegl ctrlShow false;
		_SonyMenuBtnRadio ctrlShow false;
		_SonyRingCall ctrlShow false;
		_SonyRingCallBtnDecro ctrlShow false;
		_SonyRingCallBtnRefus ctrlShow false;
		_SonyInCall ctrlShow false;
		_SonyInCallHP ctrlShow false;
		_SonyInCallMute ctrlShow false;
		_SonyInCallBtnVolp ctrlShow false;
		_SonyInCallBtnVolm ctrlShow false;
		_SonyInCallBtnHP ctrlShow false;
		_SonyInCallBtnMute ctrlShow false;
		_SonyInCallName ctrlShow false;
		_SonyInCallNumber ctrlShow false;
		_SonyInCallTime ctrlShow false;
		_SonyInCallBtnRefuse ctrlShow false;
		_SonyRegl ctrlShow false;
		_SonyReglON1 ctrlShow false;
		_SonyReglOFF1 ctrlShow false;
		_SonyReglON2 ctrlShow false;
		_SonyReglOFF2 ctrlShow false;
		_SonyReglON3 ctrlShow false;
		_SonyReglOFF3 ctrlShow false;
		_SonyReglBtnAvion ctrlShow false;
		_SonyReglBtnSilence ctrlShow false;
		_SonyReglBtnAnon ctrlShow false;
		_SonyDate ctrlShow false;
		_SonyRadio ctrlShow false;
		_SonyRadioRaf ctrlShow false;
		_SonyRadioBtn1 ctrlShow false;
		_SonyRadioBtn2 ctrlShow false;
		_SonyRadioBtn3 ctrlShow false;
		_SonyRadioBtn4 ctrlShow false;
		_SonyRadioBtn5 ctrlShow false;
		_SonyRadioBtn6 ctrlShow false;
		_SonyRadioBtn7 ctrlShow false;
		_SonyRadioBtn8 ctrlShow false;
		_SonyRadioBtn9 ctrlShow false;
		_SonyRadioBtn10 ctrlShow false;
		_SonyRadioBtn11 ctrlShow false;
		_SonyRadioBtn12 ctrlShow false;
		_SonyRadioBtn13 ctrlShow false;
		_SonyRadioBtn14 ctrlShow false;
		_SonyRadioBtn15 ctrlShow false;
		_SonyRadioBtn16 ctrlShow false;
		_SonyRadioBtn17 ctrlShow false;
		_SonyRadioBtn21 ctrlShow false;
		_SonyRadioCo1 ctrlShow false;
		_SonyRadioCo2 ctrlShow false;
		_SonyRadioCo3 ctrlShow false;
		_SonyRadioCo4 ctrlShow false;
		_SonyRadioCo5 ctrlShow false;
		_SonyRadioCo6 ctrlShow false;
		_SonyRadioCo7 ctrlShow false;
		_SonyRadioCo8 ctrlShow false;
		_SonyRadioCo9 ctrlShow false;
		_SonyRadioCo10 ctrlShow false;
		_SonyRadioCo11 ctrlShow false;
		_SonyRadioCo12 ctrlShow false;
		_SonyRadioCo13 ctrlShow false;
		_SonyRadioCo14 ctrlShow false;
		_SonyRadioCo15 ctrlShow false;
		_SonyRadioCo16 ctrlShow false;
		_SonyRadioCo17 ctrlShow false;
		_SonyRadioCo21 ctrlShow false;
		_SonyRadioNb1 ctrlShow false;
		_SonyRadioNb2 ctrlShow false;
		_SonyRadioNb3 ctrlShow false;
		_SonyRadioNb4 ctrlShow false;
		_SonyRadioNb5 ctrlShow false;
		_SonyRadioNb6 ctrlShow false;
		_SonyRadioNb7 ctrlShow false;
		_SonyRadioNb8 ctrlShow false;
		_SonyRadioNb9 ctrlShow false;
		_SonyRadioNb10 ctrlShow false;
		_SonyRadioNb11 ctrlShow false;
		_SonyRadioNb12 ctrlShow false;
		_SonyRadioNb13 ctrlShow false;
		_SonyRadioNb14 ctrlShow false;
		_SonyRadioNb15 ctrlShow false;
		_SonyRadioNb16 ctrlShow false;
		_SonyRadioNb17 ctrlShow false;
		_SonyRadioNb21 ctrlShow false;
		_SonyMenuBtnCentral ctrlShow false;
		_SonyReglBtnVolp1 ctrlShow false;
		_SonyReglBtnVolm1 ctrlShow false;
		_SonyContacts ctrlShow false;
		_SonyContactsAdd ctrlShow false;
		_SonyContactsTexte ctrlShow false;
		_SonyContactsList ctrlShow false;
		_SonyFiche ctrlShow false;
		_SonyFicheName ctrlShow false;
		_SonyFicheNum ctrlShow false;
		_SonyFicheBtnSms ctrlShow false;
		_SonyFicheBtnAppel ctrlShow false;
		_SonyFicheBtnDelete ctrlShow false;
		_SonyCentral ctrlShow false;
		_SonyCentralList ctrlShow false;
		_SonyCentralBtnApp ctrlShow false;
		_SonyCentralBtnRaf ctrlShow false;
		_SonyCentralBtnRac ctrlShow false;
		_SonyNewContact ctrlShow false;
		_SonyNewContactAnn ctrlShow false;
		_SonyNewContactAdd ctrlShow false;
		_SonyNewContactName ctrlShow false;
		_SonyNewContactNum ctrlShow false;
		_SonyRecents ctrlShow false;
		_SonyRecentsLb ctrlShow false;
		_SonyRecentsVider ctrlShow false;
		_SonyRecentsApp ctrlShow false;
		_SonyRecentsSms ctrlShow false;
		_SonyReglBtnFg ctrlShow false;
		_SonyReglBtnFm ctrlShow false;
		_SonyReglBtnFd ctrlShow false;
		_SonyReglBtnF2g ctrlShow false;
		_SonyReglBtnF2m ctrlShow false;
		_SonyReglBtnF2d ctrlShow false;
		_SonySms ctrlShow false;
		_SonySmsLb ctrlShow false;
		_SonySmsTexte ctrlShow false;
		_SonySmsBtnRep ctrlShow false;
		_SonySmsBtnSup ctrlShow false;
		_SonySmsBtnNew ctrlShow false;
		_SonyNewSms ctrlShow true;
		_SonyNewSmsNameTexte ctrlShow true;
		_SonyNewSmsNumEdit ctrlShow false;
		_SonyNewSmsSmsEdit ctrlShow true;
		_SonyNewSmsBtnAnn ctrlShow true;
		_SonyNewSmsBtnSend ctrlShow true;
		_SonyAppel ctrlShow false;
		_SonyAppelBtn ctrlShow false;
		_SonyAppelEdit ctrlShow false;
		_SonyAppelRecents ctrlShow false;
		_home ctrlShow true;

		_name = "Inconnu";
		if (count life_contacts > 0) then {
			{
				if ((_x select 1) isEqualTo _numero) exitWith {
					_name = _x select 0;
				};
			} forEach life_contacts;
		};
		pInActNumber = _numero;
		_SonyNewSmsNameTexte ctrlSetStructuredText parseText format["<t align='left' shadow='0' color='#000000' font='HelveticaNeueLTStdLt' size='1'>%1</t>", _name];
		_SonyNewSmsBtnAnn buttonSetAction "uiNamespace setVariable ['sonyp',11]; [] call ALF_fnc_menuSonyP;";
		_SonyNewSmsBtnSend buttonSetAction "[pInActNumber] call ALF_fnc_SonyPSendSmsContact;";
	};

	case 13 : {
		_SonyMenu ctrlShow false;
		_SonyMenuLock ctrlShow false;
		_SonyMenuBtnAppel ctrlShow false;
		_SonyMenuBtnSms ctrlShow false;
		_SonyMenuBtnContact ctrlShow false;
		_SonyMenuBtnRegl ctrlShow false;
		_SonyMenuBtnRadio ctrlShow false;
		_SonyRingCall ctrlShow false;
		_SonyRingCallBtnDecro ctrlShow false;
		_SonyRingCallBtnRefus ctrlShow false;
		_SonyInCall ctrlShow false;
		_SonyInCallHP ctrlShow false;
		_SonyInCallMute ctrlShow false;
		_SonyInCallBtnVolp ctrlShow false;
		_SonyInCallBtnVolm ctrlShow false;
		_SonyInCallBtnHP ctrlShow false;
		_SonyInCallBtnMute ctrlShow false;
		_SonyInCallName ctrlShow false;
		_SonyInCallNumber ctrlShow false;
		_SonyInCallTime ctrlShow false;
		_SonyInCallBtnRefuse ctrlShow false;
		_SonyRegl ctrlShow false;
		_SonyReglON1 ctrlShow false;
		_SonyReglOFF1 ctrlShow false;
		_SonyReglON2 ctrlShow false;
		_SonyReglOFF2 ctrlShow false;
		_SonyReglON3 ctrlShow false;
		_SonyReglOFF3 ctrlShow false;
		_SonyReglBtnAvion ctrlShow false;
		_SonyReglBtnSilence ctrlShow false;
		_SonyReglBtnAnon ctrlShow false;
		_SonyDate ctrlShow false;
		_SonyRadio ctrlShow false;
		_SonyRadioRaf ctrlShow false;
		_SonyRadioBtn1 ctrlShow false;
		_SonyRadioBtn2 ctrlShow false;
		_SonyRadioBtn3 ctrlShow false;
		_SonyRadioBtn4 ctrlShow false;
		_SonyRadioBtn5 ctrlShow false;
		_SonyRadioBtn6 ctrlShow false;
		_SonyRadioBtn7 ctrlShow false;
		_SonyRadioBtn8 ctrlShow false;
		_SonyRadioBtn9 ctrlShow false;
		_SonyRadioBtn10 ctrlShow false;
		_SonyRadioBtn11 ctrlShow false;
		_SonyRadioBtn12 ctrlShow false;
		_SonyRadioBtn13 ctrlShow false;
		_SonyRadioBtn14 ctrlShow false;
		_SonyRadioBtn15 ctrlShow false;
		_SonyRadioBtn16 ctrlShow false;
		_SonyRadioBtn17 ctrlShow false;
		_SonyRadioBtn21 ctrlShow false;
		_SonyRadioCo1 ctrlShow false;
		_SonyRadioCo2 ctrlShow false;
		_SonyRadioCo3 ctrlShow false;
		_SonyRadioCo4 ctrlShow false;
		_SonyRadioCo5 ctrlShow false;
		_SonyRadioCo6 ctrlShow false;
		_SonyRadioCo7 ctrlShow false;
		_SonyRadioCo8 ctrlShow false;
		_SonyRadioCo9 ctrlShow false;
		_SonyRadioCo10 ctrlShow false;
		_SonyRadioCo11 ctrlShow false;
		_SonyRadioCo12 ctrlShow false;
		_SonyRadioCo13 ctrlShow false;
		_SonyRadioCo14 ctrlShow false;
		_SonyRadioCo15 ctrlShow false;
		_SonyRadioCo16 ctrlShow false;
		_SonyRadioCo17 ctrlShow false;
		_SonyRadioCo21 ctrlShow false;
		_SonyRadioNb1 ctrlShow false;
		_SonyRadioNb2 ctrlShow false;
		_SonyRadioNb3 ctrlShow false;
		_SonyRadioNb4 ctrlShow false;
		_SonyRadioNb5 ctrlShow false;
		_SonyRadioNb6 ctrlShow false;
		_SonyRadioNb7 ctrlShow false;
		_SonyRadioNb8 ctrlShow false;
		_SonyRadioNb9 ctrlShow false;
		_SonyRadioNb10 ctrlShow false;
		_SonyRadioNb11 ctrlShow false;
		_SonyRadioNb12 ctrlShow false;
		_SonyRadioNb13 ctrlShow false;
		_SonyRadioNb14 ctrlShow false;
		_SonyRadioNb15 ctrlShow false;
		_SonyRadioNb16 ctrlShow false;
		_SonyRadioNb17 ctrlShow false;
		_SonyRadioNb21 ctrlShow false;
		_SonyMenuBtnCentral ctrlShow false;
		_SonyReglBtnVolp1 ctrlShow false;
		_SonyReglBtnVolm1 ctrlShow false;
		_SonyContacts ctrlShow false;
		_SonyContactsAdd ctrlShow false;
		_SonyContactsTexte ctrlShow false;
		_SonyContactsList ctrlShow false;
		_SonyFiche ctrlShow false;
		_SonyFicheName ctrlShow false;
		_SonyFicheNum ctrlShow false;
		_SonyFicheBtnSms ctrlShow false;
		_SonyFicheBtnAppel ctrlShow false;
		_SonyFicheBtnDelete ctrlShow false;
		_SonyCentral ctrlShow false;
		_SonyCentralList ctrlShow false;
		_SonyCentralBtnApp ctrlShow false;
		_SonyCentralBtnRaf ctrlShow false;
		_SonyCentralBtnRac ctrlShow false;
		_SonyNewContact ctrlShow false;
		_SonyNewContactAnn ctrlShow false;
		_SonyNewContactAdd ctrlShow false;
		_SonyNewContactName ctrlShow false;
		_SonyNewContactNum ctrlShow false;
		_SonyRecents ctrlShow false;
		_SonyRecentsLb ctrlShow false;
		_SonyRecentsVider ctrlShow false;
		_SonyRecentsApp ctrlShow false;
		_SonyRecentsSms ctrlShow false;
		_SonyReglBtnFg ctrlShow false;
		_SonyReglBtnFm ctrlShow false;
		_SonyReglBtnFd ctrlShow false;
		_SonyReglBtnF2g ctrlShow false;
		_SonyReglBtnF2m ctrlShow false;
		_SonyReglBtnF2d ctrlShow false;
		_SonySms ctrlShow false;
		_SonySmsLb ctrlShow false;
		_SonySmsTexte ctrlShow false;
		_SonySmsBtnRep ctrlShow false;
		_SonySmsBtnSup ctrlShow false;
		_SonySmsBtnNew ctrlShow false;
		_SonyNewSms ctrlShow true;
		_SonyNewSmsNameTexte ctrlShow true;
		_SonyNewSmsNumEdit ctrlShow false;
		_SonyNewSmsSmsEdit ctrlShow true;
		_SonyNewSmsBtnAnn ctrlShow true;
		_SonyNewSmsBtnSend ctrlShow true;
		_SonyAppel ctrlShow false;
		_SonyAppelBtn ctrlShow false;
		_SonyAppelEdit ctrlShow false;
		_SonyAppelRecents ctrlShow false;
		_home ctrlShow true;

		_data = lbData[39144,lbCurSel (39144)];
		_data = call compile _data;
		_number = _data select 0;
		_name = _data select 1;
		pInActNumber = _number;
		_SonyNewSmsNameTexte ctrlSetStructuredText parseText format["<t align='left' shadow='0' color='#000000' font='HelveticaNeueLTStdLt' size='1'>%1</t>", _name];
		_SonyNewSmsBtnAnn buttonSetAction "uiNamespace setVariable ['sonyp',2]; [] call ALF_fnc_menuSonyP;";
		_SonyNewSmsBtnSend buttonSetAction "[pInActNumber] call ALF_fnc_SonyPSendReplySms;";
	};
};

[] spawn {
	if ((isNull ALF_PhoneObject) && !ALF_Phone_inCall && !ALF_Phone_tryCall) then {
		player playActionNow "ALF_LookAt";
		ALF_PhoneObject = "ALF_Iphone_Object" createVehicle [0,0,1000];
		[ALF_PhoneObject,false] remoteExecCall ["enableSimulationGlobal",2];
		uiSleep 0.3;
		if (vehicle player isEqualTo player) then {
			ALF_PhoneObject attachTo [player, [-0.08,0.08,0.05], "RightHandMiddle1"];     
			ALF_PhoneObject setVectorDirAndUp [[0.1, -1.9, -0.8],[-0.25, -0.5, 0.5]];
		};
		
		waitUntil {(isNull findDisplay 38999) || ALF_Phone_inCall || ALF_Phone_tryCall};

		if (!ALF_Phone_inCall && !ALF_Phone_tryCall) then {
			detach ALF_PhoneObject;
			deleteVehicle ALF_PhoneObject;
			ALF_PhoneObject = objNull;
			player playActionNow "gestureNod";
			[{player playActionNow "gestureNod";}] call CBA_fnc_execNextFrame;
		};
	};
};