#include "\ALF_Client\script_macros.hpp"
/*
File: fn_menuiPhone.sqf
Author: ALF Team
Description:
Chargement du menu de l'iPhone.
*/
if (ALF_Teamspeak_Plugin_Enabled || {ALF_Teamspeak_Server_Enabled} || {ALF_Teamspeak_Channel_Enabled}) exitWith {};
if(!dialog) then {
	createDialog "ALF_iPhoneMenu_Dialog";
};
disableSerialization;
private _display = findDisplay 56400;
private _menu1sim = _display displayCtrl 56401;
private _menu1btntel = _display displayCtrl 564011;
private _menu1btnsms = _display displayCtrl 564012;
private _menu1btncontacts = _display displayCtrl 564013;
private _menu1btnreglages = _display displayCtrl 564014;
private _menu1nosim = _display displayCtrl 56402;
private _menu1nosimok = _display displayCtrl 564021;
private _menu1appelentrant = _display displayCtrl 56403;
private _menu1appel = _display displayCtrl 56404;
private _menu1Name = _display displayCtrl 564041;
private _menu1Num = _display displayCtrl 564042;
private _menu1Time = _display displayCtrl 564043;
private _menu1rouge = _display displayCtrl 564044;
private _menu1vert = _display displayCtrl 564045;
private _menu1rouge2 = _display displayCtrl 564046;
private _menu1volp = _display displayCtrl 564048;
private _menu1volm = _display displayCtrl 564049;

private _menu2telephone = _display displayCtrl 56405;
private _menu2btnappel = _display displayCtrl 564051;
private _menu2numedit = _display displayCtrl 564052;

private _menu3contacts = _display displayCtrl 56406;
private _menu3contactslist = _display displayCtrl 564061;
private _menu3Name = _display displayCtrl 564062;
private _menu3Num = _display displayCtrl 564063;
private _menu3btnadd = _display displayCtrl 564064;

private _menu3fiche = _display displayCtrl 56407;
private _menu3fichename = _display displayCtrl 564071;
private _menu3fichenum = _display displayCtrl 564072;
private _menu3fichebtnsms = _display displayCtrl 564073;
private _menu3fichebtnappel = _display displayCtrl 564074;
private _menu3fichebtnsms2 = _display displayCtrl 564075;
private _menu3fichebtnfiche = _display displayCtrl 564076;
private _menu3retour = _display displayCtrl 564077;

private _menu3addcontact = _display displayCtrl 56408;
private _menu3addname = _display displayCtrl 564081;
private _menu3addnum = _display displayCtrl 564082;
private _menu3btnOK = _display displayCtrl 564083;
private _menu3btnannuler = _display displayCtrl 564084;

private _menuALF_Phone_SMS = _display displayCtrl 56409;
private _menuNMbtnannuler = _display displayCtrl 564091;
private _menuNMnumedit = _display displayCtrl 564092;
private _menuNMnum = _display displayCtrl 564093;
private _menuNMsmsedit = _display displayCtrl 564094;
private _menuNMbtnenvoyer = _display displayCtrl 564095;

private _mutepic = _display displayCtrl 564096;
private _mutebtn = _display displayCtrl 564097;
private _speakpic = _display displayCtrl 564098;
private _speakbtn = _display displayCtrl 564099;

private _menu5 = _display displayCtrl 565050;
private _menu5btnAnonyme = _display displayCtrl 565051;
private _menu5viberON = _display displayCtrl 565052;
private _menu5viberOFF = _display displayCtrl 565053;
private _menu5textbg = _display displayCtrl 565054;
private _menu5btnbg = _display displayCtrl 565055;
private _menu5textring = _display displayCtrl 565056;
private _menu5btnring = _display displayCtrl 565057;
private _menu5AnonymeON = _display displayCtrl 565058;
private _menu5AnonymeOFF = _display displayCtrl 565059;
private _menu5btnviber = _display displayCtrl 565060;
private _menu5btnavion = _display displayCtrl 565061;
private _menu5avionON = _display displayCtrl 565063;
private _menu5avionOFF = _display displayCtrl 565062;

private _menuRadiobtnapp = _display displayCtrl 582504;
private _menuRadiopic = _display displayCtrl 58256;
private _menuRadiobtnpic1 = _display displayCtrl 582500;
private _menuRadiobtnpic2 = _display displayCtrl 582501;
private _menuRadiobtn1 = _display displayCtrl 582502;
private _menuRadiobtn2 = _display displayCtrl 582503;
private _menuRadioEdit = _display displayCtrl 582505;
private _menuRadioText = _display displayCtrl 582506;
private _menuRadioVolp = _display displayCtrl 582507;
private _menuRadioVolm = _display displayCtrl 582508;

private _menu6pic = _display displayCtrl 682560;
private _menu6smslist = _display displayCtrl 682561;
private _menu6smsview = _display displayCtrl 682562;
private _menu6btnnew = _display displayCtrl 682563;
private _menu6btnrep = _display displayCtrl 682564;
private _menu6btndel = _display displayCtrl 682565;
private _menu8recent = _display displayCtrl 682566;
private _menu8recentlb = _display displayCtrl 682567;

[] spawn ALF_fnc_setiPhoneDate;

private _menu = uiNamespace getVariable "iphonemenu";
switch (_menu) do {
	case 0 : {
		_menu2telephone ctrlShow false;
		_menu2btnappel ctrlShow false;
		_menu2numedit ctrlShow false;
		_menu3contacts ctrlShow false;
		_menu3contactslist ctrlShow false;
		_menu3Name ctrlShow false;
		_menu3Num ctrlShow false;
		_menu3btnadd ctrlShow false;
		_menu3fiche ctrlShow false;
		_menu3fichename ctrlShow false;
		_menu3fichenum ctrlShow false;
		_menu3fichebtnsms ctrlShow false;
		_menu3fichebtnappel ctrlShow false;
		_menu3fichebtnsms2 ctrlShow false;
		_menu3fichebtnfiche ctrlShow false;
		_menu3retour ctrlShow false;
		_menu3addcontact ctrlShow false;
		_menu3addname ctrlShow false;
		_menu3addnum ctrlShow false;
		_menu3btnOK ctrlShow false;
		_menu3btnannuler ctrlShow false;
		_menuALF_Phone_SMS ctrlShow false;
		_menuNMbtnannuler ctrlShow false;
		_menuNMnumedit ctrlShow false;
		_menuNMnum ctrlShow false;
		_menuNMsmsedit ctrlShow false;
		_menuNMbtnenvoyer ctrlShow false;
		_mutepic ctrlShow false;
		_mutebtn ctrlShow false;
		_speakpic ctrlShow false;
		_speakbtn ctrlShow false;
		_menu5 ctrlShow false;
		_menu5AnonymeON ctrlShow false;
		_menu5AnonymeOFF ctrlShow false;
		_menu5btnAnonyme ctrlShow false;
		_menu5textbg ctrlShow false;
		_menu5btnbg ctrlShow false;
		_menu5textring ctrlShow false;
		_menu5btnring ctrlShow false;
		_menu5viberON ctrlShow false;
		_menu5viberOFF ctrlShow false;
		_menu5btnviber ctrlShow false;
		_menu5btnavion ctrlShow false;
		_menu5avionON ctrlShow false;
		_menu5avionOFF ctrlShow false;
		_menuRadiopic ctrlShow false;
		_menuRadiobtnpic1 ctrlShow false;
		_menuRadiobtnpic2 ctrlShow false;
		_menuRadiobtn1 ctrlShow false;
		_menuRadiobtn2 ctrlShow false;
		_menuRadioEdit ctrlShow false;
		_menuRadioText ctrlShow false;
		_menuRadioVolp ctrlShow false;
		_menuRadioVolm ctrlShow false;
		_menu6pic ctrlShow false;
		_menu6smslist ctrlShow false;
		_menu6smsview ctrlShow false;
		_menu6btnnew ctrlShow false;
		_menu6btnrep ctrlShow false;
		_menu6btndel ctrlShow false;
		_menu8recent ctrlShow false;
		_menu8recentlb ctrlShow false;

		if (ALF_Phone_inCall) then {
			_menuRadiobtnapp ctrlShow false;
			_menu1sim ctrlShow false;
			_menu1btntel ctrlShow false;
			_menu1btnsms ctrlShow false;
			_menu1btncontacts ctrlShow false;
			_menu1btnreglages ctrlShow false;
			_menu1nosim ctrlShow false;
			_menu1nosimok ctrlShow false;
			_menu1appelentrant ctrlShow false;
			_menu1appel ctrlShow true;
			_menu1Name ctrlShow true;
			_menu1Num ctrlShow true;
			_menu1Time ctrlShow true;
			_menu1rouge ctrlShow false;
			_menu1vert ctrlShow false;
			_menu1rouge2 ctrlShow true;
			_menu1volp ctrlShow true;
			_menu1volm ctrlShow true;
			_mutebtn ctrlShow true;
			_speakbtn ctrlShow true;

			private _hisName = "Inconnu";
			private _hisNumber = ALF_Phone_CallNumber;
			private _hisAnonyme = ALF_Phone_CallAnonyme;
			if (count life_contacts > 0) then {
				{
					if ((_x select 1) isEqualTo _hisNumber) exitWith {
						_hisName = _x select 0;
					};
				} forEach life_contacts;
			};
			if(_hisNumber isEqualTo "17") then {_hisName = "Gendarmerie"} else {
			if(_hisNumber isEqualTo "18") then {_hisName = "Pompier"} else {
			if(_hisAnonyme) then {_hisName = "Anonyme"; _hisNumber = "**********"};};};
			_menu1Name ctrlSetStructuredText parseText format["<t align='center' shadow='0' color='#FFFFFF' font='HelveticaNeueLTStdLt' size='1.5'>%1</t>", _hisName];
			_menu1Num ctrlSetStructuredText parseText format["<t align='center' shadow='0' color='#FFFFFF' font='HelveticaNeueLTStdLt' size='1.2'>%1</t>", _hisNumber];
			_menu1volp buttonSetAction "[""UP""] spawn ALF_fnc_iPhoneSetVolume;";
			_menu1volm buttonSetAction "[""DOWN""] spawn ALF_fnc_iPhoneSetVolume;";
			_menu1rouge2 buttonSetAction "[] call ALF_fnc_endCall;";
			if(iPhone_Mute) then {
				_mutepic ctrlShow true;
				_mutebtn buttonSetAction "[] spawn ALF_fnc_iPhoneUnmute;";
			} else {
				_mutepic ctrlShow false;
				_mutebtn buttonSetAction "[] spawn ALF_fnc_iPhoneMute;";
			};
			if(iPhone_Speackers) then {
				_speakpic ctrlShow true;
				_speakbtn buttonSetAction "[] spawn ALF_fnc_iPhoneSpeakers;";
			} else {
				_speakpic ctrlShow false;
				_speakbtn buttonSetAction "[] spawn ALF_fnc_iPhoneSpeakers;";
			};
		} else {
			if (ALF_Phone_Ring) then {
				_menu1sim ctrlShow false;
				_menu1btntel ctrlShow false;
				_menu1btnsms ctrlShow false;
				_menu1btncontacts ctrlShow false;
				_menu1btnreglages ctrlShow false;
				_menu1nosim ctrlShow false;
				_menu1nosimok ctrlShow false;
				_menu1appelentrant ctrlShow true;
				_menu1appel ctrlShow false;
				_menu1Name ctrlShow true;
				_menu1Num ctrlShow true;
				_menu1Time ctrlShow false;
				_menu1rouge ctrlShow true;
				_menu1vert ctrlShow true;
				_menu1rouge2 ctrlShow false;
				_menu1volp ctrlShow false;
				_menu1volm ctrlShow false;
				_menuRadiobtnapp ctrlShow false;

				private _hisName = "Inconnu";
				private _hisNumber = ALF_Phone_CallNumber;
				private _hisAnonyme = ALF_Phone_CallAnonyme;
				if (count life_contacts > 0) then {
					{
						if ((_x select 1) isEqualTo _hisNumber) exitWith {
							_hisName = _x select 0;
						};
					} forEach life_contacts;
				};
				if(_hisAnonyme) then {_hisName = "Anonyme"; _hisNumber = "**********"};
				_menu1Name ctrlSetStructuredText parseText format["<t align='center' shadow='0' color='#FFFFFF' font='HelveticaNeueLTStdLt' size='1.5'>%1</t>", _hisName];
				_menu1Num ctrlSetStructuredText parseText format["<t align='center' shadow='0' color='#FFFFFF' font='HelveticaNeueLTStdLt' size='1.2'>%1</t>", _hisNumber];
				_menu1vert buttonSetAction "player setVariable [""call_info"",2,HC3_Life];";
				_menu1rouge buttonSetAction "[] call ALF_fnc_resetCall;";
			} else {
				if(ALF_Phone_tryCall) then {
					_menu1sim ctrlShow false;
					_menu1btntel ctrlShow false;
					_menu1btnsms ctrlShow false;
					_menu1btncontacts ctrlShow false;
					_menu1btnreglages ctrlShow false;
					_menu1nosim ctrlShow false;
					_menu1nosimok ctrlShow false;
					_menu1appelentrant ctrlShow false;
					_menu1appel ctrlShow true;
					_menu1Name ctrlShow true;
					_menu1Num ctrlShow true;
					_menu1Time ctrlShow false;
					_menu1rouge ctrlShow false;
					_menu1vert ctrlShow false;
					_menu1rouge2 ctrlShow true;
					_menu1volp ctrlShow false;
					_menu1volm ctrlShow false;
					_menuRadiobtnapp ctrlShow false;

					private _hisName = "Inconnu";
					private _hisNumber = ALF_Phone_CallNumber;
					if (count life_contacts > 0) then {
						{
							if ((_x select 1) isEqualTo _hisNumber) exitWith {
								_hisName = _x select 0;
							};
						} forEach life_contacts;
					};
					if(_hisNumber isEqualTo "17") then {_hisName = "Gendarmerie"};
					if(_hisNumber isEqualTo "18") then {_hisName = "Pompier"};
					_menu1Name ctrlSetStructuredText parseText format["<t align='center' shadow='0' color='#FFFFFF' font='HelveticaNeueLTStdLt' size='1.5'>%1</t>", _hisName];
					_menu1Num ctrlSetStructuredText parseText format["<t align='center' shadow='0' color='#FFFFFF' font='HelveticaNeueLTStdLt' size='1.2'>%1</t>", _hisNumber];
					_menu1rouge2 buttonSetAction "[] call ALF_fnc_resetCall;";
				} else {
					[] spawn ALF_fnc_setiPhoneBackGround;
					if(ALF_Forfait isEqualTo -1) then {
						_menu1sim ctrlShow false;
						_menu1btntel ctrlShow false;
						_menu1btnsms ctrlShow false;
						_menu1btncontacts ctrlShow false;
						_menu1btnreglages ctrlShow false;
						_menu1nosim ctrlShow true;
						_menu1nosimok ctrlShow true;
						_menu1appelentrant ctrlShow false;
						_menu1appel ctrlShow false;
						_menu1Name ctrlShow false;
						_menu1Num ctrlShow false;
						_menu1Time ctrlShow false;
						_menu1rouge ctrlShow false;
						_menu1vert ctrlShow false;
						_menu1rouge2 ctrlShow false;
						_menu1volp ctrlShow false;
						_menu1volm ctrlShow false;
						_menuRadiobtnapp ctrlShow false;
					} else {
						_menu1sim ctrlShow true;
						_menu1btntel ctrlShow true;
						_menu1btnsms ctrlShow true;
						_menu1btncontacts ctrlShow true;
						_menu1btnreglages ctrlShow true;
						_menu1nosim ctrlShow false;
						_menu1nosimok ctrlShow false;
						_menu1appelentrant ctrlShow false;
						_menu1appel ctrlShow false;
						_menu1Name ctrlShow false;
						_menu1Num ctrlShow false;
						_menu1Time ctrlShow false;
						_menu1rouge ctrlShow false;
						_menu1vert ctrlShow false;
						_menu1rouge2 ctrlShow false;
						_menu1volp ctrlShow false;
						_menu1volm ctrlShow false;
						_menuRadiobtnapp ctrlShow true;

						_menu1btntel buttonSetAction "uiNamespace setVariable ['iphonemenu',1]; [] call ALF_fnc_menuiPhone;";
						_menu1btnsms buttonSetAction "uiNamespace setVariable ['iphonemenu',6]; [] call ALF_fnc_menuiPhone;";
						_menu1btncontacts buttonSetAction "uiNamespace setVariable ['iphonemenu',2]; [] call ALF_fnc_menuiPhone;";
						_menu1btnreglages buttonSetAction "uiNamespace setVariable ['iphonemenu',5]; [] call ALF_fnc_menuiPhone;";
						_menuRadiobtnapp buttonSetAction "uiNamespace setVariable ['iphonemenu',7]; [] call ALF_fnc_menuiPhone;";
					};
				};
			};
		};
	};
	case 1 : {
		_menu1sim ctrlShow false;
		_menu1btntel ctrlShow false;
		_menu1btnsms ctrlShow false;
		_menu1btncontacts ctrlShow true;
		_menu1btnreglages ctrlShow false;
		_menu1nosim ctrlShow false;
		_menu1nosimok ctrlShow false;
		_menu1appelentrant ctrlShow false;
		_menu1appel ctrlShow false;
		_menu1Name ctrlShow false;
		_menu1Num ctrlShow false;
		_menu1Time ctrlShow false;
		_menu1rouge ctrlShow false;
		_menu1vert ctrlShow false;
		_menu1rouge2 ctrlShow false;
		_menu1volp ctrlShow false;
		_menu1volm ctrlShow false;
		_menu3contacts ctrlShow false;
		_menu3contactslist ctrlShow false;
		_menu3Name ctrlShow false;
		_menu3Num ctrlShow false;
		_menu3btnadd ctrlShow false;
		_menu3fiche ctrlShow false;
		_menu3fichename ctrlShow false;
		_menu3fichenum ctrlShow false;
		_menu3fichebtnsms ctrlShow false;
		_menu3fichebtnappel ctrlShow false;
		_menu3fichebtnsms2 ctrlShow false;
		_menu3fichebtnfiche ctrlShow false;
		_menu3retour ctrlShow false;
		_menu3addcontact ctrlShow false;
		_menu3addname ctrlShow false;
		_menu3addnum ctrlShow false;
		_menu3btnOK ctrlShow false;
		_menu3btnannuler ctrlShow false;
		_menuALF_Phone_SMS ctrlShow false;
		_menuNMbtnannuler ctrlShow false;
		_menuNMnumedit ctrlShow false;
		_menuNMnum ctrlShow false;
		_menuNMsmsedit ctrlShow false;
		_menuNMbtnenvoyer ctrlShow false;
		_mutepic ctrlShow false;
		_mutebtn ctrlShow false;
		_speakpic ctrlShow false;
		_speakbtn ctrlShow false;
		_menu5 ctrlShow false;
		_menu5AnonymeON ctrlShow false;
		_menu5AnonymeOFF ctrlShow false;
		_menu5btnAnonyme ctrlShow false;
		_menu5textbg ctrlShow false;
		_menu5btnbg ctrlShow false;
		_menu5textring ctrlShow false;
		_menu5btnring ctrlShow false;
		_menu5viberON ctrlShow false;
		_menu5viberOFF ctrlShow false;
		_menu5btnviber ctrlShow false;
		_menu5btnavion ctrlShow false;
		_menu5avionON ctrlShow false;
		_menu5avionOFF ctrlShow false;
		_menuRadiobtnapp ctrlShow false;
		_menuRadiopic ctrlShow false;
		_menuRadiobtnpic1 ctrlShow false;
		_menuRadiobtnpic2 ctrlShow false;
		_menuRadiobtn1 ctrlShow false;
		_menuRadiobtn2 ctrlShow false;
		_menuRadioEdit ctrlShow false;
		_menuRadioText ctrlShow false;
		_menuRadioVolp ctrlShow false;
		_menuRadioVolm ctrlShow false;
		_menu6pic ctrlShow false;
		_menu6smslist ctrlShow false;
		_menu6smsview ctrlShow false;
		_menu6btnnew ctrlShow false;
		_menu6btnrep ctrlShow false;
		_menu6btndel ctrlShow false;
		_menu8recent ctrlShow false;
		_menu8recentlb ctrlShow false;

		_menu2telephone ctrlShow true;
		_menu2btnappel ctrlShow true;
		_menu2numedit ctrlShow true;
		_menu2btnappel buttonSetAction "[] spawn ALF_fnc_iPhoneCallCustom;";
		_menu1btncontacts buttonSetAction "uiNamespace setVariable ['iphonemenu',9]; [] call ALF_fnc_menuiPhone;";
	};
	case 2 : {
		_menu1sim ctrlShow false;
		_menu1btntel ctrlShow false;
		_menu1btnsms ctrlShow false;
		_menu1btncontacts ctrlShow false;
		_menu1btnreglages ctrlShow false;
		_menu1nosim ctrlShow false;
		_menu1nosimok ctrlShow false;
		_menu1appelentrant ctrlShow false;
		_menu1appel ctrlShow false;
		_menu1Name ctrlShow false;
		_menu1Num ctrlShow false;
		_menu1Time ctrlShow false;
		_menu1rouge ctrlShow false;
		_menu1vert ctrlShow false;
		_menu1rouge2 ctrlShow false;
		_menu1volp ctrlShow false;
		_menu1volm ctrlShow false;
		_menuALF_Phone_SMS ctrlShow false;
		_menuNMbtnannuler ctrlShow false;
		_menuNMnumedit ctrlShow false;
		_menuNMnum ctrlShow false;
		_menuNMsmsedit ctrlShow false;
		_menuNMbtnenvoyer ctrlShow false;
		_menu2telephone ctrlShow false;
		_menu2btnappel ctrlShow false;
		_menu2numedit ctrlShow false;
		_menu3fiche ctrlShow false;
		_menu3fichename ctrlShow false;
		_menu3fichenum ctrlShow false;
		_menu3fichebtnsms ctrlShow false;
		_menu3fichebtnappel ctrlShow false;
		_menu3fichebtnsms2 ctrlShow false;
		_menu3fichebtnfiche ctrlShow false;
		_menu3retour ctrlShow false;
		_menu3addcontact ctrlShow false;
		_menu3addname ctrlShow false;
		_menu3addnum ctrlShow false;
		_menu3btnOK ctrlShow false;
		_menu3btnannuler ctrlShow false;
		_mutepic ctrlShow false;
		_mutebtn ctrlShow false;
		_speakpic ctrlShow false;
		_speakbtn ctrlShow false;
		_menu5 ctrlShow false;
		_menu5AnonymeON ctrlShow false;
		_menu5AnonymeOFF ctrlShow false;
		_menu5btnAnonyme ctrlShow false;
		_menu5textbg ctrlShow false;
		_menu5btnbg ctrlShow false;
		_menu5textring ctrlShow false;
		_menu5btnring ctrlShow false;
		_menu5viberON ctrlShow false;
		_menu5viberOFF ctrlShow false;
		_menu5btnviber ctrlShow false;
		_menu5btnavion ctrlShow false;
		_menu5avionON ctrlShow false;
		_menu5avionOFF ctrlShow false;
		_menuRadiobtnapp ctrlShow false;
		_menuRadiopic ctrlShow false;
		_menuRadiobtnpic1 ctrlShow false;
		_menuRadiobtnpic2 ctrlShow false;
		_menuRadiobtn1 ctrlShow false;
		_menuRadiobtn2 ctrlShow false;
		_menuRadioEdit ctrlShow false;
		_menuRadioText ctrlShow false;
		_menuRadioVolp ctrlShow false;
		_menuRadioVolm ctrlShow false;
		_menu6pic ctrlShow false;
		_menu6smslist ctrlShow false;
		_menu6smsview ctrlShow false;
		_menu6btnnew ctrlShow false;
		_menu6btnrep ctrlShow false;
		_menu6btndel ctrlShow false;
		_menu8recent ctrlShow false;
		_menu8recentlb ctrlShow false;

		_menu3contacts ctrlShow true;
		_menu3contactslist ctrlShow true;
		_menu3Name ctrlShow true;
		_menu3Num ctrlShow true;
		_menu3btnadd ctrlShow true;

		lbClear _menu3contactslist;
		if (count life_contacts > 0) then {
			{
				private _name = _x select 0;
				_menu3contactslist lbAdd format["%1",_name];
				_menu3contactslist lbSetData [(lbSize _menu3contactslist)-1,str(_x)];
				_menu3contactslist lbSetValue [(lbSize _menu3contactslist)-1,_forEachIndex];
			} forEach life_contacts;
			lbSort _menu3contactslist;
		};

		_menu3contactslist ctrlSetEventHandler ["LBDblClick", "uiNamespace setVariable ['iphonemenu',4]; [] call ALF_fnc_menuiPhone"];
		_menu3btnadd buttonSetAction "uiNamespace setVariable ['iphonemenu',3]; [] call ALF_fnc_menuiPhone;";

		private _myName = name player;
		private _myNumber = ALF_Phone_Number;
		_menu3Name ctrlSetStructuredText parseText format["<t align='left' shadow='0' color='#000000' font='HelveticaNeueLTStdLt' size='1.2'>%1</t>", _myName];
		_menu3Num ctrlSetStructuredText parseText format["<t align='left' shadow='0' color='#000000' font='HelveticaNeueLTStdLt' size='1'>%1</t>", _myNumber];

	};
	case 3 : {
		_menu1sim ctrlShow false;
		_menu1btntel ctrlShow false;
		_menu1btnsms ctrlShow false;
		_menu1btncontacts ctrlShow false;
		_menu1btnreglages ctrlShow false;
		_menu1nosim ctrlShow false;
		_menu1nosimok ctrlShow false;
		_menu1appelentrant ctrlShow false;
		_menu1appel ctrlShow false;
		_menu1Name ctrlShow false;
		_menu1Num ctrlShow false;
		_menu1Time ctrlShow false;
		_menu1rouge ctrlShow false;
		_menu1vert ctrlShow false;
		_menu1rouge2 ctrlShow false;
		_menu1volp ctrlShow false;
		_menu1volm ctrlShow false;
		_menuALF_Phone_SMS ctrlShow false;
		_menuNMbtnannuler ctrlShow false;
		_menuNMnumedit ctrlShow false;
		_menuNMnum ctrlShow false;
		_menuNMsmsedit ctrlShow false;
		_menuNMbtnenvoyer ctrlShow false;
		_menu2telephone ctrlShow false;
		_menu2btnappel ctrlShow false;
		_menu2numedit ctrlShow false;
		_menu3fiche ctrlShow false;
		_menu3fichename ctrlShow false;
		_menu3fichenum ctrlShow false;
		_menu3fichebtnsms ctrlShow false;
		_menu3fichebtnappel ctrlShow false;
		_menu3fichebtnsms2 ctrlShow false;
		_menu3fichebtnfiche ctrlShow false;
		_menu3retour ctrlShow false;
		_menu3contacts ctrlShow false;
		_menu3contactslist ctrlShow false;
		_menu3Name ctrlShow false;
		_menu3Num ctrlShow false;
		_menu3btnadd ctrlShow false;
		_mutepic ctrlShow false;
		_mutebtn ctrlShow false;
		_speakpic ctrlShow false;
		_speakbtn ctrlShow false;
		_menu5 ctrlShow false;
		_menu5AnonymeON ctrlShow false;
		_menu5AnonymeOFF ctrlShow false;
		_menu5btnAnonyme ctrlShow false;
		_menu5textbg ctrlShow false;
		_menu5btnbg ctrlShow false;
		_menu5textring ctrlShow false;
		_menu5btnring ctrlShow false;
		_menu5viberON ctrlShow false;
		_menu5viberOFF ctrlShow false;
		_menu5btnviber ctrlShow false;
		_menu5btnavion ctrlShow false;
		_menu5avionON ctrlShow false;
		_menu5avionOFF ctrlShow false;
		_menuRadiobtnapp ctrlShow false;
		_menuRadiopic ctrlShow false;
		_menuRadiobtnpic1 ctrlShow false;
		_menuRadiobtnpic2 ctrlShow false;
		_menuRadiobtn1 ctrlShow false;
		_menuRadiobtn2 ctrlShow false;
		_menuRadioEdit ctrlShow false;
		_menuRadioText ctrlShow false;
		_menuRadioVolp ctrlShow false;
		_menuRadioVolm ctrlShow false;
		_menu6pic ctrlShow false;
		_menu6smslist ctrlShow false;
		_menu6smsview ctrlShow false;
		_menu6btnnew ctrlShow false;
		_menu6btnrep ctrlShow false;
		_menu6btndel ctrlShow false;
		_menu8recent ctrlShow false;
		_menu8recentlb ctrlShow false;

		_menu3addcontact ctrlShow true;
		_menu3addname ctrlShow true;
		_menu3addnum ctrlShow true;
		_menu3btnOK ctrlShow true;
		_menu3btnannuler ctrlShow true;
		_menu3btnOK buttonSetAction "[] spawn ALF_fnc_iPhoneAddContact;";
		_menu3btnannuler buttonSetAction "uiNamespace setVariable ['iphonemenu',2]; [] call ALF_fnc_menuiPhone;";
	};
	case 4 : {
		_menu1sim ctrlShow false;
		_menu1btntel ctrlShow false;
		_menu1btnsms ctrlShow false;
		_menu1btncontacts ctrlShow false;
		_menu1btnreglages ctrlShow false;
		_menu1nosim ctrlShow false;
		_menu1nosimok ctrlShow false;
		_menu1appelentrant ctrlShow false;
		_menu1appel ctrlShow false;
		_menu1Name ctrlShow false;
		_menu1Num ctrlShow false;
		_menu1Time ctrlShow false;
		_menu1rouge ctrlShow false;
		_menu1vert ctrlShow false;
		_menu1rouge2 ctrlShow false;
		_menu1volp ctrlShow false;
		_menu1volm ctrlShow false;
		_menuALF_Phone_SMS ctrlShow false;
		_menuNMbtnannuler ctrlShow false;
		_menuNMnumedit ctrlShow false;
		_menuNMnum ctrlShow false;
		_menuNMsmsedit ctrlShow false;
		_menuNMbtnenvoyer ctrlShow false;
		_menu2telephone ctrlShow false;
		_menu2btnappel ctrlShow false;
		_menu2numedit ctrlShow false;
		_menu3contacts ctrlShow false;
		_menu3contactslist ctrlShow false;
		_menu3Name ctrlShow false;
		_menu3Num ctrlShow false;
		_menu3btnadd ctrlShow false;
		_menu3addcontact ctrlShow false;
		_menu3addname ctrlShow false;
		_menu3addnum ctrlShow false;
		_menu3btnOK ctrlShow false;
		_menu3btnannuler ctrlShow false;
		_mutepic ctrlShow false;
		_mutebtn ctrlShow false;
		_speakpic ctrlShow false;
		_speakbtn ctrlShow false;
		_menu3fiche ctrlShow true;
		_menu3fichename ctrlShow true;
		_menu3fichenum ctrlShow true;
		_menu3fichebtnsms ctrlShow true;
		_menu3fichebtnappel ctrlShow true;
		_menu3fichebtnsms2 ctrlShow true;
		_menu3fichebtnfiche ctrlShow true;
		_menu3retour ctrlShow true;
		_menu5 ctrlShow false;
		_menu5AnonymeON ctrlShow false;
		_menu5AnonymeOFF ctrlShow false;
		_menu5btnAnonyme ctrlShow false;
		_menu5textbg ctrlShow false;
		_menu5btnbg ctrlShow false;
		_menu5textring ctrlShow false;
		_menu5btnring ctrlShow false;
		_menu5viberON ctrlShow false;
		_menu5viberOFF ctrlShow false;
		_menu5btnviber ctrlShow false;
		_menu5btnavion ctrlShow false;
		_menu5avionON ctrlShow false;
		_menu5avionOFF ctrlShow false;
		_menuRadiobtnapp ctrlShow false;
		_menuRadiopic ctrlShow false;
		_menuRadiobtnpic1 ctrlShow false;
		_menuRadiobtnpic2 ctrlShow false;
		_menuRadiobtn1 ctrlShow false;
		_menuRadiobtn2 ctrlShow false;
		_menuRadioEdit ctrlShow false;
		_menuRadioText ctrlShow false;
		_menuRadioVolp ctrlShow false;
		_menuRadioVolm ctrlShow false;
		_menu6pic ctrlShow false;
		_menu6smslist ctrlShow false;
		_menu6smsview ctrlShow false;
		_menu6btnnew ctrlShow false;
		_menu6btnrep ctrlShow false;
		_menu6btndel ctrlShow false;
		_menu8recent ctrlShow false;
		_menu8recentlb ctrlShow false;

		private _cible = lbData[564061,lbCurSel (564061)];
		_cible = call compile format["%1", _cible];
		pInActContact = lbValue [564061, lbCurSel (564061)];

		_menu3fichename ctrlSetStructuredText parseText format["<t align='left' shadow='0' color='#000000' font='HelveticaNeueLTStdLt' size='1.5'>%1</t>", _cible select 0];
		_menu3fichenum ctrlSetStructuredText parseText format["<t align='left' shadow='0' color='#000000' font='HelveticaNeueLTStdLt' size='1'>%1</t>", _cible select 1];
		_menu3fichebtnsms buttonSetAction "[] spawn ALF_fnc_iPhoneSmsContact;";
		_menu3fichebtnsms2 buttonSetAction "[] spawn ALF_fnc_iPhoneSmsContact;";

		_menu3fichebtnfiche buttonSetAction "[pInActContact] spawn ALF_fnc_iPhonedeleteContact;";

		_menu3fichebtnappel buttonSetAction "[] spawn ALF_fnc_iPhoneCallContact;";
		_menu3retour buttonSetAction "uiNamespace setVariable ['iphonemenu',2]; [] call ALF_fnc_menuiPhone;";
	};

	case 5 : {
		_menu1sim ctrlShow false;
		_menu1btntel ctrlShow false;
		_menu1btnsms ctrlShow false;
		_menu1btncontacts ctrlShow false;
		_menu1btnreglages ctrlShow false;
		_menu1nosim ctrlShow false;
		_menu1nosimok ctrlShow false;
		_menu1appelentrant ctrlShow false;
		_menu1appel ctrlShow false;
		_menu1Name ctrlShow false;
		_menu1Num ctrlShow false;
		_menu1Time ctrlShow false;
		_menu1rouge ctrlShow false;
		_menu1vert ctrlShow false;
		_menu1rouge2 ctrlShow false;
		_menu1volp ctrlShow false;
		_menu1volm ctrlShow false;
		_menuALF_Phone_SMS ctrlShow false;
		_menuNMbtnannuler ctrlShow false;
		_menuNMnumedit ctrlShow false;
		_menuNMnum ctrlShow false;
		_menuNMsmsedit ctrlShow false;
		_menuNMbtnenvoyer ctrlShow false;
		_menu2telephone ctrlShow false;
		_menu2btnappel ctrlShow false;
		_menu2numedit ctrlShow false;
		_menu3contacts ctrlShow false;
		_menu3contactslist ctrlShow false;
		_menu3Name ctrlShow false;
		_menu3Num ctrlShow false;
		_menu3btnadd ctrlShow false;
		_menu3addcontact ctrlShow false;
		_menu3addname ctrlShow false;
		_menu3addnum ctrlShow false;
		_menu3btnOK ctrlShow false;
		_menu3btnannuler ctrlShow false;
		_mutepic ctrlShow false;
		_mutebtn ctrlShow false;
		_speakpic ctrlShow false;
		_speakbtn ctrlShow false;
		_menu3fiche ctrlShow false;
		_menu3fichename ctrlShow false;
		_menu3fichenum ctrlShow false;
		_menu3fichebtnsms ctrlShow false;
		_menu3fichebtnappel ctrlShow false;
		_menu3fichebtnsms2 ctrlShow false;
		_menu3fichebtnfiche ctrlShow false;
		_menu3retour ctrlShow false;
		_menuRadiobtnapp ctrlShow false;
		_menuRadiopic ctrlShow false;
		_menuRadiobtnpic1 ctrlShow false;
		_menuRadiobtnpic2 ctrlShow false;
		_menuRadiobtn1 ctrlShow false;
		_menuRadiobtn2 ctrlShow false;
		_menuRadioEdit ctrlShow false;
		_menuRadioText ctrlShow false;
		_menuRadioVolp ctrlShow false;
		_menuRadioVolm ctrlShow false;
		_menu8recent ctrlShow false;
		_menu8recentlb ctrlShow false;

		_menu5 ctrlShow true;
		_menu5btnAnonyme ctrlShow true;
		_menu5textbg ctrlShow true;
		_menu5btnbg ctrlShow true;
		_menu5textring ctrlShow true;
		_menu5btnring ctrlShow true;
		_menu5viberON ctrlShow true;
		_menu5viberOFF ctrlShow true;
		_menu5btnviber ctrlShow true;
		_menu5btnavion ctrlShow true;
		_menu6pic ctrlShow false;
		_menu6smslist ctrlShow false;
		_menu6smsview ctrlShow false;
		_menu6btnnew ctrlShow false;
		_menu6btnrep ctrlShow false;
		_menu6btndel ctrlShow false;

		private _text = "";
		if (ALF_Phone_Anonyme) then {_menu5AnonymeON ctrlShow true; _menu5AnonymeOFF ctrlShow false;} else {_menu5AnonymeON ctrlShow false; _menu5AnonymeOFF ctrlShow true;};
		_menu5btnAnonyme buttonSetAction "[] spawn ALF_fnc_setiPhoneAnonyme;";
		switch (profileNamespace getVariable ["iPhone_Background",0]) do {case 0 : {_text = "ALF";};case 1 : {_text = "Nuit 1";};case 2 : {_text = "Nuit 2";};case 3 : {_text = "Blup Blup";};case 4 : {_text = "Grahouuu";};};
		_menu5textbg ctrlSetStructuredText parseText format["<t align='left' shadow='0' color='#005689' font='HelveticaNeueLTStdLt' size='1'>%1</t>",_text];
		_menu5btnbg buttonSetAction "[] spawn ALF_fnc_setiPhoneBackGround2;";
		switch (profileNamespace getVariable ["iPhone_Ring",0]) do {case 0 : {_text = "Standard";};case 1 : {_text = "Minions";};case 2 : {_text = "Oklm";};};
		_menu5textring ctrlSetStructuredText parseText format["<t align='left' shadow='0' color='#005689' font='HelveticaNeueLTStdLt' size='1'>%1</t>",_text];
		_menu5btnring buttonSetAction "[] spawn ALF_fnc_setiPhoneRing;";
		if (ALF_Phone_Mute) then {_menu5viberON ctrlShow true; _menu5viberOFF ctrlShow false;} else {_menu5viberON ctrlShow false; _menu5viberOFF ctrlShow true;};
		_menu5btnviber buttonSetAction "[] spawn ALF_fnc_setiPhoneViber;";
		if (ALF_Phone_Avion) then {_menu5avionON ctrlShow true; _menu5avionOFF ctrlShow false;} else {_menu5avionON ctrlShow false; _menu5avionOFF ctrlShow true;};
		_menu5btnavion buttonSetAction "if(ALF_Phone_Avion)then{ALF_Phone_Avion=false;}else{ALF_Phone_Avion=true;};  [] call ALF_fnc_menuiPhone;";
	};

	case 6 : {
		_menu1sim ctrlShow false;
		_menu1btntel ctrlShow false;
		_menu1btnsms ctrlShow false;
		_menu1btncontacts ctrlShow false;
		_menu1btnreglages ctrlShow false;
		_menu1nosim ctrlShow false;
		_menu1nosimok ctrlShow false;
		_menu1appelentrant ctrlShow false;
		_menu1appel ctrlShow false;
		_menu1Name ctrlShow false;
		_menu1Num ctrlShow false;
		_menu1Time ctrlShow false;
		_menu1rouge ctrlShow false;
		_menu1vert ctrlShow false;
		_menu1rouge2 ctrlShow false;
		_menu1volp ctrlShow false;
		_menu1volm ctrlShow false;
		_menuALF_Phone_SMS ctrlShow false;
		_menuNMbtnannuler ctrlShow false;
		_menuNMnumedit ctrlShow false;
		_menuNMnum ctrlShow false;
		_menuNMsmsedit ctrlShow false;
		_menuNMbtnenvoyer ctrlShow false;
		_menu2telephone ctrlShow false;
		_menu2btnappel ctrlShow false;
		_menu2numedit ctrlShow false;
		_menu3contacts ctrlShow false;
		_menu3contactslist ctrlShow false;
		_menu3Name ctrlShow false;
		_menu3Num ctrlShow false;
		_menu3btnadd ctrlShow false;
		_menu3addcontact ctrlShow false;
		_menu3addname ctrlShow false;
		_menu3addnum ctrlShow false;
		_menu3btnOK ctrlShow false;
		_menu3btnannuler ctrlShow false;
		_mutepic ctrlShow false;
		_mutebtn ctrlShow false;
		_speakpic ctrlShow false;
		_speakbtn ctrlShow false;
		_menu3fiche ctrlShow false;
		_menu3fichename ctrlShow false;
		_menu3fichenum ctrlShow false;
		_menu3fichebtnsms ctrlShow false;
		_menu3fichebtnappel ctrlShow false;
		_menu3fichebtnsms2 ctrlShow false;
		_menu3fichebtnfiche ctrlShow false;
		_menu3retour ctrlShow false;
		_menu5 ctrlShow false;
		_menu5btnAnonyme ctrlShow false;
		_menu5textbg ctrlShow false;
		_menu5btnbg ctrlShow false;
		_menu5textring ctrlShow false;
		_menu5btnring ctrlShow false;
		_menu5viberON ctrlShow false;
		_menu5viberOFF ctrlShow false;
		_menu5btnviber ctrlShow false;
		_menu5btnavion ctrlShow false;
		_menu5avionON ctrlShow false;
		_menu5avionOFF ctrlShow false;
		_menuRadiobtnapp ctrlShow false;
		_menuRadiopic ctrlShow false;
		_menuRadiobtnpic1 ctrlShow false;
		_menuRadiobtnpic2 ctrlShow false;
		_menuRadiobtn1 ctrlShow false;
		_menuRadiobtn2 ctrlShow false;
		_menuRadioEdit ctrlShow false;
		_menuRadioText ctrlShow false;
		_menuRadioVolp ctrlShow false;
		_menuRadioVolm ctrlShow false;
		_menu8recent ctrlShow false;
		_menu8recentlb ctrlShow false;

		_menu6pic ctrlShow true;
		_menu6smslist ctrlShow true;
		_menu6smsview ctrlShow true;
		_menu6btnnew ctrlShow true;
		_menu6btnrep ctrlShow false;
		_menu6btndel ctrlShow false;

		[ALF_Phone_Number,player] remoteExecCall ["HC_fnc_loadSmsiPhone",HC3_Life];
		ALF_Phone_SMS = false;
		_menu6btnnew buttonSetAction "uiNamespace setVariable ['iphonemenu',8]; [] call ALF_fnc_menuiPhone;";
	};

	case 7 : {
		_menu1sim ctrlShow false;
		_menu1btntel ctrlShow false;
		_menu1btnsms ctrlShow false;
		_menu1btncontacts ctrlShow false;
		_menu1btnreglages ctrlShow false;
		_menu1nosim ctrlShow false;
		_menu1nosimok ctrlShow false;
		_menu1appelentrant ctrlShow false;
		_menu1appel ctrlShow false;
		_menu1Name ctrlShow false;
		_menu1Num ctrlShow false;
		_menu1Time ctrlShow false;
		_menu1rouge ctrlShow false;
		_menu1vert ctrlShow false;
		_menu1rouge2 ctrlShow false;
		_menu1volp ctrlShow false;
		_menu1volm ctrlShow false;
		_menuALF_Phone_SMS ctrlShow false;
		_menuNMbtnannuler ctrlShow false;
		_menuNMnumedit ctrlShow false;
		_menuNMnum ctrlShow false;
		_menuNMsmsedit ctrlShow false;
		_menuNMbtnenvoyer ctrlShow false;
		_menu2telephone ctrlShow false;
		_menu2btnappel ctrlShow false;
		_menu2numedit ctrlShow false;
		_menu3contacts ctrlShow false;
		_menu3contactslist ctrlShow false;
		_menu3Name ctrlShow false;
		_menu3Num ctrlShow false;
		_menu3btnadd ctrlShow false;
		_menu3addcontact ctrlShow false;
		_menu3addname ctrlShow false;
		_menu3addnum ctrlShow false;
		_menu3btnOK ctrlShow false;
		_menu3btnannuler ctrlShow false;
		_mutepic ctrlShow false;
		_mutebtn ctrlShow false;
		_speakpic ctrlShow false;
		_speakbtn ctrlShow false;
		_menu3fiche ctrlShow false;
		_menu3fichename ctrlShow false;
		_menu3fichenum ctrlShow false;
		_menu3fichebtnsms ctrlShow false;
		_menu3fichebtnappel ctrlShow false;
		_menu3fichebtnsms2 ctrlShow false;
		_menu3fichebtnfiche ctrlShow false;
		_menu3retour ctrlShow false;
		_menu5 ctrlShow false;
		_menu5btnAnonyme ctrlShow false;
		_menu5textbg ctrlShow false;
		_menu5btnbg ctrlShow false;
		_menu5textring ctrlShow false;
		_menu5btnring ctrlShow false;
		_menu5viberON ctrlShow false;
		_menu5viberOFF ctrlShow false;
		_menu5btnviber ctrlShow false;
		_menu5btnavion ctrlShow false;
		_menu5avionON ctrlShow false;
		_menu5avionOFF ctrlShow false;
		_menu6pic ctrlShow false;
		_menu6smslist ctrlShow false;
		_menu6smsview ctrlShow false;
		_menu6btnnew ctrlShow false;
		_menu6btnrep ctrlShow false;
		_menu6btndel ctrlShow false;
		_menuRadiobtnapp ctrlShow false;
		_menu8recent ctrlShow false;
		_menu8recentlb ctrlShow false;

		if(!life_radio_connected) then {
			_menuRadiobtnpic1 ctrlShow false;
			_menuRadiobtnpic2 ctrlShow true;
			_menuRadiobtn1 ctrlShow true;
			_menuRadiobtn2 ctrlShow false;
			_menuRadioText ctrlShow true;
			_menuRadioEdit ctrlShow true;
			_menuRadioText ctrlSetStructuredText parseText format["<t align='left' shadow='0' color='#FF0000' font='HelveticaNeueLTStdLt' size='1'>Disconnected</t>"];
			_menuRadioVolp ctrlShow false;
			_menuRadioVolm ctrlShow false;
			_menuRadiobtn1 buttonSetAction "[] spawn ALF_fnc_iPhoneRadioConnect;";
		} else {
			_menuRadiobtnpic1 ctrlShow true;
			_menuRadiobtnpic2 ctrlShow false;
			_menuRadiobtn1 ctrlShow false;
			_menuRadiobtn2 ctrlShow true;
			_menuRadioText ctrlShow true;
			_menuRadioVolp ctrlShow true;
			_menuRadioVolm ctrlShow true;
			_menuRadioEdit ctrlShow false;
			private _freq = player getVariable ["iPhoneRadioFreq",0];
			_menuRadioText ctrlSetStructuredText parseText format["<t align='left' shadow='0' color='#00FF00' font='HelveticaNeueLTStdLt' size='0.8'>Connected: %1Mhz</t>",_freq];
			_menuRadioVolp buttonSetAction "[""UP""] call ALF_fnc_iPhoneSetVolume;";
			_menuRadioVolm buttonSetAction "[""DOWN""] call ALF_fnc_iPhoneSetVolume;";
			_menuRadiobtn2 buttonSetAction "[call TFAR_fnc_activeSwRadio] call ALF_fnc_iPhoneRadioDisconnect; uiNamespace setVariable ['iphonemenu',7]; [] call ALF_fnc_menuiPhone;";
		};
		_menuRadiopic ctrlShow true;
	};

	case 8 : {
		_menu1sim ctrlShow false;
		_menu1btntel ctrlShow false;
		_menu1btnsms ctrlShow false;
		_menu1btncontacts ctrlShow false;
		_menu1btnreglages ctrlShow false;
		_menu1nosim ctrlShow false;
		_menu1nosimok ctrlShow false;
		_menu1appelentrant ctrlShow false;
		_menu1appel ctrlShow false;
		_menu1Name ctrlShow false;
		_menu1Num ctrlShow false;
		_menu1Time ctrlShow false;
		_menu1rouge ctrlShow false;
		_menu1vert ctrlShow false;
		_menu1rouge2 ctrlShow false;
		_menu1volp ctrlShow false;
		_menu1volm ctrlShow false;
		_menuALF_Phone_SMS ctrlShow true;
		_menuNMbtnannuler ctrlShow true;
		_menuNMnumedit ctrlShow true;
		_menuNMnum ctrlShow false;
		_menuNMsmsedit ctrlShow true;
		_menuNMbtnenvoyer ctrlShow true;
		_menu2telephone ctrlShow false;
		_menu2btnappel ctrlShow false;
		_menu2numedit ctrlShow false;
		_menu3contacts ctrlShow false;
		_menu3contactslist ctrlShow false;
		_menu3Name ctrlShow false;
		_menu3Num ctrlShow false;
		_menu3btnadd ctrlShow false;
		_menu3addcontact ctrlShow false;
		_menu3addname ctrlShow false;
		_menu3addnum ctrlShow false;
		_menu3btnOK ctrlShow false;
		_menu3btnannuler ctrlShow false;
		_mutepic ctrlShow false;
		_mutebtn ctrlShow false;
		_speakpic ctrlShow false;
		_speakbtn ctrlShow false;
		_menu3fiche ctrlShow false;
		_menu3fichename ctrlShow false;
		_menu3fichenum ctrlShow false;
		_menu3fichebtnsms ctrlShow false;
		_menu3fichebtnappel ctrlShow false;
		_menu3fichebtnsms2 ctrlShow false;
		_menu3fichebtnfiche ctrlShow false;
		_menu3retour ctrlShow false;
		_menu5 ctrlShow false;
		_menu5btnAnonyme ctrlShow false;
		_menu5textbg ctrlShow false;
		_menu5btnbg ctrlShow false;
		_menu5textring ctrlShow false;
		_menu5btnring ctrlShow false;
		_menu5viberON ctrlShow false;
		_menu5viberOFF ctrlShow false;
		_menu5btnviber ctrlShow false;
		_menu5btnavion ctrlShow false;
		_menu5avionON ctrlShow false;
		_menu5avionOFF ctrlShow false;
		_menuRadiobtnapp ctrlShow false;
		_menuRadiopic ctrlShow false;
		_menuRadiobtnpic1 ctrlShow false;
		_menuRadiobtnpic2 ctrlShow false;
		_menuRadiobtn1 ctrlShow false;
		_menuRadiobtn2 ctrlShow false;
		_menuRadioEdit ctrlShow false;
		_menuRadioText ctrlShow false;
		_menuRadioVolp ctrlShow false;
		_menuRadioVolm ctrlShow false;
		_menu6pic ctrlShow false;
		_menu6smslist ctrlShow false;
		_menu6smsview ctrlShow false;
		_menu6btnnew ctrlShow false;
		_menu6btnrep ctrlShow false;
		_menu6btndel ctrlShow false;
		_menu8recent ctrlShow false;
		_menu8recentlb ctrlShow false;

		_menuNMbtnannuler buttonSetAction "uiNamespace setVariable ['iphonemenu',6]; [] call ALF_fnc_menuiPhone;";
		_menuNMbtnenvoyer buttonSetAction "[] call ALF_fnc_iPhoneNewSmsSend;";
		};

	case 9 : {
		_menu1sim ctrlShow false;
		_menu1btntel ctrlShow false;
		_menu1btnsms ctrlShow false;
		_menu1btncontacts ctrlShow false;
		_menu1btnreglages ctrlShow false;
		_menu1nosim ctrlShow false;
		_menu1nosimok ctrlShow false;
		_menu1appelentrant ctrlShow false;
		_menu1appel ctrlShow false;
		_menu1Name ctrlShow false;
		_menu1Num ctrlShow false;
		_menu1Time ctrlShow false;
		_menu1rouge ctrlShow false;
		_menu1vert ctrlShow false;
		_menu1rouge2 ctrlShow false;
		_menu1volp ctrlShow false;
		_menu1volm ctrlShow false;
		_menuALF_Phone_SMS ctrlShow false;
		_menuNMbtnannuler ctrlShow false;
		_menuNMnumedit ctrlShow false;
		_menuNMnum ctrlShow false;
		_menuNMsmsedit ctrlShow false;
		_menuNMbtnenvoyer ctrlShow false;
		_menu2telephone ctrlShow false;
		_menu2btnappel ctrlShow false;
		_menu2numedit ctrlShow false;
		_menu3contacts ctrlShow false;
		_menu3contactslist ctrlShow false;
		_menu3Name ctrlShow false;
		_menu3Num ctrlShow false;
		_menu3btnadd ctrlShow false;
		_menu3addcontact ctrlShow false;
		_menu3addname ctrlShow false;
		_menu3addnum ctrlShow false;
		_menu3btnOK ctrlShow false;
		_menu3btnannuler ctrlShow false;
		_mutepic ctrlShow false;
		_mutebtn ctrlShow false;
		_speakpic ctrlShow false;
		_speakbtn ctrlShow false;
		_menu3fiche ctrlShow false;
		_menu3fichename ctrlShow false;
		_menu3fichenum ctrlShow false;
		_menu3fichebtnsms ctrlShow false;
		_menu3fichebtnappel ctrlShow false;
		_menu3fichebtnsms2 ctrlShow false;
		_menu3fichebtnfiche ctrlShow false;
		_menu3retour ctrlShow false;
		_menu5 ctrlShow false;
		_menu5btnAnonyme ctrlShow false;
		_menu5textbg ctrlShow false;
		_menu5btnbg ctrlShow false;
		_menu5textring ctrlShow false;
		_menu5btnring ctrlShow false;
		_menu5viberON ctrlShow false;
		_menu5viberOFF ctrlShow false;
		_menu5btnviber ctrlShow false;
		_menu5btnavion ctrlShow false;
		_menu5avionON ctrlShow false;
		_menu5avionOFF ctrlShow false;
		_menuRadiobtnapp ctrlShow false;
		_menuRadiopic ctrlShow false;
		_menuRadiobtnpic1 ctrlShow false;
		_menuRadiobtnpic2 ctrlShow false;
		_menuRadiobtn1 ctrlShow false;
		_menuRadiobtn2 ctrlShow false;
		_menuRadioEdit ctrlShow false;
		_menuRadioText ctrlShow false;
		_menuRadioVolp ctrlShow false;
		_menuRadioVolm ctrlShow false;
		_menu6pic ctrlShow false;
		_menu6smslist ctrlShow false;
		_menu6smsview ctrlShow false;

		_menu6btnnew ctrlShow true;
		_menu6btnrep ctrlShow true;
		_menu6btndel ctrlShow true;
		_menu8recent ctrlShow true;
		_menu8recentlb ctrlShow true;

		lbClear _menu8recentlb;
		if (count ALF_Phone_Historique > 0) then {
			{
				private _time = _x select 0;
				private _anonyme = _x select 1;
				private _type = _x select 2;
				private _number = _x select 3;
				private _hisName = "Inconnu";
				if(_anonyme) then {_hisName = "Anonyme"; _number = "**********"};
				if (count life_contacts > 0) then {
					{
						if ((_x select 1) isEqualTo _number) exitWith {
							_hisName = _x select 0;
						};
					} forEach life_contacts;
				};
				if(_number isEqualTo "17") then {_hisName = "Gendarmerie"};
				if(_number isEqualTo "18") then {_hisName = "Pompier"};
				_menu8recentlb lbAdd format["[%1] - %2 (%3)",_time,_hisName,_number];
				if (_type isEqualTo 0) then {
					_menu8recentlb lbSetPicture [(lbSize _menu8recentlb)-1,"\ALF_Client2\icons\out.paa"];
				} else {
					_menu8recentlb lbSetPicture [(lbSize _menu8recentlb)-1,"\ALF_Client2\icons\in.paa"];
				};
				_menu8recentlb lbSetData [(lbSize _menu8recentlb)-1,str(_x)];
			} forEach ALF_Phone_Historique;
		} else {
			_menu8recentlb lbAdd "Aucun historique.";
			_menu8recentlb lbSetData [(lbSize _menu8recentlb)-1,"Aucun historique."];
		};
		((findDisplay 56400) displayCtrl 682567) lbSetCurSel 0;

		_menu6btnnew buttonSetAction "ALF_Phone_Historique = []; [] call ALF_fnc_menuiPhone;";
		_menu6btnrep buttonSetAction "[] spawn ALF_fnc_iPhoneCallRecent;";
		_menu6btndel buttonSetAction "[] spawn ALF_fnc_iPhoneSmsRecent;";
	};
};

[] spawn {
	if ((isNull ALF_PhoneObject) && !ALF_Phone_inCall && !ALF_Phone_tryCall) then {
		player playActionNow "ALF_LookAt";
		ALF_PhoneObject = "ALF_Iphone_Object" createVehicle [0,0,1000];
		[ALF_PhoneObject,false] remoteExecCall ["enableSimulationGlobal",2];
		uiSleep 0.3;
		if (vehicle player isEqualTo player) then {
			ALF_PhoneObject attachTo [player, [-0.08,0.08,0.05], "RightHandMiddle1"];     
			ALF_PhoneObject setVectorDirAndUp [[0.1, -1.9, -0.8],[-0.25, -0.5, 0.5]];
		};
		
		waitUntil {(isNull findDisplay 56400) || ALF_Phone_inCall || ALF_Phone_tryCall};

		if (!ALF_Phone_inCall && !ALF_Phone_tryCall) then {
			detach ALF_PhoneObject;
			deleteVehicle ALF_PhoneObject;
			ALF_PhoneObject = objNull;
			player playActionNow "gestureNod";
			[{player playActionNow "gestureNod";}] call CBA_fnc_execNextFrame;
		};
	};
};