#include "\ALF_Client\script_macros.hpp"
/*
File: fn_menuInternet.sqf
Author: ALF Team
*/
private _pc = nearestObject [player, "Land_PCSet_01_screen_F"];

if (isNull _pc) exitWith {};
if !([_pc] call ALF_fnc_hasEnergy) exitWith {
	if (dialog) then {
		closeDialog 0;
	};
	["PC", "Le PC n'a pas d'électricité.", "danger"] spawn ALF_fnc_doMsg;
};

if(!dialog) then {
	createDialog "ALF_Internet_Dialog";
};
disableSerialization;

private _display = findDisplay 24500;
private _menuurl = _display displayCtrl 24501;
private _urledit = _display displayCtrl 24502;
private _urlbtn = _display displayCtrl 24503;
private _knabis1 = _display displayCtrl 24504;
private _knabisedit = _display displayCtrl 24505;
private _knabistext = _display displayCtrl 24506;
private _knabisbtn = _display displayCtrl 24507;
private _knabis2 = _display displayCtrl 24508;
private _knabislist = _display displayCtrl 24509;
private _knabisbtn2 = _display displayCtrl 24510;
private _armurerie1 = _display displayCtrl 24511;
private _bm1 = _display displayCtrl 24424;
private _bm2 = _display displayCtrl 24425;
private _armurerie1list = _display displayCtrl 24512;
private _armurerie1edit = _display displayCtrl 24513;
private _armurerie1pic = _display displayCtrl 24514;
private _armurerie1countp = _display displayCtrl 24515;
private _armurerie1btnp = _display displayCtrl 24516;
private _armurerie1btnadd = _display displayCtrl 24517;
private _armurerie2 = _display displayCtrl 24518;
private _armurerie2del = _display displayCtrl 24519;
private _armurerie2price = _display displayCtrl 24520;
private _armurerie2listliv = _display displayCtrl 24521;
private _armurerie2payer = _display displayCtrl 24522;
private _armurerie2plist = _display displayCtrl 24523;
private _bourse = _display displayCtrl 24524;
private _bourselist = _display displayCtrl 24525;
private _boursetext1 = _display displayCtrl 24526;
private _boursetext2 = _display displayCtrl 24527;
private _lbc1 = _display displayCtrl 24528;
private _lbc2 = _display displayCtrl 24529;
private _btn1lbc = _display displayCtrl 24530;
private _btn2lbc = _display displayCtrl 24531;
private _lbclb = _display displayCtrl 24532;
private _lbctxt1 = _display displayCtrl 24533;
private _lbctxt2 = _display displayCtrl 24534;
private _lbctxt3 = _display displayCtrl 24535;
private _lbctxt4 = _display displayCtrl 24536;
private _lbctxt5 = _display displayCtrl 24537;
private _btn3lbc = _display displayCtrl 24538;
private _edit1lbc = _display displayCtrl 24539;
private _edit2lbc = _display displayCtrl 24540;
private _edit3lbc = _display displayCtrl 24541;
private _edit4lbc = _display displayCtrl 24542;
private _cblbc = _display displayCtrl 24543;
private _btn4lbc = _display displayCtrl 24544;
private _btnlbcan = _display displayCtrl 24545;
private _btnlbsup = _display displayCtrl 24546;

private _menu = uiNamespace getVariable "internetmenu";
switch (_menu) do {
	case 0 : {
		_knabis1 ctrlShow false;
		_knabisedit ctrlShow false;
		_knabistext ctrlShow false;
		_knabisbtn ctrlShow false;
		_knabis2 ctrlShow false;
		_knabislist ctrlShow false;
		_knabisbtn2 ctrlShow false;

		_armurerie1 ctrlShow false;
		_armurerie1list ctrlShow false;
		_armurerie1edit ctrlShow false;
		_armurerie1pic ctrlShow false;
		_armurerie1countp ctrlShow false;
		_armurerie1btnp ctrlShow false;
		_armurerie1btnadd ctrlShow false;
		_armurerie2 ctrlShow false;
		_armurerie2del ctrlShow false;
		_armurerie2price ctrlShow false;
		_armurerie2listliv ctrlShow false;
		_armurerie2payer ctrlShow false;
		_armurerie2plist ctrlShow false;
		_bourse ctrlShow false;
		_bourselist ctrlShow false;
		_boursetext1 ctrlShow false;
		_boursetext2 ctrlShow false;
		_lbc1 ctrlShow false;
		_lbc2 ctrlShow false;
		_btn1lbc ctrlShow false;
		_btn2lbc ctrlShow false;
		_lbclb ctrlShow false;
		_lbctxt1 ctrlShow false;
		_lbctxt2 ctrlShow false;
		_lbctxt3 ctrlShow false;
		_lbctxt4 ctrlShow false;
		_lbctxt5 ctrlShow false;
		_btn3lbc ctrlShow false;
		_edit1lbc ctrlShow false;
		_edit2lbc ctrlShow false;
		_edit3lbc ctrlShow false;
		_edit4lbc ctrlShow false;
		_cblbc ctrlShow false;
		_btn4lbc ctrlShow false;
		_btnlbcan ctrlShow false;
		_btnlbsup ctrlShow false;

		_bm1 ctrlShow false;
		_bm2 ctrlShow false;

		_menuurl ctrlShow true;
		_urledit ctrlShow true;
		_urlbtn ctrlShow true;
		_urlbtn buttonSetAction "[] call ALF_fnc_searchUrl;";
	};
	case 1 : {
		_menuurl ctrlShow false;
		_urledit ctrlShow false;
		_urlbtn ctrlShow false;
		_armurerie1 ctrlShow false;
		_armurerie1list ctrlShow false;
		_armurerie1edit ctrlShow false;
		_armurerie1pic ctrlShow false;
		_armurerie1countp ctrlShow false;
		_armurerie1btnp ctrlShow false;
		_armurerie1btnadd ctrlShow false;
		_armurerie2 ctrlShow false;
		_armurerie2del ctrlShow false;
		_armurerie2price ctrlShow false;
		_armurerie2listliv ctrlShow false;
		_armurerie2payer ctrlShow false;
		_armurerie2plist ctrlShow false;
		_bm1 ctrlShow false;
		_bm2 ctrlShow false;
		_bourse ctrlShow false;
		_bourselist ctrlShow false;
		_boursetext1 ctrlShow false;
		_boursetext2 ctrlShow false;
		_lbc1 ctrlShow false;
		_lbc2 ctrlShow false;
		_btn1lbc ctrlShow false;
		_btn2lbc ctrlShow false;
		_lbclb ctrlShow false;
		_lbctxt1 ctrlShow false;
		_lbctxt2 ctrlShow false;
		_lbctxt3 ctrlShow false;
		_lbctxt4 ctrlShow false;
		_lbctxt5 ctrlShow false;
		_btn3lbc ctrlShow false;
		_edit1lbc ctrlShow false;
		_edit2lbc ctrlShow false;
		_edit3lbc ctrlShow false;
		_edit4lbc ctrlShow false;
		_cblbc ctrlShow false;
		_btn4lbc ctrlShow false;
		_btnlbcan ctrlShow false;
		_btnlbsup ctrlShow false;

		_knabis1 ctrlShow true;
		_knabisedit ctrlShow true;
		_knabistext ctrlShow true;
		_knabisbtn ctrlShow true;
		_knabis2 ctrlShow false;
		_knabislist ctrlShow false;
		_knabisbtn2 ctrlShow false;

		_knabisbtn buttonSetAction "[] call ALF_fnc_knabisBuy;";
	};
	case 2 : {
		_menuurl ctrlShow false;
		_urledit ctrlShow false;
		_urlbtn ctrlShow false;
		_knabis1 ctrlShow false;
		_knabisedit ctrlShow false;
		_knabistext ctrlShow false;
		_knabisbtn ctrlShow false;
		_armurerie1 ctrlShow false;
		_armurerie1list ctrlShow false;
		_armurerie1edit ctrlShow false;
		_armurerie1pic ctrlShow false;
		_armurerie1countp ctrlShow false;
		_armurerie1btnp ctrlShow false;
		_armurerie1btnadd ctrlShow false;
		_armurerie2 ctrlShow false;
		_armurerie2del ctrlShow false;
		_armurerie2price ctrlShow false;
		_armurerie2listliv ctrlShow false;
		_armurerie2payer ctrlShow false;
		_armurerie2plist ctrlShow false;
		_bm1 ctrlShow false;
		_bm2 ctrlShow false;
		_bourse ctrlShow false;
		_bourselist ctrlShow false;
		_boursetext1 ctrlShow false;
		_boursetext2 ctrlShow false;
		_lbc1 ctrlShow false;
		_lbc2 ctrlShow false;
		_btn1lbc ctrlShow false;
		_btn2lbc ctrlShow false;
		_lbclb ctrlShow false;
		_lbctxt1 ctrlShow false;
		_lbctxt2 ctrlShow false;
		_lbctxt3 ctrlShow false;
		_lbctxt4 ctrlShow false;
		_lbctxt5 ctrlShow false;
		_btn3lbc ctrlShow false;
		_edit1lbc ctrlShow false;
		_edit2lbc ctrlShow false;
		_edit3lbc ctrlShow false;
		_edit4lbc ctrlShow false;
		_cblbc ctrlShow false;
		_btn4lbc ctrlShow false;
		_btnlbcan ctrlShow false;
		_btnlbsup ctrlShow false;

		_knabis2 ctrlShow true;
		_knabislist ctrlShow true;
		_knabisbtn2 ctrlShow true;

		[] call ALF_fnc_knabisList;

		_knabisbtn2 buttonSetAction "[] call ALF_fnc_knabisLivraison;";
	};

	case 3 : {
		_menuurl ctrlShow false;
		_urledit ctrlShow false;
		_urlbtn ctrlShow false;
		_knabis1 ctrlShow false;
		_knabisedit ctrlShow false;
		_knabistext ctrlShow false;
		_knabisbtn ctrlShow false;
		_knabis2 ctrlShow false;
		_knabislist ctrlShow false;
		_knabisbtn2 ctrlShow false;
		_armurerie2 ctrlShow false;
		_armurerie2del ctrlShow false;
		_armurerie2price ctrlShow false;
		_armurerie2listliv ctrlShow false;
		_armurerie2payer ctrlShow false;
		_armurerie2plist ctrlShow false;
		_bm1 ctrlShow false;
		_bm2 ctrlShow false;
		_bourse ctrlShow false;
		_bourselist ctrlShow false;
		_boursetext1 ctrlShow false;
		_boursetext2 ctrlShow false;
		_lbc1 ctrlShow false;
		_lbc2 ctrlShow false;
		_btn1lbc ctrlShow false;
		_btn2lbc ctrlShow false;
		_lbclb ctrlShow false;
		_lbctxt1 ctrlShow false;
		_lbctxt2 ctrlShow false;
		_lbctxt3 ctrlShow false;
		_lbctxt4 ctrlShow false;
		_lbctxt5 ctrlShow false;
		_btn3lbc ctrlShow false;
		_edit1lbc ctrlShow false;
		_edit2lbc ctrlShow false;
		_edit3lbc ctrlShow false;
		_edit4lbc ctrlShow false;
		_cblbc ctrlShow false;
		_btn4lbc ctrlShow false;
		_btnlbcan ctrlShow false;
		_btnlbsup ctrlShow false;

		_armurerie1 ctrlShow true;
		_armurerie1list ctrlShow true;
		_armurerie1edit ctrlShow true;
		_armurerie1pic ctrlShow true;
		_armurerie1countp ctrlShow true;
		_armurerie1btnp ctrlShow true;
		_armurerie1btnadd ctrlShow true;

		lbClear _armurerie1list;
		private _config = M_CONFIG(getArray,"WeaponShops","armurerie","items");
		{
			private _itemInfo = [_x select 0] call life_fnc_fetchCfgDetails;
			_armurerie1list lbAdd format["%1 - %2e",_itemInfo select 1,[_x select 2] call life_fnc_numberText];
			_armurerie1list lbSetData[(lbSize _armurerie1list)-1,format["[""%1"",""%2""]",_x select 0,_x select 2]];
			_armurerie1list lbSetPicture[(lbSize _armurerie1list)-1,_itemInfo select 2];
		} forEach (_config);
		_armurerie1countp ctrlSetStructuredText parseText format["<t color='#000000'>%1</t>",count alf_shop_panier];
		_armurerie1btnp buttonSetAction "uiNamespace setVariable ['internetmenu',4]; [] call ALF_fnc_menuInternet;";
		_armurerie1btnadd buttonSetAction "[] call ALF_fnc_addPArmurerie;";
	};

	case 4 : {
		_menuurl ctrlShow false;
		_urledit ctrlShow false;
		_urlbtn ctrlShow false;
		_knabis1 ctrlShow false;
		_knabisedit ctrlShow false;
		_knabistext ctrlShow false;
		_knabisbtn ctrlShow false;
		_knabis2 ctrlShow false;
		_knabislist ctrlShow false;
		_knabisbtn2 ctrlShow false;
		_armurerie1edit ctrlShow false;
		_armurerie1pic ctrlShow false;
		_armurerie1countp ctrlShow false;
		_armurerie1btnp ctrlShow true;
		_armurerie1btnadd ctrlShow false;
		_armurerie1 ctrlShow false;
		_armurerie1list ctrlShow false;
		_bm1 ctrlShow false;
		_bm2 ctrlShow false;
		_bourse ctrlShow false;
		_bourselist ctrlShow false;
		_boursetext1 ctrlShow false;
		_boursetext2 ctrlShow false;
		_lbc1 ctrlShow false;
		_lbc2 ctrlShow false;
		_btn1lbc ctrlShow false;
		_btn2lbc ctrlShow false;
		_lbclb ctrlShow false;
		_lbctxt1 ctrlShow false;
		_lbctxt2 ctrlShow false;
		_lbctxt3 ctrlShow false;
		_lbctxt4 ctrlShow false;
		_lbctxt5 ctrlShow false;
		_btn3lbc ctrlShow false;
		_edit1lbc ctrlShow false;
		_edit2lbc ctrlShow false;
		_edit3lbc ctrlShow false;
		_edit4lbc ctrlShow false;
		_cblbc ctrlShow false;
		_btn4lbc ctrlShow false;
		_btnlbcan ctrlShow false;
		_btnlbsup ctrlShow false;

		_armurerie2 ctrlShow true;
		_armurerie2del ctrlShow true;
		_armurerie2price ctrlShow true;
		_armurerie2listliv ctrlShow true;
		_armurerie2payer ctrlShow true;
		_armurerie2plist ctrlShow true;

		lbClear _armurerie2plist;
		private _pricett = 0;
		{
			private _itemInfo = [_x select 0] call life_fnc_fetchCfgDetails;
			private _itemPrice = _x select 2;
			_pricett = _pricett + _itemPrice;
			_armurerie2plist lbAdd format["%1 - [x%2]",_itemInfo select 1,_x select 1];
			_armurerie2plist lbSetPicture[(lbSize _armurerie2plist)-1,_itemInfo select 2];
			_armurerie2plist lbSetData[(lbSize _armurerie2plist)-1,str(_x)];
		} forEach alf_shop_panier;
		_armurerie2plist lbSetCurSel 0;
		_armurerie1btnp buttonSetAction "uiNamespace setVariable ['internetmenu',3]; [] call ALF_fnc_menuInternet;";
		_armurerie2price ctrlSetStructuredText parseText format["<t color='#000000'>%1€</t>",[_pricett] call life_fnc_numberText];
	
		lbClear _armurerie2listliv;
		{
			private _position = call compile format["%1",_x];
			private _house = nearestObject [_position, "House"];
			private _houseName = getText(configFile >> "CfgVehicles" >> (typeOf _house) >> "displayName");
		
			_armurerie2listliv lbAdd format["%1",_houseName];
			_armurerie2listliv lbSetdata [(lbSize _armurerie2listliv)-1,format["%1",_position]];
		} forEach life_houses;
		_armurerie2listliv lbSetCurSel 0;
		_armurerie2payer buttonSetAction "[] spawn ALF_fnc_payerArmurerie;";
		_armurerie2del buttonSetAction "[] call ALF_fnc_delPArmurerie;";
	};

	case 5 : {
		_menuurl ctrlShow false;
		_urledit ctrlShow false;
		_urlbtn ctrlShow false;
		_knabis1 ctrlShow false;
		_knabisedit ctrlShow false;
		_knabistext ctrlShow false;
		_knabisbtn ctrlShow false;
		_knabis2 ctrlShow false;
		_knabislist ctrlShow false;
		_knabisbtn2 ctrlShow false;
		_armurerie2 ctrlShow false;
		_armurerie2del ctrlShow false;
		_armurerie2price ctrlShow false;
		_armurerie2listliv ctrlShow false;
		_armurerie2payer ctrlShow false;
		_armurerie2plist ctrlShow false;
		_bm1 ctrlShow true;
		_bm2 ctrlShow false;
		_bourse ctrlShow false;
		_bourselist ctrlShow false;
		_boursetext1 ctrlShow false;
		_boursetext2 ctrlShow false;
		_lbc1 ctrlShow false;
		_lbc2 ctrlShow false;
		_btn1lbc ctrlShow false;
		_btn2lbc ctrlShow false;
		_lbclb ctrlShow false;
		_lbctxt1 ctrlShow false;
		_lbctxt2 ctrlShow false;
		_lbctxt3 ctrlShow false;
		_lbctxt4 ctrlShow false;
		_lbctxt5 ctrlShow false;
		_btn3lbc ctrlShow false;
		_edit1lbc ctrlShow false;
		_edit2lbc ctrlShow false;
		_edit3lbc ctrlShow false;
		_edit4lbc ctrlShow false;
		_cblbc ctrlShow false;
		_btn4lbc ctrlShow false;
		_btnlbcan ctrlShow false;
		_btnlbsup ctrlShow false;

		_armurerie1 ctrlShow false;
		_armurerie1list ctrlShow true;
		_armurerie1edit ctrlShow true;
		_armurerie1pic ctrlShow true;
		_armurerie1countp ctrlShow true;
		_armurerie1btnp ctrlShow true;
		_armurerie1btnadd ctrlShow true;

		lbClear _armurerie1list;
		private _config = M_CONFIG(getArray,"WeaponShops","blackmarket","items");
		{
			private _itemInfo = [_x select 0] call life_fnc_fetchCfgDetails;
			_armurerie1list lbAdd format["%1 - %2e",_itemInfo select 1,[_x select 2] call life_fnc_numberText];
			_armurerie1list lbSetData[(lbSize _armurerie1list)-1,format["[""%1"",""%2""]",_x select 0,_x select 2]];
			_armurerie1list lbSetPicture[(lbSize _armurerie1list)-1,_itemInfo select 2];
		} forEach (_config);
		_armurerie1countp ctrlSetStructuredText parseText format["<t color='#000000'>%1</t>",count alf_shop_panier];
		_armurerie1btnp buttonSetAction "uiNamespace setVariable ['internetmenu',6]; [] call ALF_fnc_menuInternet;";
		_armurerie1btnadd buttonSetAction "[] call ALF_fnc_addPArmurerie;";
	};

	case 6 : {
		_menuurl ctrlShow false;
		_urledit ctrlShow false;
		_urlbtn ctrlShow false;
		_knabis1 ctrlShow false;
		_knabisedit ctrlShow false;
		_knabistext ctrlShow false;
		_knabisbtn ctrlShow false;
		_knabis2 ctrlShow false;
		_knabislist ctrlShow false;
		_knabisbtn2 ctrlShow false;
		_armurerie1edit ctrlShow false;
		_armurerie1pic ctrlShow false;
		_armurerie1countp ctrlShow false;
		_armurerie1btnp ctrlShow true;
		_armurerie1btnadd ctrlShow false;
		_armurerie1 ctrlShow false;
		_armurerie1list ctrlShow false;
		_bm1 ctrlShow false;
		_bm2 ctrlShow true;
		_bourse ctrlShow false;
		_bourselist ctrlShow false;
		_boursetext1 ctrlShow false;
		_boursetext2 ctrlShow false;
		_lbc1 ctrlShow false;
		_lbc2 ctrlShow false;
		_btn1lbc ctrlShow false;
		_btn2lbc ctrlShow false;
		_lbclb ctrlShow false;
		_lbctxt1 ctrlShow false;
		_lbctxt2 ctrlShow false;
		_lbctxt3 ctrlShow false;
		_lbctxt4 ctrlShow false;
		_lbctxt5 ctrlShow false;
		_btn3lbc ctrlShow false;
		_edit1lbc ctrlShow false;
		_edit2lbc ctrlShow false;
		_edit3lbc ctrlShow false;
		_edit4lbc ctrlShow false;
		_cblbc ctrlShow false;
		_btn4lbc ctrlShow false;
		_btnlbcan ctrlShow false;
		_btnlbsup ctrlShow false;

		_armurerie2 ctrlShow false;
		_armurerie2del ctrlShow true;
		_armurerie2price ctrlShow true;
		_armurerie2listliv ctrlShow true;
		_armurerie2payer ctrlShow true;
		_armurerie2plist ctrlShow true;

		lbClear _armurerie2plist;
		private _pricett = 0;
		{
			private _itemInfo = [_x select 0] call life_fnc_fetchCfgDetails;
			private _itemPrice = _x select 2;
			_pricett = _pricett + _itemPrice;
			_armurerie2plist lbAdd format["%1 - [x%2]",_itemInfo select 1,_x select 1];
			_armurerie2plist lbSetPicture[(lbSize _armurerie2plist)-1,_itemInfo select 2];
			_armurerie2plist lbSetData[(lbSize _armurerie2plist)-1,str(_x)];
		} forEach alf_shop_panier;
		_armurerie2plist lbSetCurSel 0;
		_armurerie1btnp buttonSetAction "uiNamespace setVariable ['internetmenu',5]; [] call ALF_fnc_menuInternet;";
		_armurerie2price ctrlSetStructuredText parseText format["<t color='#000000'>%1€</t>",[_pricett] call life_fnc_numberText];
	
		lbClear _armurerie2listliv;
		{
			private _position = call compile format["%1",_x];
			private _house = nearestObject [_position, "House"];
			private _houseName = getText(configFile >> "CfgVehicles" >> (typeOf _house) >> "displayName");
		
			_armurerie2listliv lbAdd format["%1",_houseName];
			_armurerie2listliv lbSetdata [(lbSize _armurerie2listliv)-1,format["%1",_position]];
		} forEach life_houses;
		_armurerie2listliv lbSetCurSel 0;
		_armurerie2payer buttonSetAction "[] spawn ALF_fnc_payerBM;";
		_armurerie2del buttonSetAction "[] call ALF_fnc_delPArmurerie;";
	};

	case 7 : {
		_menuurl ctrlShow false;
		_urledit ctrlShow false;
		_urlbtn ctrlShow false;
		_knabis1 ctrlShow false;
		_knabisedit ctrlShow false;
		_knabistext ctrlShow false;
		_knabisbtn ctrlShow false;
		_knabis2 ctrlShow false;
		_knabislist ctrlShow false;
		_knabisbtn2 ctrlShow false;
		_armurerie2 ctrlShow false;
		_armurerie2del ctrlShow false;
		_armurerie2price ctrlShow false;
		_armurerie2listliv ctrlShow false;
		_armurerie2payer ctrlShow false;
		_armurerie2plist ctrlShow false;
		_bm1 ctrlShow false;
		_bm2 ctrlShow false;
		_armurerie1 ctrlShow false;
		_armurerie1list ctrlShow false;
		_armurerie1edit ctrlShow false;
		_armurerie1pic ctrlShow false;
		_armurerie1countp ctrlShow false;
		_armurerie1btnp ctrlShow false;
		_armurerie1btnadd ctrlShow false;
		_lbc1 ctrlShow false;
		_lbc2 ctrlShow false;
		_btn1lbc ctrlShow false;
		_btn2lbc ctrlShow false;
		_lbclb ctrlShow false;
		_lbctxt1 ctrlShow false;
		_lbctxt2 ctrlShow false;
		_lbctxt3 ctrlShow false;
		_lbctxt4 ctrlShow false;
		_lbctxt5 ctrlShow false;
		_btn3lbc ctrlShow false;
		_edit1lbc ctrlShow false;
		_edit2lbc ctrlShow false;
		_edit3lbc ctrlShow false;
		_edit4lbc ctrlShow false;
		_cblbc ctrlShow false;
		_btn4lbc ctrlShow false;
		_btnlbcan ctrlShow false;
		_btnlbsup ctrlShow false;

		_bourse ctrlShow true;
		_bourselist ctrlShow true;
		_boursetext1 ctrlShow true;
		_boursetext2 ctrlShow true;

		[] call ALF_fnc_loadlbPrice;
	};
	case 8 : {
		_menuurl ctrlShow false;
		_urledit ctrlShow false;
		_urlbtn ctrlShow false;
		_knabis1 ctrlShow false;
		_knabisedit ctrlShow false;
		_knabistext ctrlShow false;
		_knabisbtn ctrlShow false;
		_knabis2 ctrlShow false;
		_knabislist ctrlShow false;
		_knabisbtn2 ctrlShow false;
		_armurerie2 ctrlShow false;
		_armurerie2del ctrlShow false;
		_armurerie2price ctrlShow false;
		_armurerie2listliv ctrlShow false;
		_armurerie2payer ctrlShow false;
		_armurerie2plist ctrlShow false;
		_bm1 ctrlShow false;
		_bm2 ctrlShow false;
		_armurerie1 ctrlShow false;
		_armurerie1list ctrlShow false;
		_armurerie1edit ctrlShow false;
		_armurerie1pic ctrlShow false;
		_armurerie1countp ctrlShow false;
		_armurerie1btnp ctrlShow false;
		_armurerie1btnadd ctrlShow false;
		_bourse ctrlShow false;
		_bourselist ctrlShow false;
		_boursetext1 ctrlShow false;
		_boursetext2 ctrlShow false;
		
		_lbc1 ctrlShow true;
		_lbc2 ctrlShow false;
		_btn1lbc ctrlShow false;
		_btn2lbc ctrlShow false;
		_lbclb ctrlShow true;
		_lbctxt1 ctrlShow true;
		_lbctxt2 ctrlShow true;
		_lbctxt3 ctrlShow true;
		_lbctxt4 ctrlShow true;
		_lbctxt5 ctrlShow true;
		_btn3lbc ctrlShow false;
		_edit1lbc ctrlShow false;
		_edit2lbc ctrlShow false;
		_edit3lbc ctrlShow false;
		_edit4lbc ctrlShow false;
		_cblbc ctrlShow false;
		_btn4lbc ctrlShow false;
		_btnlbcan ctrlShow false;
		_btnlbsup ctrlShow false;

		[player] remoteExec ["HC_fnc_getAnnonceLeboncoin",HC_Life];
	};
	case 9 : {
		_menuurl ctrlShow false;
		_urledit ctrlShow false;
		_urlbtn ctrlShow false;
		_knabis1 ctrlShow false;
		_knabisedit ctrlShow false;
		_knabistext ctrlShow false;
		_knabisbtn ctrlShow false;
		_knabis2 ctrlShow false;
		_knabislist ctrlShow false;
		_knabisbtn2 ctrlShow false;
		_armurerie2 ctrlShow false;
		_armurerie2del ctrlShow false;
		_armurerie2price ctrlShow false;
		_armurerie2listliv ctrlShow false;
		_armurerie2payer ctrlShow false;
		_armurerie2plist ctrlShow false;
		_bm1 ctrlShow false;
		_bm2 ctrlShow false;
		_armurerie1 ctrlShow false;
		_armurerie1list ctrlShow false;
		_armurerie1edit ctrlShow false;
		_armurerie1pic ctrlShow false;
		_armurerie1countp ctrlShow false;
		_armurerie1btnp ctrlShow false;
		_armurerie1btnadd ctrlShow false;
		_bourse ctrlShow false;
		_bourselist ctrlShow false;
		_boursetext1 ctrlShow false;
		_boursetext2 ctrlShow false;

		_lbc1 ctrlShow false;
		_lbc2 ctrlShow true;
		_btn1lbc ctrlShow false;
		_btn2lbc ctrlShow false;
		_lbclb ctrlShow true;
		_lbctxt1 ctrlShow false;
		_lbctxt2 ctrlShow false;
		_lbctxt3 ctrlShow false;
		_lbctxt4 ctrlShow false;
		_lbctxt5 ctrlShow false;
		_btn3lbc ctrlShow false;
		_edit1lbc ctrlShow true;
		_edit2lbc ctrlShow true;
		_edit3lbc ctrlShow true;
		_edit4lbc ctrlShow true;
		_cblbc ctrlShow false;
		_btn4lbc ctrlShow true;
		_btnlbcan ctrlShow false;
		_btnlbsup ctrlShow false;

		[getPlayerUID player,player] remoteExec ["HC_fnc_getLeboncoin",HC_Life];
		_btn4lbc buttonSetAction "[] spawn ALF_fnc_vendreLeboncoin;";
	};

	case 10 : {
		_menuurl ctrlShow false;
		_urledit ctrlShow false;
		_urlbtn ctrlShow false;
		_knabis1 ctrlShow false;
		_knabisedit ctrlShow false;
		_knabistext ctrlShow false;
		_knabisbtn ctrlShow false;
		_knabis2 ctrlShow false;
		_knabislist ctrlShow false;
		_knabisbtn2 ctrlShow false;
		_armurerie2 ctrlShow false;
		_armurerie2del ctrlShow false;
		_armurerie2price ctrlShow false;
		_armurerie2listliv ctrlShow false;
		_armurerie2payer ctrlShow false;
		_armurerie2plist ctrlShow false;
		_bm1 ctrlShow true;
		_bm2 ctrlShow false;
		_bourse ctrlShow false;
		_bourselist ctrlShow false;
		_boursetext1 ctrlShow false;
		_boursetext2 ctrlShow false;
		_lbc1 ctrlShow false;
		_lbc2 ctrlShow false;
		_btn1lbc ctrlShow false;
		_btn2lbc ctrlShow false;
		_lbclb ctrlShow false;
		_lbctxt1 ctrlShow false;
		_lbctxt2 ctrlShow false;
		_lbctxt3 ctrlShow false;
		_lbctxt4 ctrlShow false;
		_lbctxt5 ctrlShow false;
		_btn3lbc ctrlShow false;
		_edit1lbc ctrlShow false;
		_edit2lbc ctrlShow false;
		_edit3lbc ctrlShow false;
		_edit4lbc ctrlShow false;
		_cblbc ctrlShow false;
		_btn4lbc ctrlShow false;
		_btnlbcan ctrlShow false;
		_btnlbsup ctrlShow false;

		_armurerie1 ctrlShow false;
		_armurerie1list ctrlShow true;
		_armurerie1edit ctrlShow true;
		_armurerie1pic ctrlShow true;
		_armurerie1countp ctrlShow true;
		_armurerie1btnp ctrlShow true;
		_armurerie1btnadd ctrlShow true;

		lbClear _armurerie1list;
		private _config = M_CONFIG(getArray,"WeaponShops","blackmarket2","items");
		{
			private _itemInfo = [_x select 0] call life_fnc_fetchCfgDetails;
			_armurerie1list lbAdd format["%1 - %2e",_itemInfo select 1,[_x select 2] call life_fnc_numberText];
			_armurerie1list lbSetData[(lbSize _armurerie1list)-1,format["[""%1"",""%2""]",_x select 0,_x select 2]];
			_armurerie1list lbSetPicture[(lbSize _armurerie1list)-1,_itemInfo select 2];
		} forEach (_config);
		_armurerie1countp ctrlSetStructuredText parseText format["<t color='#000000'>%1</t>",count alf_shop_panier];
		_armurerie1btnp buttonSetAction "uiNamespace setVariable ['internetmenu',11]; [] call ALF_fnc_menuInternet;";
		_armurerie1btnadd buttonSetAction "[] call ALF_fnc_addPArmurerie;";
	};

	case 11 : {
		_menuurl ctrlShow false;
		_urledit ctrlShow false;
		_urlbtn ctrlShow false;
		_knabis1 ctrlShow false;
		_knabisedit ctrlShow false;
		_knabistext ctrlShow false;
		_knabisbtn ctrlShow false;
		_knabis2 ctrlShow false;
		_knabislist ctrlShow false;
		_knabisbtn2 ctrlShow false;
		_armurerie1edit ctrlShow false;
		_armurerie1pic ctrlShow false;
		_armurerie1countp ctrlShow false;
		_armurerie1btnp ctrlShow true;
		_armurerie1btnadd ctrlShow false;
		_armurerie1 ctrlShow false;
		_armurerie1list ctrlShow false;
		_bm1 ctrlShow false;
		_bm2 ctrlShow true;
		_bourse ctrlShow false;
		_bourselist ctrlShow false;
		_boursetext1 ctrlShow false;
		_boursetext2 ctrlShow false;
		_lbc1 ctrlShow false;
		_lbc2 ctrlShow false;
		_btn1lbc ctrlShow false;
		_btn2lbc ctrlShow false;
		_lbclb ctrlShow false;
		_lbctxt1 ctrlShow false;
		_lbctxt2 ctrlShow false;
		_lbctxt3 ctrlShow false;
		_lbctxt4 ctrlShow false;
		_lbctxt5 ctrlShow false;
		_btn3lbc ctrlShow false;
		_edit1lbc ctrlShow false;
		_edit2lbc ctrlShow false;
		_edit3lbc ctrlShow false;
		_edit4lbc ctrlShow false;
		_cblbc ctrlShow false;
		_btn4lbc ctrlShow false;
		_btnlbcan ctrlShow false;
		_btnlbsup ctrlShow false;

		_armurerie2 ctrlShow false;
		_armurerie2del ctrlShow true;
		_armurerie2price ctrlShow true;
		_armurerie2listliv ctrlShow true;
		_armurerie2payer ctrlShow true;
		_armurerie2plist ctrlShow true;

		lbClear _armurerie2plist;
		private _pricett = 0;
		{
			private _itemInfo = [_x select 0] call life_fnc_fetchCfgDetails;
			private _itemPrice = _x select 2;
			_pricett = _pricett + _itemPrice;
			_armurerie2plist lbAdd format["%1 - [x%2]",_itemInfo select 1,_x select 1];
			_armurerie2plist lbSetPicture[(lbSize _armurerie2plist)-1,_itemInfo select 2];
			_armurerie2plist lbSetData[(lbSize _armurerie2plist)-1,str(_x)];
		} forEach alf_shop_panier;
		_armurerie2plist lbSetCurSel 0;
		_armurerie1btnp buttonSetAction "uiNamespace setVariable ['internetmenu',10]; [] call ALF_fnc_menuInternet;";
		_armurerie2price ctrlSetStructuredText parseText format["<t color='#000000'>%1€</t>",[_pricett] call life_fnc_numberText];
	
		lbClear _armurerie2listliv;
		{
			private _position = call compile format["%1",_x];
			private _house = nearestObject [_position, "House"];
			private _houseName = getText(configFile >> "CfgVehicles" >> (typeOf _house) >> "displayName");
		
			_armurerie2listliv lbAdd format["%1",_houseName];
			_armurerie2listliv lbSetdata [(lbSize _armurerie2listliv)-1,format["%1",_position]];
		} forEach life_houses;
		_armurerie2listliv lbSetCurSel 0;
		_armurerie2payer buttonSetAction "[] spawn ALF_fnc_payerBM;";
		_armurerie2del buttonSetAction "[] call ALF_fnc_delPArmurerie;";
	};
	
	case 12 : {
		_menuurl ctrlShow false;
		_urledit ctrlShow false;
		_urlbtn ctrlShow false;
		_knabis1 ctrlShow false;
		_knabisedit ctrlShow false;
		_knabistext ctrlShow false;
		_knabisbtn ctrlShow false;
		_knabis2 ctrlShow false;
		_knabislist ctrlShow false;
		_knabisbtn2 ctrlShow false;
		_armurerie2 ctrlShow false;
		_armurerie2del ctrlShow false;
		_armurerie2price ctrlShow false;
		_armurerie2listliv ctrlShow false;
		_armurerie2payer ctrlShow false;
		_armurerie2plist ctrlShow false;
		_bm1 ctrlShow true;
		_bm2 ctrlShow false;
		_bourse ctrlShow false;
		_bourselist ctrlShow false;
		_boursetext1 ctrlShow false;
		_boursetext2 ctrlShow false;
		_lbc1 ctrlShow false;
		_lbc2 ctrlShow false;
		_btn1lbc ctrlShow false;
		_btn2lbc ctrlShow false;
		_lbclb ctrlShow false;
		_lbctxt1 ctrlShow false;
		_lbctxt2 ctrlShow false;
		_lbctxt3 ctrlShow false;
		_lbctxt4 ctrlShow false;
		_lbctxt5 ctrlShow false;
		_btn3lbc ctrlShow false;
		_edit1lbc ctrlShow false;
		_edit2lbc ctrlShow false;
		_edit3lbc ctrlShow false;
		_edit4lbc ctrlShow false;
		_cblbc ctrlShow false;
		_btn4lbc ctrlShow false;
		_btnlbcan ctrlShow false;
		_btnlbsup ctrlShow false;

		_armurerie1 ctrlShow false;
		_armurerie1list ctrlShow true;
		_armurerie1edit ctrlShow true;
		_armurerie1pic ctrlShow true;
		_armurerie1countp ctrlShow true;
		_armurerie1btnp ctrlShow true;
		_armurerie1btnadd ctrlShow true;

		lbClear _armurerie1list;
		private _config = M_CONFIG(getArray,"WeaponShops","blackmarket3","items");
		{
			private _itemInfo = [_x select 0] call life_fnc_fetchCfgDetails;
			_armurerie1list lbAdd format["%1 - %2e",_itemInfo select 1,[_x select 2] call life_fnc_numberText];
			_armurerie1list lbSetData[(lbSize _armurerie1list)-1,format["[""%1"",""%2""]",_x select 0,_x select 2]];
			_armurerie1list lbSetPicture[(lbSize _armurerie1list)-1,_itemInfo select 2];
		} forEach (_config);
		_armurerie1countp ctrlSetStructuredText parseText format["<t color='#000000'>%1</t>",count alf_shop_panier];
		_armurerie1btnp buttonSetAction "uiNamespace setVariable ['internetmenu',13]; [] call ALF_fnc_menuInternet;";
		_armurerie1btnadd buttonSetAction "[] call ALF_fnc_addPArmurerie;";
	};
	
	case 13 : {
		_menuurl ctrlShow false;
		_urledit ctrlShow false;
		_urlbtn ctrlShow false;
		_knabis1 ctrlShow false;
		_knabisedit ctrlShow false;
		_knabistext ctrlShow false;
		_knabisbtn ctrlShow false;
		_knabis2 ctrlShow false;
		_knabislist ctrlShow false;
		_knabisbtn2 ctrlShow false;
		_armurerie1edit ctrlShow false;
		_armurerie1pic ctrlShow false;
		_armurerie1countp ctrlShow false;
		_armurerie1btnp ctrlShow true;
		_armurerie1btnadd ctrlShow false;
		_armurerie1 ctrlShow false;
		_armurerie1list ctrlShow false;
		_bm1 ctrlShow false;
		_bm2 ctrlShow true;
		_bourse ctrlShow false;
		_bourselist ctrlShow false;
		_boursetext1 ctrlShow false;
		_boursetext2 ctrlShow false;
		_lbc1 ctrlShow false;
		_lbc2 ctrlShow false;
		_btn1lbc ctrlShow false;
		_btn2lbc ctrlShow false;
		_lbclb ctrlShow false;
		_lbctxt1 ctrlShow false;
		_lbctxt2 ctrlShow false;
		_lbctxt3 ctrlShow false;
		_lbctxt4 ctrlShow false;
		_lbctxt5 ctrlShow false;
		_btn3lbc ctrlShow false;
		_edit1lbc ctrlShow false;
		_edit2lbc ctrlShow false;
		_edit3lbc ctrlShow false;
		_edit4lbc ctrlShow false;
		_cblbc ctrlShow false;
		_btn4lbc ctrlShow false;
		_btnlbcan ctrlShow false;
		_btnlbsup ctrlShow false;

		_armurerie2 ctrlShow false;
		_armurerie2del ctrlShow true;
		_armurerie2price ctrlShow true;
		_armurerie2listliv ctrlShow true;
		_armurerie2payer ctrlShow true;
		_armurerie2plist ctrlShow true;

		lbClear _armurerie2plist;
		private _pricett = 0;
		{
			private _itemInfo = [_x select 0] call life_fnc_fetchCfgDetails;
			private _itemPrice = _x select 2;
			_pricett = _pricett + _itemPrice;
			_armurerie2plist lbAdd format["%1 - [x%2]",_itemInfo select 1,_x select 1];
			_armurerie2plist lbSetPicture[(lbSize _armurerie2plist)-1,_itemInfo select 2];
			_armurerie2plist lbSetData[(lbSize _armurerie2plist)-1,str(_x)];
		} forEach alf_shop_panier;
		_armurerie2plist lbSetCurSel 0;
		_armurerie1btnp buttonSetAction "uiNamespace setVariable ['internetmenu',12]; [] call ALF_fnc_menuInternet;";
		_armurerie2price ctrlSetStructuredText parseText format["<t color='#000000'>%1€</t>",[_pricett] call life_fnc_numberText];
	
		lbClear _armurerie2listliv;
		{
			private _position = call compile format["%1",_x];
			private _house = nearestObject [_position, "House"];
			private _houseName = getText(configFile >> "CfgVehicles" >> (typeOf _house) >> "displayName");
		
			_armurerie2listliv lbAdd format["%1",_houseName];
			_armurerie2listliv lbSetdata [(lbSize _armurerie2listliv)-1,format["%1",_position]];
		} forEach life_houses;
		_armurerie2listliv lbSetCurSel 0;
		_armurerie2payer buttonSetAction "[] spawn ALF_fnc_payerBM;";
		_armurerie2del buttonSetAction "[] call ALF_fnc_delPArmurerie;";
	};
};
