[
	[_this,0,objNull,[objNull]] call BIS_fnc_param,
	[
		["PRESENTER CARTE IDENTITE",
			"[player,player getVariable [""IdentititeFausse"",profileName]] remoteExecCall [""ALF_fnc_showIDcard"",life_pInact_curObject];",
			"'ALF_identite' in (magazines player)"],
		["PRESENTER PERMIS",
			"[name player,license_driver,license_trucking,life_permis,license_moto,license_boat,license_pilot] remoteExec [""ALF_fnc_showPcard"",life_pInact_curObject];",
			"'ALF_Permis' in (magazines player)"],
		["DEMENOTTER",
			"[life_pInact_curObject] call ALF_fnc_unrestrain;",
			"[life_pInact_curObject] call ALF_fnc_checkMenotter && {'ALF_cle_M' in (magazines player)}"],
		["LIBERER",
			"[life_pInact_curObject] call ALF_fnc_unrestrain2;",
			"[life_pInact_curObject] call ALF_fnc_checkMenotter && {'ALF_ZipCutter' in (magazines player)}"],
			
		["ASSIGNER CELLULE",
			"[4,[],life_pInact_curObject] spawn ALF_fnc_menuMettrePrison;",
			"life_penit_service && {life_pInact_curObject getVariable [""ALF_EnPrison"",false]}"],
		["METTRE EN PRISON",
			"[0,[],life_pInact_curObject] spawn ALF_fnc_menuMettrePrison;",
			"life_penit_service && {player distance [11005.1,3701.35,0.00239563] <= 100} && {!(life_pInact_curObject getVariable [""ALF_EnPrison"",false])}"],
		["SORTIR DE PRISON",
			"life_pInact_curObject setVariable ['ALF_EnPrison',false,true];",
			"life_penit_service && {player distance [11005.1,3701.35,0.00239563] <= 100} && {life_pInact_curObject getVariable [""ALF_EnPrison"",false]}"],
		["SOIGNER",
			"[life_pInact_curObject] spawn ALF_fnc_soignerPompier;",
			"((life_penit_service && license_medWork) || life_pompier_service) && {'ALF_Bandage' in (magazines player)}"],
			
		["TEST ALCOOLEMIE",
			"[player] remoteExec [""ALF_fnc_testAlcoolemie"",life_pInact_curObject];",
			"'ALF_Alcootest' in (magazines player)"],
		["TEST STUPEFIANTS",
			"[player] remoteExec [""ALF_fnc_testStup"",life_pInact_curObject];",
			"'ALF_TestStup' in (magazines player)"],
		["METTRE UN BRACELET",
			"[0,[],life_pInact_curObject] spawn ALF_fnc_menuAjoutBracelet;",
			"'ALF_Bracelet' in (magazines player) && {!(life_pInact_curObject in (missionNamespace getVariable [""ALF_AllBracelets"",[]]))} && {life_gendarme_service || life_penit_service}"],
		["ENLEVER LE BRACELET",
			"[1,life_pInact_curObject] call ALF_fnc_enleverBracelet;",
			"(life_pInact_curObject in (missionNamespace getVariable [""ALF_AllBracelets"",[]])) && {life_gendarme_service || life_penit_service}"],
		["AMENDE",
			"[life_pInact_curObject] call ALF_fnc_ticketAction;",
			"life_gendarme_service"],
		["VERIFIER CASH",
			"[player] remoteExecCall [""ALF_fnc_verifCash"",life_pInact_curObject];",
			"life_gendarme_service && {[life_pInact_curObject] call ALF_fnc_checkMenotter || ([life_pInact_curObject] call ALF_fnc_checkSurrender)}"],
		["SAISIR CASH",
			"[player] remoteExecCall [""ALF_fnc_saisieCash"",life_pInact_curObject];",
			"life_gendarme_service && {[life_pInact_curObject] call ALF_fnc_checkMenotter || ([life_pInact_curObject] call ALF_fnc_checkSurrender)}"],
		["FOUILLER",
			"[life_pInact_curObject] spawn ALF_fnc_fouilleAnal;",
			"((life_gendarme_service || life_penit_service) && {[life_pInact_curObject] call ALF_fnc_checkMenotter}) || {[life_pInact_curObject] call ALF_fnc_checkSurrender}"],
		["TEST ADN",
			"[life_pInact_curObject] spawn ALF_fnc_getPlayerAdn;",
			"life_gendarme_service && (player distance (nearestObject [position player,""Land_Caserne""]) < 100 || {player distance (nearestObject [position player,""Land_ALF_Comico2""]) < 100})"],
		["RECO. FACIAL",
			"[life_pInact_curObject] spawn ALF_fnc_getPlayerFace;",
			"life_gendarme_service && (player distance (nearestObject [position player,""Land_Caserne""]) < 100 || {player distance (nearestObject [position player,""Land_ALF_Comico2""]) < 100})"],
		["ENLEVER PERMIS",
			"[life_pInact_curObject] call ALF_fnc_actionPoints;",
			"life_gendarme_service"],
		["ENLEVER POINTS",
			"[life_pInact_curObject] call ALF_fnc_actionPoints;",
			"life_gendarme_service"],
		["VERIFIER PERMIS ARMES",
			"[player] remoteExec [""ALF_fnc_verifParmes"",life_pInact_curObject];",
			"life_gendarme_service"],
		["ENLEVER PERMIS ARMES",
			"[2] remoteExecCall [""ALF_fnc_Parmes"",life_pInact_curObject]; [""Info"", ""Tu as retiré le permis port d'armes de la personne."", ""success"", false] spawn ALF_fnc_doMsg;",
			"life_gendarme_service && licence_gunTarget"],
		
		["GROUPE SANGUIN",
			"[0,life_pInact_curObject] spawn ALF_fnc_testGroupeSanguin;",
			"life_pompier_service"],
		
		["CROCHETER LE BRACELET",
			"[0,life_pInact_curObject] spawn ALF_fnc_enleverBracelet;",
			"'ALF_Lockpick' in (magazines player) && {life_pInact_curObject in (missionNamespace getVariable [""ALF_AllBracelets"",[]])}"],
		["METTRE LA CAGOULE",
			"[life_pInact_curObject] spawn ALF_fnc_headbag_put_action;",
			"([life_pInact_curObject] call ALF_fnc_checkMenotter) && ('ALF_Headbag' in (items player)) && ((headgear life_pInact_curObject) != 'ALF_Headbag')"],
		["RETIRER LA CAGOULE",
			"[life_pInact_curObject] spawn ALF_fnc_headbag_take_action;",
			"([life_pInact_curObject] call ALF_fnc_checkMenotter) && ((headgear life_pInact_curObject) isEqualTo 'ALF_Headbag')"],
		
		["DONNER LICENCE PILOTE",
			"[2] remoteExecCall [""ALF_fnc_pilot"",life_pInact_curObject]; [""Info"", ""Tu as donné la licence de vol à la personne."", ""success"", false] spawn ALF_fnc_doMsg;",
			"!licence_pilotTarget && b_15"],
		["ELEVER LICENCE PILOTE",
			"[3] remoteExecCall [""ALF_fnc_pilot"",life_pInact_curObject]; [""Info"", ""Tu as retiré la licence de vol de cette personne."", ""success"", false] spawn ALF_fnc_doMsg;",
			"licence_pilotTarget && b_15"],
		["FAIRE FACTURE",
			"createDialog ""Life_facture"";",
			"!(player getVariable [""isEmployed"",""""] isEqualTo """") && !(life_pompier_service && life_gendarme_service && life_penit_service)"],
			
		["[P] Virer de la prison",
			"[0,player] remoteExecCall [""ALF_fnc_penitSetLevel"",life_pInact_curObject];",
			"life_penit > 2"],
		["[P] Passer S. Stagiaire",
			"[1,player] remoteExecCall [""ALF_fnc_penitSetLevel"",life_pInact_curObject];",
			"life_penit > 1"],
		["[P] Passer S. Titulaire",
			"[2,player] remoteExecCall [""ALF_fnc_penitSetLevel"",life_pInact_curObject];",
			"life_penit > 2"],
		["[P] Passer S. Principal",
			"[3,player] remoteExecCall [""ALF_fnc_penitSetLevel"",life_pInact_curObject];",
			"life_penit > 3"],
		["[P] Passer S. Brigadier",
			"[4,player] remoteExecCall [""ALF_fnc_penitSetLevel"",life_pInact_curObject];",
			"life_penit > 4"],
		["[P] Passer S. Brigadier",
			"[4,player] remoteExecCall [""ALF_fnc_penitSetLevel"",life_pInact_curObject];",
			"life_penit > 4"],
		["[P] Passer P. Surveillant",
			"[5,player] remoteExecCall [""ALF_fnc_penitSetLevel"",life_pInact_curObject];",
			"life_penit > 5"],
		["[P] Passer Major",
			"[6,player] remoteExecCall [""ALF_fnc_penitSetLevel"",life_pInact_curObject];",
			"life_penit > 6"],
		["[P] Passer Lieutenant",
			"[7,player] remoteExecCall [""ALF_fnc_penitSetLevel"",life_pInact_curObject];",
			"life_penit > 7"],
		["[P] Passer Capitaine",
			"[8,player] remoteExecCall [""ALF_fnc_penitSetLevel"",life_pInact_curObject];",
			"life_penit > 8"],
		["[P] Passer Commandant",
			"[9,player] remoteExecCall [""ALF_fnc_penitSetLevel"",life_pInact_curObject];",
			"life_penit > 9"],
		["AJOUTER Medecin",
			"[""medWork"",player] remoteExecCall [""ALF_fnc_penitSetLic"",life_pInact_curObject];",
			"life_penit > 8"],
		["RETIRER Medecin",
			"[""NOmedWork"",player] remoteExecCall [""ALF_fnc_penitSetLic"",life_pInact_curObject];",
			"life_penit > 8"],
		["AJOUTER ERIS",
			"[""eris"",player] remoteExecCall [""ALF_fnc_penitSetLic"",life_pInact_curObject];",
			"life_penit > 8"],
		["RETIRER ERIS",
			"[""NOeris"",player] remoteExecCall [""ALF_fnc_penitSetLic"",life_pInact_curObject];",
			"life_penit > 8"],
		["AJOUTER CYNO.",
			"[""cynoAP"",player] remoteExecCall [""ALF_fnc_penitSetLic"",life_pInact_curObject];",
			"life_penit > 8"],
		["RETIRER CYNO.",
			"[""NOcynoAP"",player] remoteExecCall [""ALF_fnc_penitSetLic"",life_pInact_curObject];",
			"life_penit > 8"],
		
		["[G] Virer de la Gendarmerie",
			"[0,player] remoteExecCall [""ALF_fnc_copSetLevel"",life_pInact_curObject];",
			"life_coplevel > 2"],
		["[G] Passer Elève Gendarme",
			"[1,player] remoteExecCall [""ALF_fnc_copSetLevel"",life_pInact_curObject];",
			"life_coplevel > 1"],
		["[G] Passer Gendarme",
			"[2,player] remoteExecCall [""ALF_fnc_copSetLevel"",life_pInact_curObject];",
			"life_coplevel > 2"],
		["[G] Passer MDL-Chef",
			"[3,player] remoteExecCall [""ALF_fnc_copSetLevel"",life_pInact_curObject];",
			"life_coplevel > 3"],
		["[G] Passer Adjudant",
			"[4,player] remoteExecCall [""ALF_fnc_copSetLevel"",life_pInact_curObject];",
			"life_coplevel > 4"],
		["[G] Passer Adjudant-Chef",
			"[5,player] remoteExecCall [""ALF_fnc_copSetLevel"",life_pInact_curObject];",
			"life_coplevel > 5"],
		["[G] Passer Major",
			"[6,player] remoteExecCall [""ALF_fnc_copSetLevel"",life_pInact_curObject];",
			"life_coplevel > 6"],
		["[G] Passer Sous-Lieutenant",
			"[7,player] remoteExecCall [""ALF_fnc_copSetLevel"",life_pInact_curObject];",
			"life_coplevel > 7"],
		["[G] Passer Lieutenant",
			"[8,player] remoteExecCall [""ALF_fnc_copSetLevel"",life_pInact_curObject];",
			"life_coplevel > 8"],
		["[G] Passer Capitaine",
			"[9,player] remoteExecCall [""ALF_fnc_copSetLevel"",life_pInact_curObject];",
			"life_coplevel > 9"],
		["[G] Passer Commandant",
			"[10,player] remoteExecCall [""ALF_fnc_copSetLevel"",life_pInact_curObject];",
			"life_coplevel > 10"],
		["[G] Passer Lieutenant-Colonel",
			"[11,player] remoteExecCall [""ALF_fnc_copSetLevel"",life_pInact_curObject];",
			"life_coplevel > 11"],
		["AJOUTER CYNO.",
			"[""CYNO"",player] remoteExecCall [""ALF_fnc_copSetLic"",life_pInact_curObject];",
			"life_gendarme_service && {life_copLevel > 6}"],
		["RETIRER CYNO.",
			"[""NOCYNO"",player] remoteExecCall [""ALF_fnc_copSetLic"",life_pInact_curObject];",
			"life_gendarme_service && {life_copLevel > 6}"],
		["AJOUTER GIGN",
			"[""GIGN"",player] remoteExecCall [""ALF_fnc_copSetLic"",life_pInact_curObject];",
			"life_gendarme_service && {life_copLevel > 6}"],
		["RETIRER GIGN",
			"[""NOGIGN"",player] remoteExecCall [""ALF_fnc_copSetLic"",life_pInact_curObject];",
			"life_gendarme_service && {life_copLevel > 6}"],
		["AJOUTER PSIG",
			"[""PSIG"",player] remoteExecCall [""ALF_fnc_copSetLic"",life_pInact_curObject];",
			"life_gendarme_service && {life_copLevel > 6}"],
		["RETIRER PSIG",
			"[""NOPSIG"",player] remoteExecCall [""ALF_fnc_copSetLic"",life_pInact_curObject];",
			"life_gendarme_service && {life_copLevel > 6}"],
		["AJOUTER SR",
			"[""SR"",player] remoteExecCall [""ALF_fnc_copSetLic"",life_pInact_curObject];",
			"life_gendarme_service && {life_copLevel > 6}"],
		["RETIRER SR",
			"[""NOSR"",player] remoteExecCall [""ALF_fnc_copSetLic"",life_pInact_curObject];",
			"life_gendarme_service && {life_copLevel > 6}"],
		["AJOUTER PMO",
			"[""PMO"",player] remoteExecCall [""ALF_fnc_copSetLic"",life_pInact_curObject];",
			"life_gendarme_service && {life_copLevel > 6}"],
		["RETIRER PMO",
			"[""NOPMO"",player] remoteExecCall [""ALF_fnc_copSetLic"",life_pInact_curObject];",
			"life_gendarme_service && {life_copLevel > 6}"],
			
		["[P] Virer des Pompiers",
			"[0,player] remoteExecCall [""ALF_fnc_medSetLevel"",life_pInact_curObject];",
			"life_medicLevel > 2"],
		["[P] Passer Sapeur",
			"[1,player] remoteExecCall [""ALF_fnc_medSetLevel"",life_pInact_curObject];",
			"life_medicLevel > 1"],
		["[P] Passer Sapeur 1ere Cl.",
			"[2,player] remoteExecCall [""ALF_fnc_medSetLevel"",life_pInact_curObject];",
			"life_medicLevel > 2"],
		["[P] Passer Caporal",
			"[3,player] remoteExecCall [""ALF_fnc_medSetLevel"",life_pInact_curObject];",
			"life_medicLevel > 3"],
		["[P] Passer Caporal-Chef",
			"[4,player] remoteExecCall [""ALF_fnc_medSetLevel"",life_pInact_curObject];",
			"life_medicLevel > 4"],
		["[P] Passer Sergent",
			"[5,player] remoteExecCall [""ALF_fnc_medSetLevel"",life_pInact_curObject];",
			"life_medicLevel > 5"],
		["[P] Passer Sergent-Chef",
			"[6,player] remoteExecCall [""ALF_fnc_medSetLevel"",life_pInact_curObject];",
			"life_medicLevel > 6"],
		["[P] Passer Adjudant",
			"[7,player] remoteExecCall [""ALF_fnc_medSetLevel"",life_pInact_curObject];",
			"life_medicLevel > 7"],
		["[P] Passer Adjudant-Chef",
			"[8,player] remoteExecCall [""ALF_fnc_medSetLevel"",life_pInact_curObject];",
			"life_medicLevel > 8"],
		["[P] Passer Lieutenant",
			"[9,player] remoteExecCall [""ALF_fnc_medSetLevel"",life_pInact_curObject];",
			"life_medicLevel > 9"],
		["[P] Passer Capitaine",
			"[10,player] remoteExecCall [""ALF_fnc_medSetLevel"",life_pInact_curObject];",
			"life_medicLevel > 10"],
		["ADD/SUP SAMU",
			"[11,player] remoteExecCall [""ALF_fnc_medSetLevel"",life_pInact_curObject];",
			"life_medicLevel > 8"],
			
		["[P] Virer du Service Publique",
			"[0,player] remoteExecCall [""ALF_fnc_pubSetLevel"",life_pInact_curObject];",
			"life_publique > 6"],
		["[P] Passer Grade 1",
			"[1,player] remoteExecCall [""ALF_fnc_pubSetLevel"",life_pInact_curObject];",
			"life_publique > 6"],
		["[P] Passer Grade 2",
			"[2,player] remoteExecCall [""ALF_fnc_pubSetLevel"",life_pInact_curObject];",
			"life_publique > 6"],
		["[P] Passer Grade 3",
			"[3,player] remoteExecCall [""ALF_fnc_pubSetLevel"",life_pInact_curObject];",
			"life_publique > 6"],
		["[P] Passer Grade 4",
			"[4,player] remoteExecCall [""ALF_fnc_pubSetLevel"",life_pInact_curObject];",
			"life_publique > 6"],
		["[P] Passer Grade 5",
			"[5,player] remoteExecCall [""ALF_fnc_pubSetLevel"",life_pInact_curObject];",
			"life_publique > 6"],
		["[P] Passer Grade 6",
			"[6,player] remoteExecCall [""ALF_fnc_pubSetLevel"",life_pInact_curObject];",
			"life_publique > 6"],
		["[P] Passer Grade 7",
			"[7,player] remoteExecCall [""ALF_fnc_pubSetLevel"",life_pInact_curObject];",
			"life_publique > 6"],
		["[P] Passer Grade 8",
			"[8,player] remoteExecCall [""ALF_fnc_pubSetLevel"",life_pInact_curObject];",
			"life_publique > 7"]
	]
] spawn ALF_fnc_interactions_create;

//licence_pilotTarget=true; licence_gunTarget=true; [] spawn {closedialog 0; [player] spawn ALF_fnc_interactions_player_to_player_basics;}